### ISSUE TITLE
How to get non-primitive last evaluated value

### ISSUE THREAD

**Issue by vlkosinov** [laverdet/isolated-vm#102]
Hi! Thanks a lot for this library!

As I understand it, in `script.run`, the values of non-primitives are simply ignored in `Unwrap` method:

[1] https://github.com/laverdet/isolated-vm/blob/master/src/script_handle.cc#L64
[2] https://github.com/laverdet/isolated-vm/blob/master/src/transferable.cc#L12
[3] https://github.com/laverdet/isolated-vm/blob/master/src/isolate/class_handle.h#L429

So is there any another way to access the last evaluated value?

**Comment by laverdet** [comment]
Is it possible to modify the script to wrap the last value in a Reference or ExternalCopy?

**Comment by vlkosinov** [comment]
Of course! But I have no idea how to do this reliably and avoid AST manipulations (eg via babel) on original code, which seem like a big overhead for this task

**Comment by vlkosinov** [comment]
Is it possible to make Script.run to return ExternalCopy? 😊

**Comment by laverdet** [comment]
Sorry for the delay, I was off the grid for the week.

Can't you wrap it yourself via eval?
```js
let code = 'function hello() {};';
let fn = isolate.compileScriptSync(`new ivm.Reference(eval(${JSON.stringify(code)}))`).runSync(context);
console.log(fn);
```

If you already have a lot of code that depends on this kind of thing I assume that you're already using eval somewhere on the backend?

**Comment by vlkosinov** [comment]
Hello!

Your code logs `undefined`, but “eval” seems like a possible solution if obtain its result inside the isolate.

I don’t like eval, it doesn’t look good in stack traces🙃

Now I parse the input code with [cherow](https://github.com/cherow/cherow), and if the last AST node is an expression, I wrap it like this:

```js
  const lastNodeCode = originalCode.slice(lastNode.start);
  const preExpressionCode = originalCode.slice(0, lastNode.start);
  const modifiedLastExpression =
    ";this.LAST_EXPRESSION_RESULT=" + lastNodeCode;
  const modifiedCode = preExpressionCode + modifiedLastExpression;
```
then I execute this code at 'runtime', which catches this value and sends back from the isolate   

```js
(function runtime(inputCodeModule) {
  const context = {};
  inputCodeModule.call(context);
  const result = context.LAST_EXPRESSION_RESULT;

  handleIsolateResult.applySync(undefined, [
    new ivm.ExternalCopy(context.LAST_EXPRESSION_RESULT).copyInto()
  ]);
})(function inputCodeModule() {
  // modified code here
})
```
 
So I can say that it is possible to get the last value, but it is a little bit tricky 🙂

Thank you!

**Comment by laverdet** [comment]
You're right, the reference returned by my example is actually undefined. This is because `function hello() {};` is a FunctionStatement and not an ExpressionStatement. The following example will show what I mean:

```js
const ivm = require('isolated-vm');
let isolate = new ivm.Isolate;
let context = isolate.createContextSync();
context.global.setSync('ivm', ivm);

let code = 'function hello() {}; hello;';
let fn = isolate.compileScriptSync(`new ivm.Reference(eval(${JSON.stringify(code)}))`).runSync(context);
console.log(fn, fn.typeof);
```

Logs: `Reference {} 'function'`

**Comment by vlkosinov** [comment]
Thanks @laverdet, got this! ❤️

**Comment by jakajancar** [comment]
It would be really nice if there was a way to get back objects/arrays without modifying user code (and messing with column/line offsets, and affecting parsing errors).

**Comment by laverdet** [comment]
@jakajancar what is your use case?

**Comment by jakajancar** [comment]
@laverdet
Imagine a SaaS app like JIRA that allows an admin to enter a script to customize behavior, e.g. list valid states for an issue to transition to. Context would contain information about the issue. Return would be a list (array) of valid destination states, potentially with some other attributes to set in the transition.

**Comment by laverdet** [comment]
@jakajancar can you just have the user put `return whatever;` and then wrap the supplied code in a function? Then you would call the generated function and do what you need to do get it back into your application. This is similar to what nodejs does for modules.

The "return last expression" semantics aren't really javascripty and I would strongly recommend against exposing that to users.

**Comment by laverdet** [comment]
Though if you do want to go with the return last expression semantics you can do the eval trick I mentioned above.

**Comment by jakajancar** [comment]
A cleaner way to get non-primitive returns without glueing strings together is:

```
// Prepare the source code.
v8::ScriptOrigin origin(v8::String::NewFromUtf8(isolate, "user", v8::NewStringType::kNormal).ToLocalChecked());
v8::ScriptCompiler::Source source(v8::String::NewFromUtf8(isolate, line.c_str(), v8::NewStringType::kNormal).ToLocalChecked(), origin);

// Compile the source code.
v8::Local<v8::Function> function = v8::ScriptCompiler::CompileFunctionInContext(context, &source, 0, {}, 0, {}).ToLocalChecked();

// Run the script to get the result.
v8::Local<v8::Value> result = function->Call(context, context->Global(), 0, {}).ToLocalChecked();
```

**Comment by laverdet** [comment]
@jakajancar I'm not sure what you're suggesting? Did you read my suggestion about `eval`?
