### ISSUE TITLE
Segmentation fault in createSnapshot when using Typed array

### ISSUE THREAD

**Issue by vlkosinov** [laverdet/isolated-vm#103]
The node process crashes when trying to run createSnapshot for code with typed arrays.

```js
// test-snapshot.js
const ivm = require("isolated-vm");
const snapshot = ivm.Isolate.createSnapshot([
  // and with any others Typed arrays (Uint8Array, Float64Array, etc)
  { code: "const array = new Int32Array(128)" }
]);

```

```bash
node ./test-snapshot.js
[1]    28624 segmentation fault  node ./test-snapshot.js
```

Env versions:
`node: '8.11.3', v8: '6.2.414.54'`
`node: '10.15.3', v8: '6.8.275.32-node.51`
`node: '11.12.0' v8: '7.0.276.38-node.18'`
Mac OS: 10.14.3 

Any ideas?

**Comment by laverdet** [comment]
Thanks, this is a weird case in the v8 API so there were some extra things I had to hook. I'll push this out to npm later today.

**Comment by vlkosinov** [comment]
Thank you!
