### ISSUE TITLE
Question: Recursively referencing a object.

### ISSUE THREAD

**Issue by thesayyn** [laverdet/isolated-vm#104]
Hi. Thanks for this awesome project!

I have an question about passing a complex object into isolate.

In my example i have an expressjs instance running in my main application. 
Also i have an isolate instance which contains an expressjs route handler.

```typescript
function  handle(req, res) {
// business code
}
```
so after i evaluate this i'm invoking it with

```typescript
const fn = await context.global.get('a');
const res = await fn.apply(undefined, [new ivm.Reference(req), new ivm.Reference(res)]);
```
Of course this code doesn't work but i think understood that what i'm trying to do.

My question is how i can pass this complex express res,req  object to isolate in a good way.

I think only way is to achieve that writing an proxy object which implements the obvious methods and variables in res, req object or wrapping each object directly and recursively with Reference.

Thanks again.

**Comment by thesayyn** [comment]
@laverdet Sorry for disturbing..

**Comment by laverdet** [comment]
Unfortunately there is no quick and easy way to do what you're trying to do. You must consider that with full access to the `req` or `res` objects it may be possible for a user to create a new HTTP server on a different port, or to interfere with other requests on the same server. Instead you'll have to expose safe versions of the features you want in the isolate.
