### ISSUE TITLE
Add option to remove script from being debuggable in inspector

### ISSUE THREAD

**Issue by ErkoKnoll** [laverdet/isolated-vm#105]
Hi,

It would be nice if there was a flag to exclude certain scripts from showing up and being navigable in inspector.

Currently as a workaround I'm filtering out certain messages in websocket proxy not to show certain scripts in navigation pane, but this approach is rather hacky and it would be nice if there was a proper way to restrict access to certain scripts.

Motivation behind this request is that I have a bootstrap script that get loaded before user scripts and I don't want to expose the content of bootstrap script to users via inspector.

**Comment by laverdet** [comment]
This isn't a supported feature in v8. Notably, nodejs has a similar issue [nodejs/node#11893] which is still outstanding. In Devtools you can "blackbox" a script, but this is a feature that the user has to opt-in to.

If you really want to hide the implementation details of something you can put it in another context which doesn't enable the inspector. Care must be taken to avoid leaking access to your context's objects though. I've modified `inspector-example.js` to show you how you can do this, and the kinds of problems you will run into. If you run this in the inspector you will find that you can't step into `foo()` or see the implementation details anywhere. I'm not sure if this is guaranteed at all though, so I would avoid using this for any secure information.

```js
'use strict';
let WebSocket = require('ws');
let ivm = require('./isolated-vm');

/**
 * Note that allowing untrusted users to access the v8 inspector may result in security issues.
 * Maybe it won't though, I don't know. I haven't really looked into everything the inspector can
 * do.
 */

// Launch an infinite loop in another thread
let isolate = new ivm.Isolate({ inspector: true });
(async function() {
	// Build internal context (secret to inspector)
	let internalContext = await isolate.createContext();
	internalContext.global.setIgnored('ivm', ivm);
	let internalLibraryReference = await (await isolate.compileScript(`new ivm.Reference({
	foo() {
		// secrets here
		return 'foo';
	},

	badExample() {
		if (({}).evil !== undefined) {
			throw new Error('A bad thing happened.');
		}
		return { json: 'data' };
	}
});`)).run(internalContext);

	// Build user context
	let context = await isolate.createContext({ inspector: true });
	context.global.setIgnored('internal', internalLibraryReference.derefInto());

	// Use of eval avoids this showing up in the scripts list
	await (await context.global.get('eval')).apply(undefined, [`
foo = Function.prototype.bind.apply(internal.foo);
badExample = internal.badExample;
delete internal;
`]);

	// Run user code
	let script = await isolate.compileScript('for(;;){foo(); debugger;}', { filename: 'example.js' });

	// uncomment to see a bad thing happen:
	// let script = await isolate.compileScript('for(;;){let value = badExample(); value.__proto__.evil = 1; debugger;}', { filename: 'example.js' });
	// or this one:
	// let script = await isolate.compileScript('for(;;){badExample.__proto__.__proto__ = 1; badExample(); debugger;}', { filename: 'example.js' });
	await script.run(context);
}()).catch(console.error);

// Create an inspector channel on port 10000
let wss = new WebSocket.Server({ port: 10000 });

wss.on('connection', function(ws) {
	// Dispose inspector session on websocket disconnect
	let channel = isolate.createInspectorSession();
	function dispose() {
		try {
			channel.dispose();
		} catch (err) {}
	}
	ws.on('error', dispose);
	ws.on('close', dispose);

	// Relay messages from frontend to backend
	ws.on('message', function(message) {
		try {
			channel.dispatchProtocolMessage(message);
		} catch (err) {
			// This happens if inspector session was closed unexpectedly
			ws.close();
		}
	});

	// Relay messages from backend to frontend
	function send(message) {
		try {
			ws.send(message);
		} catch (err) {
			dispose();
		}
	}
	channel.onResponse = (callId, message) => send(message);
	channel.onNotification = send;
});
console.log('Inspector: chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:10000');
```

**Comment by laverdet** [comment]
Oh and if all you want to do is make a script not show up in the file list you can just use the eval trick I showed in my example. You will still be able to step into the functions and see the implementation detail though.

**Comment by ErkoKnoll** [comment]
Hi, thanks a lot for clearing this up! Either using eval or filtering out certain ws messages not to show a script in navigation pane will do the trick for me.

**Comment by mustafaakin** [comment]
Hello, sorry to pop this. How do we open this page in Chrome? It does not seem to recognize chrome-devtools anymore. I've navigated to chrome://inspect and added 127.0.0.1:10000 as target but it does not seem to pick up.
