### ISSUE TITLE
Advice on running with an HTTP server

### ISSUE THREAD

**Issue by DominicTobias** [laverdet/isolated-vm#106]
Hi,

Many thanks for this script, this is a question not an issue so I'll close it but would appreciate your advice.

In your examples you create a single isolate. Let's say I'm running an HTTP server and I want to run code in an isolate for each request (lot's of different code). I may also want to cache the Scripts (I guess this is a high level wrapper around the compiled WASM).

What is the best practice/most efficient way of doing this - should I create an isolate for every request that needs to run code, or should I re-use one, or one per core, or?

Thanks for any tips.

**Comment by laverdet** [comment]
Sorry for the delay on responding to this.

The answer here really just depends on what you're building. A new isolate per request sounds like overkill. Each isolate you create has some overhead (in terms of CPU used to build the isolate and memory to keep it around), but what you get is independence from the other isolates. For instance, every context in a single isolate shares garbage collection. Therefore if one context is running poorly written code which has a reference leak somewhere it will slow down other contexts running in that same isolate. Garbage collection just runs whenever it feels like, so when a context loses the garbage collection lottery it has to pay for the garbage accumulated by all the other contexts. On the other hand, sharing resources is sometimes good. If your contexts are all running the same function over and over they might be able to reuse some of the work from the last time the function ran, even if it was in a different context.

If you want to cache a script you might look into the snapshot feature, which allows you to save an isolate with compiled code which can be used to create many isolates already ready to go.

**Comment by DominicTobias** [comment]
Cool thanks for the info!
