### ISSUE TITLE
Accessing V8 microtask queue

### ISSUE THREAD

**Issue by ErkoKnoll** [laverdet/isolated-vm#109]
Hi,

Is there a way to get an access to V8's microtask queue? I'm interested to know if anything is still either in the queue or is being currently processed. The reason why I'm interested in it is that Promises are being executed in microtask queue and currently I have no way of knowing when I can dispose the isolate, which should happen when all user code has been processed, including anything on Promise chains.

One solution is to replace the default implementation of Promise with one of Sync Promises implementations, but I was hoping that perhaps there is a way to access that information so I know exactly when nothing else needs processing and can then shut down the Isolate safely, and also can keep the default Promise implementation.

**Comment by laverdet** [comment]
I don't think the microtask queue is going to help you. isolated-vm won't return until the microtask queue is flushed, you can prove that with this example:
```js
const ivm = require('isolated-vm');
let isolate = new ivm.Isolate;
let context = isolate.createContextSync();
isolate.compileScriptSync('Promise.reject(new Error);').runSync(context);
```

If you run this example you'll see that the error is thrown from `runSync`.. but the script doesn't technically throw an error it starts a microtask which throws an error. isolated-vm runs the script, then flushes the isolate's microtask queue which is when it detects there was an error.

**Comment by ErkoKnoll** [comment]
Thanks for pointing that out, but I think my scenario is little bit more complicated. In my case microtasks are being spawned and executed after the initial synchronous script execution. I'm scheduling some IO tasks on main node event loop and once any of those tasks are completed I'm then calling a callback (via Reference.apply) in an Isolate instance which in turn returns a Promise (to keep in line with standard spec) for the end user. But as the main synchronous script execution is finished I'm keeping track of async tasks that are being executed on the main event loop to know when the event loop has been cleared and when I can finally terminate the Isolate. But since I'm exposing a Promise on the Isolate side, and Promise 'resolve' invocations are deferred via microtasks, then currently I have no way of knowing when 'resolve' or 'reject' invocations have completed their promise chain so I can finally shut down the Isolate safely without risking terminating the Isolate in the middle of the last async callbacks's execution that takes place on microtask queue because of the nature how Promises work.

There are higher level workarounds I can try to solve the problem with, such as replacing default Promise implementation with Sync Promise where 'resolve' and 'reject' invocations are being executed synchronously, or I can try overwriting 'then' and 'catch' methods of default implementation and keep track of their invocations, but I think the most elegant and the least error prone way is to know if there is anything left to execute on Isolate's microtask queue, or any other mechanism to tell if the Isolate is still processing anything.

**Comment by laverdet** [comment]
Would you mind putting together a short example which shows the condition you're referring to?

**Comment by ErkoKnoll** [comment]
I added an example how it fails for me in under some circumstances. If you run it it then most likely it will work properly, but you can see the logic I'm dealing with. This logic actually works for the most of the time, but fails under certain circumstances that I currently cannot reproduce with a simple example.

I even tried adding 'randomCallback' function to interrupt microtask queue from being executed right away, but I think V8 is pretty clever when it comes to executing those tasks and right now I haven't found a way to reproduce the case with this simple example. If I can come up with a reproducible case I'll update the code, maybe you can think of a way to force 'resolve' to be deferred into microtask queue so it won't be processed synchronously, which seems to be the case with this example.

[microtasks.txt](https://github.com/laverdet/isolated-vm/files/3181481/microtasks.txt)

**Comment by ErkoKnoll** [comment]
Now after doing bit more testing and reverting some experimental stuff looks like your library calls wait out whatever V8 is doing. Not sure why it works now, I did however upgrade binaries that were several months old that were combined with latest JS codebase, maybe something went wrong because of that. 

I'll do some more testing and if I cant reproduce it any longer, I'll close the issue.

So as long as you think there is no way that the user can schedule anything on microtask queue without your library knowing about it then there is no reason to read microtask queue.

**Comment by ErkoKnoll** [comment]
I think it was my mistake after all, thank you for pointing me in right direction and helping me to find it.

**Comment by laverdet** [comment]
I'm glad you got the issue resolved. I do want to point out one complication. There's generally 2 things which will cause an isolate to "wake up" and run JS code. First is by `apply`, `run`, `evaluate`.. these are simple in that as soon as the promise resolves or the sync version returns you can be sure that the isolate is done with its work and no tasks remain. The second is more subtle.. which is by *returning* from a function that was invoked asynchronously by the isolate.

For example:

```js
const ivm = require('isolated-vm');
let isolate = new ivm.Isolate;
let context = isolate.createContextSync();
context.global.setSync('print', new ivm.Reference(function(...args) {
  console.log(...args);
}));
let script = isolate.compileScriptSync(`
  print.apply(undefined, ['in isolate']).then(function() {
    print.apply(undefined, ['in promise']);
  });
`);
script.runSync(context);
console.log('run finished');
```

How could you ever tell that the work is done? The user could keep chaining promises on new calls to `print` as much as they want. Each time the invoked function returns it wakes up the isolate and resolves the promise. If there are listeners on the promise it will run that code which might run more code, and the default nodejs isolate will *not* get a notification that the new work has completed. In this case you can probably work around it by always initiating work from the parent isolate, but based on your description this isn't what was happening.

**Comment by ErkoKnoll** [comment]
Yeah, it was my mistake, your library was acting correctly, and even better than expected considering how V8 can queue some calls, very awesome stuff btw.
