### ISSUE TITLE
Snapshot encoding issue

### ISSUE THREAD

**Issue by Jerska** [laverdet/isolated-vm#114]
Hey @laverdet ! I'm here to ask for you help again. :)

We stumbled on a weird issue when using the `snapshot` feature. The encoding of strings in the snapshot is weirdly messed up.
The strings really look like `utf-8` encoding interpreted as `latin-1`.

Here's our repro script:

```js
let ivm = require('isolated-vm');

const snapshot = ivm.Isolate.createSnapshot([{
  code: `
    this.testAscii = 'e';
    this.testAssigned = 'è';
    this.testWarmedUp = () => 'è';
    this.testNotWarmedUp = () => 'è';
  `
}], 'this.testWarmedUp()');

let isolate = new ivm.Isolate({ memoryLimit: 128, snapshot });

let context = isolate.createContextSync();
let jail = context.global;
jail.setSync('global', jail.derefInto());
jail.setSync('_ivm', ivm);
jail.setSync('_log', new ivm.Reference(function(...args) {
  console.log(...args);
}));

let bootstrap = isolate.compileScriptSync('new '+ function() {
  let ivm = _ivm;
  delete _ivm;

  let log = _log;
  delete _log;

  global.console = {
    log: function(...args) {
      log.applySync(undefined, args.map(arg => new ivm.ExternalCopy(arg).copyInto()));
    }
  };
});

bootstrap.runSync(context);

isolate.compileScriptSync(`
  console.log('testAscii:', this.testAscii);
  console.log('testAssigned:', this.testAssigned);
  console.log('testWarmedUp:', this.testWarmedUp());
  console.log('testNotWarmedUp:', this.testNotWarmedUp());
  console.log('testNotSnapshot:', 'è');
`).runSync(context);
```

Output:
```sh
testAscii: e
testAssigned: Ã¨
testWarmedUp: Ã¨
testNotWarmedUp: Ã¨
testNotSnapshot: è
```

As you can see, it works just fine outside of the snapshot.

cc @JonathanMontane

**Comment by laverdet** [comment]
Thanks I fixed this in master. I won't have time to push a new release on npm for at least a few weeks though.

**Comment by Jerska** [comment]
Oh wow, thanks so much for the quick response and fix!
We'll use a commit ref in the meantime, no worries.

**Comment by laverdet** [comment]
Hi 2.0.0 is on npm now which includes this fix. It contains a pretty significant overhaul to the heap limits logic so please don't hesitate to open a new issue if there's any unexpected breaking changes.
