### ISSUE TITLE
Question: what exceptions are safe to expose

### ISSUE THREAD

**Issue by jakajancar** [laverdet/isolated-vm#115]
I would like to expose some errors to the user (author of the untrusted code). What is a proper way to do it safely, when 1) compiling and 2) running?

E.g.:

        try {
            const compiled = isolate.compileScriptSync('1 + 1asd')
        } catch (e) {
            res.writeHead(400, { 'Content-Type': 'application/json; charset=utf-8' });
            res.end(JSON.stringify({
                message: e.stack
            }));
            return;
        }

already exposes more than needed, including some sensitive information (path on host):

```
SyntaxError: Invalid or unexpected token [<isolated-vm>:1:5]
    at Server.<anonymous> (/app/services/user-code-evaluator/bin/user-code-evaluator:18:38)
    at emitTwo (events.js:126:13)
    at Server.emit (events.js:214:7)
    at parserOnIncoming (_http_server.js:660:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at (<isolated-vm boundary>)
    at /app/services/user-code-evaluator/bin/user-code-evaluator:18:38
```

**Comment by laverdet** [comment]
It's up to you what you would like to expose to the user. I suggest using the `filename` option on `compileScript` to prefix the user's script name with something like `~sandbox/${filename}` and then only show them the stack trace that contains that string.

**Comment by jakajancar** [comment]
That's a great suggestion, thank you!

**Comment by jakajancar** [comment]
Actually, the user can just do `new Error('foo')).stack`, without ever throwing, to get paths outside of the "vm boundary".

**Comment by laverdet** [comment]
```js
const ivm = require('isolated-vm');
function secret() {
	let isolate = new ivm.Isolate({ memoryLimit: 128 });
	console.log(isolate.compileScriptSync('(new Error).stack').runSync(isolate.createContextSync()));
}
secret();
```

Does not log "secret".
