### ISSUE TITLE
Question: sync vs async performance

### ISSUE THREAD

**Issue by jakajancar** [laverdet/isolated-vm#116]
Assuming executed scripts are synchronous and return immediately, should it be faster to use `compileScriptSync`/`runSync`/exceptions or or `compileScript`/`run`/promises?

**Comment by laverdet** [comment]
I don't think it makes too much of difference. In general I would recommend the async/promise API. The sync methods may have marginally lower latency but that's at the cost of tying up your nodejs process and also you lose out on multi-threading.
