### ISSUE TITLE
Feature request: ability to pause execution of an isolate

### ISSUE THREAD

**Issue by kirjavascript** [laverdet/isolated-vm#119]
The title of this pull request may not be exactly what I want, here is my use case;

I have a timeout for execution of an isolate, but if the user triggers some async behaviour with applySyncPromise, I dont want the time taken there to contribute to the timeout time

If I could call something to 'pause' execution before the async and resume it afterwards that should resolve it, or perhaps there's a better way to structure this

Alternatively, I could scrap using isolated-vm's timeout function and manage the timeout myself, but that would be a little more awkward.

**Comment by laverdet** [comment]
Perhaps the timeout should just pause automatically when entering a new isolate?

#108 mentions some ambiguities here with this parameter.

**Comment by kirjavascript** [comment]
> when entering a new isolate?

Not sure if I have the right terminology here, but I'm not creating a new isolate when I want to pause

Here's a code snippet from my project with places where I want to pause the timer indicated;

```javascript
jail.setSync('_require', new ivm.Reference((str) => (
    new Promise((resolve, reject) => {
        // pause here
        acquire(str)
            .then(obj => {
                // resume here
                resolve(obj.toString())
            })
            .catch(e => reject(new Error(e.message)));
    })
)));
```

From seeing the other issue, it seems like the timer code is quite complex, if the implementation of this is too much of a problem the solution can definitely be done by users purely in javascript so should not be high priority.

**Comment by laverdet** [comment]
I should have said entering a "different" isolate instead of a "new" isolate. When you call `applySyncPromise` or `applySync` the current isolate is suspended and execution resumes in a different isolate. So in this case I think that maybe the better behavior is to pause timeouts. If I'm not mistaken the timeout won't even trigger until the `apply` call returns anyway.

**Comment by kirjavascript** [comment]
ah yes, this would be perfect!
