### ISSUE TITLE
Question: Is it possible to bootstrap nodejs in a isolate?

### ISSUE THREAD

**Issue by thesayyn** [laverdet/isolated-vm#120]
Is it possible to bootstrap nodejs in a isolate?

If it is possible, do you have any idea about how can it be accomplished?

Thank you  :)

**Comment by laverdet** [comment]
What is your goal? Why create a new isolate if you want to give that isolate access to everything in nodejs?

**Comment by thesayyn** [comment]
Actually my goal is make a node-like execution context that completely isolated from main process. At the same time support for most packages in registry.  

the isolate won't contain all the features from nodejs. 

My requirements are 
- Support for mock require. In memory modules like database so we don't open database connections over and over again
- Support for native require 
- Memory synchronisation between isolates

**Comment by laverdet** [comment]
I would recommend spinning up a new process and using something like [vm2](https://github.com/patriksimek/vm2.git) to restrict access.

**Comment by thesayyn** [comment]
Currently, we are using vm2 but we need to share memory between isolates which is not possible in node js.

**Comment by laverdet** [comment]
I'm not sure what you mean by "share memory"

**Comment by thesayyn** [comment]
Let me explain with an example. 

We have one object allocated in memory and it has functions like `write`, `flush`, `end`.

We invoke a function in the isolate with apply function and the function makes a heavy convert operation inside the isolate by using modules from npm.

```typescript
const p = require('an-converter-module');
function process(pt: PassThrough) {
   const convert = p.convert('');
   convert.on('data', data => pt.write(data)) // Data is a buffer
   convert.on('end', () => pt.end())
}
```

I can use vm2 (in the main process and currently we are using it), I don't have control over it.
I made it work in isolated-vm but I still need nodejs environment in my isolate.

Actually here is my work and a more detailed explanation about what I am trying to accomplish: https://github.com/spica-engine/spica/pull/6 

Thank you for your time and help :)

**Comment by laverdet** [comment]
You can solve some of your issues with [worker_threads](https://nodejs.org/api/worker_threads.html) which run in the same process but in a different isolate and thread. You can share `SharedArrayBuffer` instances or transfer `ArrayBuffer` instances between worker threads.

The main conflict here is that the nodejs runtime is just not secure in the way that you want it to be. If you want to use isolated-vm for this you'll have to build wrappers around the nodejs features you want to support. If you want to use vm2 you'll have to deal with the fact that your process can crash at any time.

**Comment by LeonardoRochaInacio** [comment]
> I would recommend spinning up a new process and using something like [vm2](https://github.com/patriksimek/vm2.git) to restrict access.

Hi laverdet, do you think is it safe to open a child_process and use vm2 in that new child process? My goal is use LucidORM to control database in a isolated enviroment. I mean, will using vm2 in a child process solve the sandbox break problem?

**Comment by laverdet** [comment]
My understanding is that vm2 is critically broken. You have to assume that everything in the process can be accessed from within the vm2 realm.
