### ISSUE TITLE
Throwing subclasses of Error won't work

### ISSUE THREAD

**Issue by ErkoKnoll** [laverdet/isolated-vm#122]
Hi,

Issue is rather simple, if I'm throwing an Error inside the Isolate then it properly gets copied back, however if the thrown object is a subclass of an Error then it won't, but will throw instead: `An object was thrown from supplied code within isolated-vm, but that object was not an instance of `Error`.`

Would be nice if Error subclasses would be sent back in the same fashion as errors, as they contain the same properties.

Code for reproducing:
```
class CustomError extends Error {
}

throw new CustomError('message');
```

I'm currently using version 1.7.10, is it maybe fixed in a newer version? Upgrading my stack is a rather tedious process, thats why I'm asking.

**Comment by laverdet** [comment]
The behavior is the same on the latest release too. The problem is a little tricky to fix but I have some ideas.

**Comment by ErkoKnoll** [comment]
Thanks a lot!
