### ISSUE TITLE
How to import a node module

### ISSUE THREAD

**Issue by cyberwombat** [laverdet/isolated-vm#124]
I am a little unclear on the limitations of using a node module in the isolated code. Let's say the http module. Is it possible? I have been looking at CloudFlare's Workers which seem to use Isolates - I think they made certain modules available to the isolated code such as fetch but unsure how.

**Comment by cyberwombat** [comment]
Ok i think I understand. I was incorrectly looking at the `compileModule` function thinking I could use this for native modules. I can see how I can pass individual functions using the log example so I think that will work - create wrapper for all the desired functions.

**Comment by VityaSchel** [comment]
Can you provide an example? I'm stuck on this, my goal is to be able to import simple node modules inside isolated-vm

**Comment by jakeonfire** [comment]
for `moment`/`moment-timezone`, i was able to import it by packaging it with `rollup`:

`index.js`:
```js
import moment from "moment-timezone"
```

`rollup.config.js`:
```js
import commonjs from '@rollup/plugin-commonjs';
import json from '@rollup/plugin-json';
import { nodeResolve } from '@rollup/plugin-node-resolve';

export default {
  input: 'index.js',
  output: {
    dir: 'output',
    format: 'cjs'
  },
  plugins: [commonjs(), json(), nodeResolve()]
};
```

packaged with: `npx rollup --config rollup.config.js --bundleConfigAsCjs`

and then to import the resulting file into the isolate context:
```js
const externalDepsSource = fs.readFileSync("./lib/packager/output/index.js").toString()
context.evalSync(`
  const moment = (function() {
    ${externalDepsSource}
    return moment;
  })();
`)
