### ISSUE TITLE
How to get result *out* of isolate

### ISSUE THREAD

**Issue by Jaaap** [laverdet/isolated-vm#126]
I'm having a hard time doing even the most trivially simple task with isolated-vm:
Given a simple untrustworthy script, get the resulting output
```
const ivm = require('isolated-vm');
let isolate = new ivm.Isolate();
let context = await isolate.createContext();
let script = await isolate.compileScript("let x = {a:1};");
await script.run(context).catch(err => console.error(err));
let output = await context.global.get('x');
console.log(output.deref());
```
result: ` TypeError: Cannot dereference this from current isolate`
I also tried to `return x` but that gives a `SyntaxError: Illegal return statement`

What is the correct way to get data **out** of the isolate?

**Comment by laverdet** [comment]
`deref()` doesn't work to reference a variable in another isolate.

There's lot of different ways you can do this and it depends on your application. In this case you could just do:

```js
const ivm = require('isolated-vm');
let isolate = new ivm.Isolate();
let context = await isolate.createContext();
let script = await isolate.compileScript("let x = {a:1}; JSON.stringify(x);");
let output = await script.run(context).catch(err => console.error(err));
console.log(output);
```

Probably what you want to do is use ExternalCopy from within the isolate. There's examples of this in the docs.

**Comment by Jaaap** [comment]
Super, it works!
Thank you.
