### ISSUE TITLE
Cannot transfer an Error, but can throw one

### ISSUE THREAD

**Issue by elachys** [laverdet/isolated-vm#127]
After updating to 2.0.1 errors are still not transferable.

```
reference.applyIgnored(receiver, [new Error('some error')]);
```
Still gives me the standard non transferrable error message.

**Comment by laverdet** [comment]
This is by design. When an error is thrown the `stack` and `message` fields are copied out and a new error is created on the other side.. all other information is lost. When trying to pass it as an argument it doesn't get this treatment.

**Comment by Strate** [comment]
@laverdet is it possible to copy also a `code` field if this field present on original error object? This is very often pattern to add additional useful info to error.code
