### ISSUE TITLE
Async stack traces

### ISSUE THREAD

**Issue by ErkoKnoll** [laverdet/isolated-vm#128]
Hi,

I'm passing in `--async-stack-traces` option to Node 12 in hopes that V8 Isolate will produce async stack traces, but it does not make any difference right now. I'm wondering if this flag needs to be passed into V8 Isolate when creating it, in which case I would like to request a support for it, as I don't see any option to pass in custom V8 flags right now.

**Comment by laverdet** [comment]
All v8 flags passed on the command line are forwarded to new isolates with the sole exception of `--max-semi-space-size` and `--max-old-space-size`. Could you please post an example of what you're trying to do and what you would expect to happen?

**Comment by ErkoKnoll** [comment]
It is actually working, my mistake was to compiled the script from TS to ES6 which replaced async/await with something that does not work with async stack traces anyway. By compiling to ES2018 async/await stays as is and then async stack traces also work.
