### ISSUE TITLE
Release prebuilt binaries

### ISSUE THREAD

**Issue by ngocdaothanh** [laverdet/isolated-vm#129]
node-gyp is used for building isolated-vm:
https://github.com/nodejs/node-gyp

But node-gyp doesn't support Python 3.

When isolated-vm is used inside other libraries, when users install other libraries, the installation will fail because most users don't have Python 2.

Can isolated-vm release prebuilt binaries like this please?
https://github.com/atom/node-keytar/releases/tag/v4.13.0

**Comment by laverdet** [comment]
Sorry, I don't want to do this. I do this for [node-fibers](https://github.com/laverdet/node-fibers) and it's been a total nightmare. Supposedly gyp works on python 3 and we're just waiting for support from node-gyp. This is being tracked on nodejs/node-gyp#1687 which you I notice you commented on 2 days ago. Anyway, for now python 2 is needed for binary modules on nodejs, that's just the reality of it.

**Comment by ngocdaothanh** [comment]
> But node-gyp doesn't support Python 3.

Memo: node-gyp now supports Python 3.
