### ISSUE TITLE
Dynamic import

### ISSUE THREAD

**Issue by idleman** [laverdet/isolated-vm#130]
I am trying to add support for dynamic import, but I am stuck. I am currently trying to set v8::Isolate::SetHostImportModuleDynamicallyCallback when the isolate is being constructed, similar to how vm.SourceTextModule works in nodejs - but is is never called:

isolate_handle.cc:
```
unique_ptr<ClassHandle> IsolateHandle::New(MaybeLocal<Object> maybe_options) {
  Local<Object> options;
  if (maybe_options.ToLocal(&options)) {
    // setting this callback enables dynamic import
    Local<Value> import_handle = Unmaybe(
      options->Get(context, v8_symbol("importModuleDynamically"))
    );
    if (!import_handle->IsUndefined()) {
      if (!import_handle->IsFunction()) {
        throw js_type_error("`importModuleDynamically` must be a function");			
      }

      Isolate::GetCurrent()->SetHostImportModuleDynamicallyCallback([](
        Local<Context> context,
        Local<ScriptOrModule> referrer,
        Local<String> specifier)
      {
        // Never invoked
        return MaybeLocal<Promise>();
      });
    }
  }
}
```

 What steps is required to add support for dynamic import()? Any guidance?

**Comment by laverdet** [comment]
When you call `Isolate::GetCurrent()` it returns the currently running isolate which in this case is the "parent" isolate. You should be looking for the isolate which was just created.

Anyway, callbacks between isolates are pretty complicated especially when promises are involved. I'll see if I can get to this feature request eventually :)

**Comment by idleman** [comment]
Thanks, it explains it.

Please do. It would be great if dynamic support was supported.
