### ISSUE TITLE
Adding custom code to the global context

### ISSUE THREAD

**Issue by mozrat** [laverdet/isolated-vm#142]
Hello,

I'm am struggling to execute code in an isolated environment that can use classes that I have provided in the context.

With my test below I would want to see the ```Log``` class called.

```
import { expect } from 'chai';
import 'mocha';

const ivm = require('isolated-vm');

describe('isolate-vm', () => {

  it('should execute some simple script', (done) => {

    class Log {
      public debug(msg: string) {
        console.log(`>>> ${msg}`);
      }
    }

    const l = new Log();
    l.debug('hello world - before test');

    const isolate = new ivm.Isolate({ memoryLimit: 128 });
    const context = isolate.createContextSync();

    const jail = context.global;
    jail.setSync('global', jail.derefInto());
    jail.setSync('_ivm', ivm);
    jail.setSync('_Log', new ivm.Reference(Log));
    jail.setSync('foo', 'bar');

    const bootstrap = isolate.compileScriptSync(
      `new function() {

        const ivm = _ivm;
        delete _ivm;

        const Log = _Log;
        delete _Log;
        
        const ClsLog = function(...args) {Log.applySync(undefined, args.map(arg => {new ivm.ExternalCopy(arg).copyInto()}))}; 
        global.Log = new ClsLog();
      
      }`
    );

    bootstrap.runSync(context);

    const hostile = isolate.compileScriptSync('var x = 10;\ny = x + 1;\nLog.debug(`y = ${y}`)\n');

    hostile.run(context).then((result: any) => {
      console.log(result);
      done();
    }).catch((err: any) => {
      console.log(err);
    });
  });

});

```

Running this test results in

```
Debugger listening on ws://127.0.0.1:50302/edeab33c-13d9-4b90-8d73-5e7237732727
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
>>> hello world - before test
Waiting for the debugger to disconnect...

TypeError: Class constructor Log cannot be invoked without 'new'
```

I think the error is misleading, and that the ```Log``` object isn't being transferred into the virtual machine properly.

Appreciate any help or examples

**Comment by laverdet** [comment]
The error message is correct. The `apply` family of methods invokes a function but a class must be invoked as a constructor. It is impossible to transfer an arbitrary class or object into an isolate, you have to create delegating functions to do what you want to do.

You can observe this in plain Javascript:
```js
class Log {
  debug(msg) {
    console.log(`>>> ${msg}`);
  }
}
const logger = Log.apply(undefined, []);
```

Throws: `TypeError: Class constructor Log cannot be invoked without 'new'`

**Comment by mozrat** [comment]
Thank you, obviously need to brush up on my basic Javascript :)

Is there a way to invoke the class inside the isolate after transferring it in? I have tried other things like ```deref``` but without success

Appreciate your help

**Comment by laverdet** [comment]
It really depends on what you're trying to do. You've posted a unit test for an abstract problem so I can't offer you meaningful advice.

You could just define the class directly in the isolate:

```js
const ivm = require('isolated-vm');
const isolate = new ivm.Isolate({ memoryLimit: 128 });
const context = isolate.createContextSync();
context.global.setSync('global', context.global.derefInto());
isolate.compileScriptSync(`
(function() {
  class Log {
    debug(msg) {
      console.log(\`>>> \${msg}\`);
    }
  }
  global.Log = new Log;
})();
`).runSync(context);

const hostile = isolate.compileScriptSync('var x = 10;\ny = x + 1;\nLog.debug(`y = ${y}`)\n');
hostile.runSync(context);
```

It runs but it's not going to log anything because it invokes `console.log` inside the other isolate which isn't wired up to anything.
