### ISSUE TITLE
Error: /home/parallels/projects/node_modules/isolated-vm/native-example/build/Release/isolated-native-example.node: undefined symbol: _ZN3ivm8Executor16current_executorE

### ISSUE THREAD

**Issue by ron7777777** [laverdet/isolated-vm#144]
**node_modules/isolated-vm/native-example compiles but when you run: node usage.js to test it you get following error:**
######################################################################
node usage.js 
internal/modules/cjs/loader.js:1025
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /home/parallels/projects/node_modules/isolated-vm/native-example/build/Release/isolated-native-example.node: undefined symbol: _ZN3ivm8Executor16current_executorE
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1025:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/parallels/projects/node_modules/isolated-vm/native-example/usage.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
######################################################################

**Error originates from following line in usage.js file:**
require('.');

**ENVIRONMENT:**

installed/compiled "isolated-vm" and "isolated-vm/native-example" with "npm install" without errors. I have also tried removing "node_modules" and install fresh without success.

in "node_modules/isolated-vm" directory I ran "node tests.js" without error.

isolated-vm: 
isolated-vm@3.0.0

uname -a: 
Linux debian-gnu-linux-vm 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u3 (2018-08-19) x86_64 GNU/Linux
NOTE: Error also occurs with ubuntu 18.04.3

node -v:
v10.18.0   && v12.14.0
gcc -v:
gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) 

**BTW:** (This is a secondary issue I will file latter but just to give more info): In node_modules/isolated-vm directory I ran "node parallel-sort-example.js" and received following error:

######################################################################
Single-threaded took 629.918232ms
node: ../src/isolate/scheduler.cc:118: void ivm::Scheduler::Implementation::IncrementUvRef(): Assertion `Executor::IsDefaultThread()' failed.
Aborted
######################################################################

**Comment by laverdet** [comment]
The native module support was something requested by a user a long time ago and I'm pretty sure never saw any usage. Is there a native module you want to build under isolated-vm?

The parallel sort example is fixed in master now.

**Comment by ron7777777** [comment]
With nan addon I wish to launch a worker thread from main thread with an immediate detach but continue to be able to access the isolate and context. I wish to use serializer.WriteValue in worker thread which explains the need for both isolate and context to be available. 

To do this I was hoping to make a snapshot of the isolate in main thread and load it from memory in the worker thread to continue processing.

I would really like to self code this using v8 internals but compiling "v8.h" with "nan.h" in the addon code  generates conflict errors with the "nan.h" subset of V8 library. So this leaves two questions if you could be so kind?

**1)** _recommended way to compile "v8.h" together with "nan.h" without conflicts?_
**2)** _simplest way to to take an isolate snapshot and reload it for use later?_

**NOTE: Here are some incomplete snippets of code I have tried so far.**
**1)** I tried using a snippet of code from your isolated-vm repository but it unfortunately core dumps at **"snapshot_creator.CreateBlob"**.

v8::Isolate *isolate = v8::Isolate::Allocate();
v8::SnapshotCreator snapshot_creator{isolate};
v8::Isolate::Scope isolate_scope(isolate);
v8::HandleScope handle_scope(isolate);
v8::Local<v8::Context> context = v8::Context::New(isolate);
snapshot_creator.SetDefaultContext(context, {&SerializeInternalFieldsCallback, nullptr});
isolate->ContextDisposedNotification();
**snapshot = snapshot_creator.CreateBlob(v8::SnapshotCreator::FunctionCodeHandling::kKeep);**

**2)** core dumps at **"CreateSnapshotDataBlob(source1)"**
const char* source1 = "function f() { return 42; }";
**v8::StartupData data1 = v8::V8::CreateSnapshotDataBlob(source1);**
v8::Isolate::CreateParams params1;
params1.snapshot_blob = &data1;

**3)** If possible to get "nan.h" to compile with "v8.h" I would like to try using a class like the one listed below.
// TestIsolate is used for testing isolate serialization.
class TestIsolate : public v8::Isolate {
    public:
        static v8::Isolate* NewInitialized(bool enable_serializer) {
            i::Isolate* isolate = new TestIsolate(enable_serializer);
            v8::Isolate* v8_isolate = reinterpret_cast<v8::Isolate*>(isolate);
            v8::Isolate::Scope isolate_scope(v8_isolate);
            isolate->Init(NULL);
            return v8_isolate;
      }
  explicit TestIsolate(bool enable_serializer) : v8::Isolate(enable_serializer) {
    set_array_buffer_allocator(CcTest::array_buffer_allocator());
  }
}

v8::Isolate* isolate = TestIsolate::NewInitialized(true);

v8::Isolate::Scope isolate_scope(isolate);
 {
  v8::HandleScope scope(isolate);
  v8::Context::New(isolate);
 }
 Isolate* internal_isolate = reinterpret_cast<Isolate*>(isolate);
 internal_isolate->heap()->CollectAllAvailableGarbage("serialize");

**Comment by laverdet** [comment]
> 1) recommended way to compile "v8.h" together with "nan.h" without conflicts?

You must be misunderstanding something because nan.h [includes node.h](https://github.com/nodejs/nan/blob/60e86a9d4c4536fbbd2a76814470edd66b23114e/nan.h#L55) which in turn [includes v8.h](https://github.com/nodejs/node/blob/fe058188a158cea61656b6ecb4517abf4a679353/src/node.h#L63). Compiling v8.h "with" nan.h is not only possible, it is *essential*.

> 2) simplest way to to take an isolate snapshot and reload it for use later?

Snapshots are not what you think they are. Snapshots are meant to cache compiled code to make initialization faster. Snapshots are not a tool to serialize arbitrary state into a new isolate.

My sense here is that isolated-vm is not really what you are looking for. If your goal is to just create a worker thread that does something in C++ all the tools you need are in v8.h and \<thread\>.

**Comment by ron7777777** [comment]
Thank you for your quick reply. 

1) So you are saying there is a way for me to access i::/internal:: and v8::V8:: namespace by only including nan.h? I did not have success doing this ergo my question on how to include v8.h in an nan addon using nan.h? From what I know you can only access a subset of V8 by including nan.h?

2) worker thread launched with detach can not continue to work on isolate after the main thread exits. I wish to have access to a copy of the isolate that will not be locked or garbage collected after the main thread exits. Is there really no way to do this?

Thank you in advance...

**Comment by laverdet** [comment]
> So you are saying there is a way for me to access i::/internal:: and v8::V8:: namespace by only including nan.h? I did not have success doing this ergo my question on how to include v8.h in an nan addon using nan.h? From what I know you can only access a subset of V8 by including nan.h?

Most v8 internal symbols are not exported in the compiled nodejs binary so you generally can't access these in any addon. C++ doesn't have any portable way for some header to limit access to an API in a different header so I'm not really sure what you're running into. nan.h includes v8.h, so you have access to everything in v8.h if you include nan.h.

> worker thread launched with detach can not continue to work on isolate after the main thread exits. I wish to have access to a copy of the isolate that will not be locked or garbage collected after the main thread exits. Is there really no way to do this?

After the main thread exits the process is done. There isn't any way to just copy a running isolate. You can `fork()` the whole process if you want which kind of does what you're asking for but I'm concerned you're in over your head with whatever this is.

**Comment by ron7777777** [comment]
I was incorrectly referring to the function called using js binding/addon as main thread so I was not being clear. No fork would be needed. I appreciate your opinion but I will nevertheless continue the quest to serialize/deserialize or simply copy an isolate and use it again. 😏 Thank you for your assistance much appreciated! Love what you have done with isolated-vm btw!
