### ISSUE TITLE
How to run this in the most safest way possible?

### ISSUE THREAD

**Issue by ChampRay** [laverdet/isolated-vm#146]
I want to use this package to run a lot of untrusted user code and really need to ensure in the event that in a scenario that the package did miss something, the worst they could do is trivial. Is there any way easy way to run this in a even more restricted mode? like no read permissions, no write permissions, no execution commands.

**Comment by laverdet** [comment]
You could run in a Docker container which would provide a great deal of isolation from the rest of the system. For most users running the nodejs process under an account with limited permissions should be enough, and should also be standard for all web services-- trusted or not. If you are worried about sandboxes theoretically maybe reading data from other sandboxes using finicky cpu cache timing attacks (Spectre / Meltdown) you can run with the v8 flag `--untrusted-code-mitigations` as documented [here](https://v8.dev/docs/untrusted-code-mitigations). The nightmare scenario where an attacker roots your server through isolated-vm is unlikely. Your web browser is constantly running untrusted code from thousands of websites and does a pretty decent job of avoiding this situation.
