### ISSUE TITLE
All fields of `ScriptOrigin`, `ScriptRunOptions`, etc. are required in TypeScript

### ISSUE THREAD

**Issue by nsamsonau-pal** [laverdet/isolated-vm#148]
Since the types started using intersection, all sub-fields became required. For example, now running a script required either no options or **all** options provided:
`script.run(context, { timeout: 10000 })` would require the `release` field to be set as well, but `script.run(context)` would still work.
 
https://github.com/laverdet/isolated-vm/blob/bc28b77425cd48574ec8b30c1a4097cd34bbf67d/isolated-vm.d.ts#L535-L558

**Comment by SpencerSharkey** [comment]
I noticed this too when making the upgrade to 3.x, I opened #150 that should fix it moving forward
