### ISSUE TITLE
Creating a snapshot can crash the process with "Illegal instruction"

### ISSUE THREAD

**Issue by samkline** [laverdet/isolated-vm#151]
This line of code will crash the Node process, tested on Node 13.6.0 and 12.13.0:

```
require('isolated-vm').Isolate.createSnapshot([{code:`a=new Intl.DateTimeFormat()`}])
```

The act of snapshotting the DateTimeFormat is what breaks it. If you remove the `a=`, then the process does not crash.

The result looks like:

```
global handle not serialized: 0x103245053ef9 <Foreign>global handle not serialized: 0x103245053f09 <Foreign>global handle not serialized: 0x103245053f19 <Foreign>

#
# Fatal error in , line 0
# Check failed: handle_checker.CheckGlobalAndEternalHandles().
#
#
#
#FailureMessage Object: 0x7ffd38c65a90Illegal instruction (core dumped)
```
The issue comes from `SnapshotCreator::CreateBlob` in V8's [src/api/api.cc](https://github.com/v8/v8/blob/master/src/api/api.cc), which is called by isolated-vm's [src/module/isolate_handle.cc](https://github.com/laverdet/isolated-vm/blob/master/src/module/isolate_handle.cc).

I'm not sure whether this can be handled by isolated-vm, or if it needs to be fixed in V8.

**Comment by laverdet** [comment]
This is something that would be need to be added in v8. I suspect it's not something that would be a terribly high priority for them though.

You could reproduce the issue without isolated-vm via: `require('v8').serialize({ format: new Intl.DateTimeFormat() })` which would make explaining the feature request to the v8 team a lot easier. I believe if they add support there then it would carry over to snapshots, though I'm not 100% sure.

I wish I could make this error message better but the snapshot API has my hands tied.

**Comment by samkline** [comment]
I expected as much, thanks for confirming and for the explanation that it's related to V8's serialization. I may go file an issue with the V8 team but it's also easy for me to work around.

Since there's nothing actionable for isolated-vm here, I'll close this issue.
