### ISSUE TITLE
Getting a stack trace from an unhandled promise rejection

### ISSUE THREAD

**Issue by mikolalysenko** [laverdet/isolated-vm#155]
I can get the stack trace for synchronous user code executing in isolated-vm by wrapping such code in a `try...catch`, serializing any caught errors, and sending them back to the main process.  However if there are promises spawned by the user code then I can't necessarily catch any unhandled rejections within the isolate if they occur in a microtask.  These errors get caught and bubble up into the external context, where they are rethrown and then caught at the point where they are initially called.

It's nice that I can catch these errors at all, however because they are rethrown in the main process they lose the stack trace from the isolate.  This sucks because I would like to report the isolate stack trace for debugging code using promises more effectively.

Is there a way to get the stack trace from a thrown exception within an isolate?  I think the only way to solve this problem is to add some extra API.  Some ideas:

* Maybe the isolate stack could be included in the exception as a property (error.stack for normal stack and `error.isolateStack` for the isolate stack)
* Perhaps the isolate could implement something like `process.on('uncaughtException')` or `window.onerror` to handle these errors

**Comment by laverdet** [comment]
> I can get the stack trace for synchronous user code executing in isolated-vm by wrapping such code in a try...catch, serializing any caught errors, and sending them back to the main process. 

The try/catch actually shouldn't be necessary because isolated-vm copies the stack trace out automatically and combines it with the stack trace from the outer isolate:

```js
"use strict";
const ivm = require('isolated-vm');
const isolate = new ivm.Isolate;
const context = isolate.createContextSync();
context.evalSync(`
function foo() {
	throw new Error("hello");
}
foo();`, { filename: 'user-code.js' });
```

Logs:
```
ex.js:5
context.evalSync(`
        ^

Error: hello
    at foo (user-code.js:3:8)
    at user-code.js:5:1
    at (<isolated-vm boundary>)
    at ex.js:5:9
```

Errors thrown from microtasks (promise handlers) should have stack traces as well, but don't due to a bug. The bug should be fixed in the commit I just pushed if you want to give it a try.

**Comment by mikolalysenko** [comment]
Awesome!
