### ISSUE TITLE
Installation on mac OS fails

### ISSUE THREAD

**Issue by antouhou** [laverdet/isolated-vm#158]
When installing on mac OS installation fails with the following node-gyp error:

```
File "/Users/anton/.nvm/versions/node/v12.14.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2285, in SetUpConfigurations
    for configuration in target_dict['configurations'].keys():
RuntimeError: dictionary changed size during iteration
```

node v12.14.0
npm 6.13.6
node-gyp v5.0.5
mac OS 10.14.5
clang-1001.0.46.4
GNU Make 3.81
Python 3.7.6

I'm not sure what the issue is. XCode tells me that it's the latest versions of compile available

**Comment by laverdet** [comment]
You have to build with python 2.7.

**Comment by antouhou** [comment]
@laverdet Thank you for the response! Just discovered that it doesn't work with python 3 too. If someone else will come across the same issue, here it is: https://github.com/nodejs/node-gyp/issues/1998. Thank you very much for the response!

**Comment by laverdet** [comment]
I also found that the gyp feature that I was using which triggered this bug is not actually needed. I can just drop the line and it's not a problem, so the next version on npm should work with python 3
