### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by rs** [laverdet/isolated-vm#16]
Would it be possible to get user/system and internal/external CPU usage for code ran into an isolate?

**Comment by laverdet** [comment]
I don't think this is something I'll get around to implementing for the following reasons:
- Requires a pretty significant amount of platform-dependent code and testing
- Requires extra bookkeeping for a feature that won't be used by many
- The situation gets complicated when isolate calls are nested
- You can track wall time manually with Date.now() which is pretty good in most situations

**Comment by rs** [comment]
Fair enough.
