### ISSUE TITLE
Would an isolated-vm be good for server-side rendering of React

### ISSUE THREAD

**Issue by justin808** [laverdet/isolated-vm#160]
I'm the maintainer and primary author of [React on Rails](https://github.com/shakacode/react_on_rails).

I'm looking into improving the Node rendering of React.

This involves loading a very large "bundle" of JavaScript that defines the rendering functions.

# Goals
1. **Safety between requests**: Currently, the reuse of the vm context allows global leakage between server rendering requests. **We prefer that leakage be impossible.**
2.  **Speed**. If we give up speed for safety, the decreased speed must be nearly as fast as (unsafely) using the original, pooled context.
3. **Access to Node Externals**: Allow access to node externals, such as "require," which would enable the ability to make http requests from the running code.

Any thoughts, @laverdet?

Thanks in advance.

**Comment by laverdet** [comment]
I think the builtin nodejs `vm` module is what you're looking for.

**Comment by justin808** [comment]
@laverdet we've been using that successfully. The only thing that maybe the "isolate" could give us is a super-fast way to restore a fresh state of the loaded bundle so that the previous rendering request doesn't impact any nefarious globals.

**Comment by laverdet** [comment]
I don't think it'll be any faster. I recommend compiling your bundle once with vm.compileScript so you can reuse the compiled code in newly created contexts. That should be about the same speed or faster than isolated-vm's snapshot feature.
