### ISSUE TITLE
isolated-vm.d.ts -> Context.evalxxxxx is out of date

### ISSUE THREAD

**Issue by gm3000** [laverdet/isolated-vm#161]
evalClosure(code: string, options?: ContextEvalClosureOptions): Promise<ContextEvalResult>
according to doc and my test, the second argument is missing
should it have 3 arguments?
arguments *[array]` - Arguments to pass to this code

**Comment by laverdet** [comment]
Thanks, I've updated the types. I made some other significant changes to the definition too so let me know if you run into anything else.

**Comment by gm3000** [comment]
Hi, thx for the fix, I`ve commented new issue, pls refer to
https://github.com/laverdet/isolated-vm/commit/e5dbf97819b761851331108358555c3df15b3e18#r37226361
 
(type parameter) Options in type ArgumentsTypeBidirectional<Options extends import("isolated-vm").TransferOptionsBidirectional>
Type 'Options["arguments"]' does not satisfy the constraint 'TransferOptions'.
  Type 'TransferOptions | undefined' is not assignable to type 'TransferOptions'.
    Type 'undefined' is not assignable to type 'TransferOptions'.ts(2344)

Not sure if it is by different ts version.

**Comment by laverdet** [comment]
@gm3000 the issue you brought up has been fixed in v3.1.5. I didn't have strict mode enabled on this project.

**Comment by gm3000** [comment]
thx for the tip, great project, BYW
