### ISSUE TITLE
URIError object does not cross isolate boundary as itself but as Error object when thrown

### ISSUE THREAD

**Issue by fokushi** [laverdet/isolated-vm#163]
The specific case I was testing was to throw from the default isolate to an isolate created by isolated-vm.  While other standard error types (Error, RangeError, ReferenceError, SyntaxError, TypeError) will cross the isolate boundary as themselves, URIError will cross as Error.

Update: Passing a URIError object as an argument or return value works fine.  It only fails when throwing.  The opposite direction (isolate throwing URIError object to default isolate) has the same behavior.

**Comment by laverdet** [comment]
v8 only exposes the 5 errors you mentioned to embedders: https://github.com/v8/v8/blob/1ed469833165cd1a6801e56a2d1ec956a5af4b21/include/v8.h#L7137-L7143

I don't think I can add support for URIError in a reasonable way, and I think that even the current behavior of trying to discriminate between those 5 errors was a minor mistake.
