### ISSUE TITLE
Suggested Way to Decode Base64 in a script

### ISSUE THREAD

**Issue by jbis9051** [laverdet/isolated-vm#165]
Both `atob` and `Buffer` are  not defined.

**Comment by laverdet** [comment]
`atob` is specified in the HTML standard (not JS) and `Buffer` is an implementation detail of nodejs (not defined in any standard). `isolated-vm` is a **pure-JS** environment so you'll have to do this with a library. Perhaps: https://github.com/davidchambers/Base64.js/

**Comment by jbis9051** [comment]
@laverdet Sure. I understand and agree with the reasons those aren't provided. I was just wondering what the recommenced way (even using that lib) to do it.

**Comment by laverdet** [comment]
Give the documentation a read over and play with the module a bit and it should become clear how to accomplish this.

**Comment by jbis9051** [comment]
@laverdet  I've taken a look at the documentation and attempted the following:


```js
// setup script
jail.setSync('_atob', new ivm.Reference(function (string) {
       return Buffer.from(string, 'base64').toString()
}));
```


```js
// jailed script
let atob = _atob;

global.atob = function (...args) {
        return atob.apply(undefined, args, {result: {copy: true}});
};

global.atob(base64EncodedString);
```


This issue seems to be `global.atob()` doesn't return anything.

**Comment by laverdet** [comment]
In this case you can just take the contents of this file: https://github.com/davidchambers/Base64.js/blob/master/base64.js and then run it via `context.evalSync(<that code>)`. Then those functions will be available in the context.
