### ISSUE TITLE
Using Axios within isolate-vm

### ISSUE THREAD

**Issue by RyanElfman** [laverdet/isolated-vm#166]
I'm trying to allow user to use Axios within their scripts with the following code which half works:

```
const axios = require('axios');
const ivm = require('isolated-vm');
const isolate = new ivm.Isolate({ memoryLimit: 128 });
const context = isolate.createContextSync();

class Logger {
    static methods = [this.log];

    static log(obj) {
        console.log("log called:");
        console.log(obj.deref());
    }
}

class AxiosWrapper {
    static methods = [this.get];

    static async get(...args) {
        return axios.get.apply(this, args);
    }
}

// Logger.
context.evalClosure(`
    (function() {
        log = function(obj) {
            $0.applyIgnored(undefined, [obj],  { arguments: { copy: true } });
        };
    })();
`, Logger.methods, { arguments: { reference: true } });

// Axios.
context.evalClosure(`
    (function() {
        axios = {
            get: function (...args) {
                return $0.apply(undefined, args, { arguments: { copy: true }, result: { promise: true } });
            }
        };
    })();    
`, AxiosWrapper.methods, { arguments: { reference: true } });

async function compileUserScript() {
    var script = await isolate.compileScript(`
        (function() {
            doStuff = async function(obj) {
                var r = await axios.get('https://jsonplaceholder.typicode.com/posts');                
                log(r);
            };
        })();
    `)

    await script.run(context);    
}

async function doStuff (obj) {
    await compileUserScript();
    await context.evalClosure('doStuff($0);', [obj]);
}
doStuff("test");
```
I get back the JSON result inside of the Logger.log function but I have to deref() it. I want the user script to be able to use the objects, properties, functions, etc. that was returned from the promise, like so:

```
doStuff = async function(obj) {
    var r = await axios.get('https://jsonplaceholder.typicode.com/posts');      
    var firstUserId = r[0].userId;
    log(firstUserId);
};
```

**Comment by laverdet** [comment]
The Axios get function should probably be this:
```js
return $0.apply(undefined, args, { arguments: { copy: true }, result: { promise: true, copy: true } });
```

I added `{copy:true}` to the return result which performs [structured clone algorithm](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm) to move the results. I've never used Axios in depth before, but if the returned object has more methods then you'll need to do a lot more legwork to get it working.

Also you don't need the IIFE's in those `evalClosure` invocations, a local scope is provided automatically.

**Comment by RyanElfman** [comment]
Thanks. I did try that without luck but I figured out what was going wrong based on what you said. 

Axios was returning a bunch of stuff including methods. I had to use the .data property to get the results and then everything worked. 

I don't know if isolate-vm is good enough for my use case since I want to be able to use nodejs packages. I might have to use vm2 even though it seems they have vulnerabilities...

**Comment by bayati-code** [comment]
So I tried your code and adjusted the url but I am not finding a way to return the value with express

`app.post("/test_vm", async (req, res) => {
  try {
    let payload = {};
    const axios = require("axios");
    const ivm = require("isolated-vm");
    const isolate = new ivm.Isolate({ memoryLimit: 128 });
    const context = isolate.createContextSync();

    class Logger {
      static methods = [this.log];

      static log(obj) {
        console.log("log called:");
        console.log(obj.deref());
      }
    }

    class AxiosWrapper {
      static methods = [this.get];

      static async get(...args) {
        return axios.get.apply(this, args);
      }
    }

    // Logger.
    context.evalClosure(
      `
        (function() {
            log = function(obj) {
                $0.applyIgnored(undefined, [obj],  { arguments: { copy: true } });
            };
        })();
    `,
      Logger.methods,
      { arguments: { reference: true } }
    );

    // Axios.
    context.evalClosure(
      `
        (function() {
            axios = {
                get: function (...args) {
                    return $0.apply(undefined, args, { arguments: { copy: true }, result: { promise: true } });
                }
            };
        })();    
    `,
      AxiosWrapper.methods,
      { arguments: { reference: true } }
    );

    async function compileUserScript() {
      var script = await isolate.compileScript(`
            (function() {
                doStuff = async function(obj) {
                    var r = await axios.get('https://jsonplaceholder.typicode.com/posts');                
                    log(r);
                };
            })();
        `);

      return await script.run(context);
    }

    async function doStuff(obj) {
      await compileUserScript();
      await context.evalClosure("doStuff($0);", [obj]);
    }
    await doStuff("");
    // Send the processed data as the response
    res.json(payload);
  } catch (error) {
    console.error("Error:", error);
    res.status(500).send("An error occurred");
  }
});`
