### ISSUE TITLE
While loop ignores timeout

### ISSUE THREAD

**Issue by Attacler** [laverdet/isolated-vm#169]
Hi there,

When i put in a while(1){ somedeclaredfunction } the timeout seems to be ignored.

        const logCallback = function(...args) {
            console.log(...args);
        };
        
        context.evalClosureSync('global.log = function(...args) {
            $0.applyIgnored(undefined, args, { arguments: { copy: true } });
        }', [ logCallback ], { arguments: { reference :true} });

        const execute = isolate.compileScriptSync("log('start');while(1){log('test');}");
        const output = execute.run(context, {
            timeout: 1000,
        }).catch(err => console.error(err)).then(data => console.log(data));

Sometimes the timeout error occures way later (like 1 minute later), how can i fix this?

Greetings,
Bart

**Comment by laverdet** [comment]
It looks like you're just overloading stdout with too much logging. If you replace the inner script with `"log('start');while(1){log(`test: ${new Date}`);}"` you can see that the isolate in fact only lives for 1 second even though the logs it sent out take a while to flush. Also if I remove the `console.log` and make `logCallback` a no-op the program terminates after 1 second.
