### ISSUE TITLE
segfault: both examples doesn't work on my end

### ISSUE THREAD

**Issue by tunnckoCore** [laverdet/isolated-vm#173]
Hi there. This looks awesome and like it will help me a lot. 

The thing is that both examples fail with `segfault (core dump)`.

- archlinux, gcc, make, base-devel, not sure for the python version which is used
- node 12.14, npm 6.14, yarn 1.22

```
extra/python2 2.7.17-1 (11.8 MiB 75.4 MiB) (Installed)
    A high-level scripting language
extra/python2-backports.functools_lru_cache 1.6.1-1 (8.9 KiB 23.4 KiB) (Installed: 1.5-1)
    Backport of functools.lru_cache from Python 3.3
extra/python2-backports 1.0-2 (2.5 KiB 1.0 KiB) (Installed)
extra/boost-libs 1.72.0-1 (2.6 MiB 10.5 MiB) (Installed)
    Free peer-reviewed portable C++ source libraries - runtime libraries
extra/python-dbus-common 1.2.16-1 (4.6 MiB 8.5 MiB) (Installed: 1.2.14-1)
    Common dbus-python files shared between python-dbus and python2-dbus
extra/python-dbus 1.2.16-1 (103.8 KiB 543.2 KiB) (Installed: 1.2.14-1)
    Python bindings for DBUS
extra/python2 2.7.17-1 (11.8 MiB 75.4 MiB) (Installed)
    A high-level scripting language
```

**Comment by laverdet** [comment]
This isn't the experience other users are having, such a hard failure is not normal. I just spun up an Arch Linux instance on Scaleway and installed `isolated-vm` successfully and all tests passed. You'll have to dig deeper and give me more information to go on here.

**Comment by tunnckoCore** [comment]
> to dig deeper

Ok. Ideas? Things to check more? From where to start?

Oh I thought to include it and forgot:
- 8gb ECC RAM, half or more are almost constantly free
- Xeon x3440, 4 cores 8 threads
- Kernel 4.19.99-1-lts

I was thinking to re-install the OS (or even migrate strongly to other distro after 5 years on pure hardcore Arch) and start clean again (this install is ~3y old), for quite some time now... it's getting more and more problems and there's ton of bloat, so I'm not that surprised.

**Comment by tunnckoCore** [comment]
Oookay, it started working on `node v13.10.1 (npm v6.13.7)`

and after system restart and rebuild.

Cool. Didn't restarted it for a month, haha.
