### ISSUE TITLE
Typescript definition is wrong for InspectorSession

### ISSUE THREAD

**Issue by reivax0z** [laverdet/isolated-vm#180]
Hi,

Following the use of the **inspector** in our implementation of isolated-vm, we've realised that if we follow the depicted Typescript definition of:

```
export type InspectorSession = {
	dispatchProtocolMessage(message: string): void;
	dispose(): void;
	onNotification: (callId: number, message: string) => void;
	onResponse: (message: string) => void;
};
``` 

Then the devtool cannot properly receive the messages.

The Typescript definition should be:
```
export type InspectorSession = {
	dispatchProtocolMessage(message: string): void;
	dispose(): void;
	onNotification: (message: string) => void;
	onResponse: (callId: number, message: string) => void;
};
``` 

Note the difference where the `onResponse` includes both the `callId` and the `message`.

This is also highlighted in the current official docs (`js` example of the inspector):
```
channel.onResponse = (callId, message) => send(message);
channel.onNotification = send;
```

Thanks!

**Comment by laverdet** [comment]
Thanks for the report. This is fixed in master and will be updated next time I cut a new npm version.

**Comment by reivax0z** [comment]
Awesome! Thanks for the quick fix :)
