### ISSUE TITLE
Passing some new v8 process 

### ISSUE THREAD

**Issue by tyvdh** [laverdet/isolated-vm#181]
Forgive me if this is an ignorant question but I’m trying to run some code which uses the detect-node library which checks for a process global class. If it’s not present the module defaults to a browser mode. Is there any way I can pass in a process to this package?

**Comment by laverdet** [comment]
`detect-node` is one-line module: https://github.com/iliakan/detect-node/blob/master/index.js

You could trick it just by doing this: `context.global.set('process', '[object process]')`

**Comment by laverdet** [comment]
Actually I guess you would have to do: `context.global.eval('globalThis.process = { [Symbol.toStringTag]: "process" }')`

**Comment by tyvdh** [comment]
Holy. I knew it had to be something simple. Thank you!
