### ISSUE TITLE
Stop the function from executing

### ISSUE THREAD

**Issue by Attacler** [laverdet/isolated-vm#182]
Hi there,

Is there a way to stop the code from executing?
I tried to use throw but they dont work inside a promise.

Greetings,
Attacler/Bart

**Comment by laverdet** [comment]
I'm not really sure what you're asking.

**Comment by cemremengu** [comment]
I think he wants to cancel a long running function like this https://github.com/robertkrimen/otto#halting-problem

**Comment by laverdet** [comment]
The only way to interrupt a script semi-gracefully is by selecting a `timeout` ahead of time. Calling `isolate.dispose()` will also interrupt any script that's running but of course it disposes the isolate while it's at it.

**Comment by Attacler** [comment]
Thank you!
