### ISSUE TITLE
async result is a Reference {}

### ISSUE THREAD

**Issue by cemremengu** [laverdet/isolated-vm#183]
The script below keeps printing `Reference {}` for some reason instead of the value. `getRedisObject` is an async function that returns a json result. What can be the problem?

```
const ivm = require('isolated-vm');
const fn = require('./fn');

const isolate = new ivm.Isolate({ memoryLimit: 512 });

const context = isolate.createContextSync();

const { global } = context;
global.setSync('global', global.derefInto());

const logCallback = function (...args) {
  console.log(...args);
};
context.evalClosureSync(
  `global.log = function(...args) {
  $0.applyIgnored(undefined, args, { arguments: { copy: true } });
}`,
  [logCallback],
  { arguments: { reference: true } },
);

context.evalClosureSync(
  `global.getRedisObject = (...args) => { 
    return $0.applySync(undefined, args, { arguments: { copy: true }, result: { promise: true } });
  }`,
  [fn.getRedisObject],
  { arguments: { reference: true } },
);
const promisify = (code) => `(async () => {
  ${code}
})()`;

isolate
  .compileScriptSync(promisify(`log(await getRedisObject('musty'))`))
  .runSync(context);
```

getRedisObject
```
module.exports = async (key) => {
  try {
    return unflatten(await redis.hgetall(key)) ?? {};
  } catch (err) {
    logger.error('getRedisObject failed %s', err);
  }
  return {};
};
```

**Comment by laverdet** [comment]
You probably want `result: { promise: true, copy: true }` on the call to `applySync`.

**Comment by cemremengu** [comment]
Thank you!

**Comment by cemremengu** [comment]
Sorry this is not related but didnt want to create it as an issue;
We are building a system that will execute some async js code based on an incoming alarm (500 per second). What is the best way to approach this for best performance (to handle this workload) in terms of isolates and contexts? For example I am now trying 1 isolate and many contexts. I can do a resource pool for contexts maybe but I would like to know what is more expensive to create.

Previously we used vm2 but failed badly. I would appreciate if you could share your opinions and thanks for making this fantastic work available!

**Comment by laverdet** [comment]
It really depends on what you're building. I would recommend starting with a pool containing a number of isolates about equal to the number of physical cores on your server. Creating and disposing isolates isn't free so if you can avoid it you should. If the code you want to run changes infrequently you should look into the snapshot feature which makes spinning up new isolates and contexts cheaper which could be valuable.
