### ISSUE TITLE
memoryLimit is ignored when using `Array.fill`

### ISSUE THREAD

**Issue by y21** [laverdet/isolated-vm#186]
Hello,
I've tried using the example code that's listen on the README which is supposed to dispose the isolate once the memory limit is "reached" and modified it a bit to use `Array.fill`.
> A determined attacker could use 2-3 times this limit before their script is terminated.

I am aware that it can take up more than what was specified, but it seems to take up gigabytes of memory instead of only a few megabytes.
```js
const ivm = require('isolated-vm');
const isolate = new ivm.Isolate({ memoryLimit: 8 });
const context = isolate.createContextSync();

// Let's see what happens when we try to blow the isolate's memory
const hostile = isolate.compileScriptSync(`
	void (new Array(1024 * 1024 * 60).fill());
`);

hostile.run(context).then(console.log, console.error);
```
![image](https://user-images.githubusercontent.com/30553356/83758842-fb405000-a672-11ea-8881-555657392764.png)
Memory usage after a few seconds: 0.5 GB => 3.08 GB

It doesn't copy the result or anything like that, so I'm unsure of what's going on. Clearly 3 GB is way more than 3x 8 MB.

Node.js: v13.12.0
isolated-vm: v3.3.3
v8: 7.9.317.25-node.30

**Comment by y21** [comment]
Ah, looks like it's been reported before (#107)
Really hacky but simply overwriting `Array.prototype.fill` with MDN's polyfill and adding a length check before seems to fix it.

**Comment by laverdet** [comment]
@y21 is the length check actually needed? Simply implementing the function in JS should be enough. The issue is that v8's optimized/assembly `fill` implementation is uninterruptible, but any pure-JS algorithm should be interruptible.

**Comment by y21** [comment]
Right, the length check isn't actually needed. It seems to dispose the isolate even without it after reaching ~200 MB memory usage, which is still way more than what was specified (8 MB) but I guess that's to be expected as it's not a strict limit.
I might keep the length check to prevent this from happening, but there would still be some other ways an attacker could go way above the memory limit, e.g. `'.'.repeat(1e9);`, so I'm not sure if it's worth overwriting all these prototype functions with polyfills and a strict length check...

**Comment by laverdet** [comment]
Limits under about 128mb seem to be pretty hit or miss.

I wouldn't recommending putting in a length check because there's nothing stopping the user from using their own `fill` function that doesn't have the length check.

**Comment by y21** [comment]
Oh you're right, the length check doesn't really make sense. I clearly didn't think that through... 😅
Back to the issue with `fill` being uninterruptible: wouldn't it make sense to (temporarily) have some sort of "warning" in the README that mentions this problem, so developers are aware of this and can overwrite this function with Mozilla's polyfill until this is sorted out?

**Comment by laverdet** [comment]
I think more documentation might make sense. My hope was that the v8 team would be able to take care of the issue but it seems to be tricky to fix and also not a priority for them.
