### ISSUE TITLE
Example for retrieving value from function execution within isolate

### ISSUE THREAD

**Issue by space55** [laverdet/isolated-vm#187]
Hi,

I've been reading the docs and trying to figure this out for a couple days, but I can't for the life of me understand it. Essentially, the goal I'm trying to accomplish is to allow a user to supply JavaScript code that will perform a task based on an input I provide, and then retrieve the output that the user's code generates.

Sample:

`main.js`
```javascript
const ivm = require('isolated-vm');

const http = require('http');
const https = require('https');
const jsdom = require('jsdom');
const axios = require('axios');

const isolate = new ivm.Isolate({
  memoryLimit: 128
});
const context = isolate.createContextSync();
context.global.setIgnored('jsdom', jsdom, {
  reference: true
});
context.global.setIgnored('http', http, {
  reference: true
});
context.global.setIgnored('https', https, {
  reference: true
});
context.global.setIgnored('axios', axios, {
  reference: true
});

const jail = context.global;
jail.setSync('global', jail.derefInto());
const logCallback = function (...args) {
  console.log(...args);
};

context.evalClosureSync(`global.log = function(...args) {
	$0.applyIgnored(undefined, args, { arguments: { copy: true } });
}`, [logCallback], {
  arguments: {
    reference: true
  }
});

async function exec_sandboxed_req(code, inputValue, callback) {
  const script = isolate.compileScriptSync(code);
  await script.run(context);
  const fnReference = await context.global.get('getResult');

  const res = await fnReference.apply(undefined, [inputValue], {
    timeout: 3000,
    resolve: true,
    reference: {
      copy: true
    }
  });

  console.log(res);

  callback(res);
}
```

`user-code.js`
```javascript

async function doStuff(inputValue) {
    // Does stuff
    return outputValue;
}

async function getResult(inputValue) {
    return await doStuff(inputValue);
}
```

What would be the rough process to pull this off? I feel like I'm close, as I've been able to get user-supplied code to execute, but it always runs out of order. In addition, I'm also having issues catching exceptions. I've tried putting a catch _everywhere_, but I still can't see any exceptions.

On a separate note, is there any way for me to pass a callback to the code, which would get me my result? Something like `setResult` in [v8-sandbox](https://github.com/fulcrumapp/v8-sandbox)

Thanks in advance!

**Comment by laverdet** [comment]
I think you have a misunderstanding of the separation model used in isolated-vm. The `jsdom` (and other) references you've created live in the nodejs isolate and cannot be accessed plainly in the isolated isolate. These objects might as well exist on another computer. It actually may be easier to imagine the separation model as literally a different computer. How would your nodejs server directly call a DOM function in the user's browser? You would need to write some kind of RPC for that.

**Comment by space55** [comment]
It's completely possible I misunderstand the separation. The current code I'm using is designed to make a request, parse the HTML, and then return a result. Essentially, I will be passing the URL into the isolated system, and be receiving a text value out of the isolated system. Hence why I'm asking to pass in a string value, and retrieve a string value out.

**Comment by laverdet** [comment]
In nodejs you use `require('http')` to make an http request. In the browser you use `fetch` or `XMLHttpRequest` (or others). `isolated-vm` is neither of those platforms. If you want to make an http request from the isolate you will need to proxy the request back into nodejs. If you want make that request through axios you will have to modify axios in some way to make that happen.

**Comment by space55** [comment]
Ah, I understand. Let me ask about the last part, then - is there some way to pull off passing a value into a function, and getting the return value from the isolate? I assume I'm misunderstanding that as well, I've been staying up way too late working on similar things

**Comment by space55** [comment]
As it turns out, I _was_ misunderstanding, and my code pretty much worked. The important bit was:

```javascript
  const script = isolate.compileScriptSync(code);
  await script.run(context)
  const fnReference = await context.global.get('getATIS');

  const res = await fnReference.apply(undefined, [icao], {
    timeout: 3000,
    reference: {
      copy: true
    }
  });
  console.log(res);
```

Now to figure out how to auto-resolve promises...
