### ISSUE TITLE
Incorrect type definitions for apply*

### ISSUE THREAD

**Issue by misiek08** [laverdet/isolated-vm#189]
Hello!
I think there was mistake made in https://github.com/laverdet/isolated-vm/commit/bc7c1c5592b26dee8a0a6d19727b489709b02ea7, because I think now it's impossible to pass array of simple (string, int) arguments to those callbacks.
Am I missing something, or those `[]` removed are really missing in types?

```js
error TS2345: Argument of type '[string]' is not assignable to parameter of type '[]'.

82         cb.applyIgnored(null, ["example string"])
```

**Comment by laverdet** [comment]
You haven't included the declaration for `cb` so it's difficult for me to help you.

Probably what you are seeing is the `apply` family of functions now checks the arguments of the referenced function:
```ts
declare const fn1: ivm.Reference<() => {}>;
fn1.apply(undefined, [ 'hello' ]); // error

declare const fn2: ivm.Reference<(arg: string) => {}>;
fn2.apply(undefined, [ 'hello' ]); // not an error
```

There's an issue with `this` parameters that I need to update but it doesn't look like that's what you're seeing.

**Comment by misiek08** [comment]
Thanks, it was problem with `cb` declaration like you said! The source code of library I mention was deleted this night, so I can't link to this code part no more.
Source was at https://github.com/superfly/fly and it was removed by push force ~10 hours ago.

**Comment by benaubin** [comment]
@laverdet I'm having an issue where the type declarations won't allow  `Copy<ArrayBuffer>` to be passed as an argument to apply()

**Comment by laverdet** [comment]
@benaubin thanks, those cases weren't handled in the `apply` signature. I pushed a commit which adds support for that in the types. Unfortunately I don't have any TS testing set up for this project right now so coverage is pretty spotty.
