### ISSUE TITLE
cannot catch exception thrown after host call

### ISSUE THREAD

**Issue by ITeMbi** [laverdet/isolated-vm#191]
Hello,
I am trying to catch an exception thrown after a call to the host. For some reason, my `try/catch` block can't catch the exception thrown and instead, I see an unhandled promise rejection.<br/>
Code:
```js
const { Isolate } = require('isolated-vm');
const isolate = new Isolate({
    memoryLimit: 32
});

(async () => {
    const ctx = await isolate.createContext();
    await ctx.global.set('global', ctx.global.derefInto());

    try {
        await ctx.evalClosure(`
        global.t = async () => {
            const res = await $0.apply(undefined, [], { result: { promise: true } });
            throw new Error('test');
        };
        `, [
            async function() {
                console.log('function called');
                return new Promise(r => setTimeout(r, 1000, 'something'));
            }
        ], {
            arguments: {
                reference: true
            }
        });
    } catch (e) {
        console.log('caught exception from evalClosure', e.message);
    }


    try {
        await ctx.eval('t();', {
            promise: true
        });
    } catch (e) {
        console.log('caught exception from eval', e.message)
    }
})();
```

What I'm trying to do is inject some code using `evalClosure` (create a global function which executes a function on the host and stores the result in a variable `res`, do some error checking and maybe throw an exception inside of the isolate if something went wrong) and call the injected function in a separate `eval` call. I'd expect that the try catch block would catch the error and would log a message to the console ('caught exception from eval'), but it doesn't.<br/>
Maybe I'm misunderstanding something here? Can I not catch unhandled promise rejections outside of the isolate? I guess it can be caught using `t().catch(() => { /* ... */ });`, but the code passed to `ctx.eval` is unknown so that's not an option.

The try/catch block works fine if the exception is thrown **before** the host call was made:
```js
await ctx.evalClosure(`
global.t = async () => {
    throw new Error('test');
    const res = await $0.apply(undefined, [], { result: { promise: true } });
};`, /* ... */);
```
This logs `caught exception from eval test`

**Comment by laverdet** [comment]
You also need to wait on the proxied promise. The second try/catch block should be this:

```js
const result = await ctx.eval('t();', {
  promise: true
});
await result.result;
```

I think this behavior is pretty confusing and it even took me a little while to figure out what was going wrong since I haven't messed with these features in a few months. I'm going to leave this issue open as a reminder to revisit the API when possible.

**Comment by laverdet** [comment]
`result` will be removed in v4.x
