### ISSUE TITLE
Poor performance when using promise results

### ISSUE THREAD

**Issue by benrazon** [laverdet/isolated-vm#193]
From the default node process, I used to get a reference to an async function in my other isolate and then calling
apply with  {result: {promise: true}} so that I could easily await the function result. This was working great on my mac, but when running in aws lambda, I found that awaiting the result would take 6-8 seconds instead of less than 100 milliseconds. I'm pretty sure I'm using the same version of isolated-vm and node, but they aren't the exact same files because of different operating systems. Switching the async function to a sync version solved the performance issue and was straightforward. I simply switched to using the sync versions of the isolated-vm api instead of the async ones. I haven't looked into this further yet, but wanted to post in case you had any ideas.

**Comment by laverdet** [comment]
That's pretty surprising behavior. The async versions use a thread pool so if Lambda has some interesting behavior with threads then I guess that might cause a performance problem. 6 seconds is unreasonable though.
