### ISSUE TITLE
Call a callback function passed from an isolate from the main isolate in the isolate context.

### ISSUE THREAD

**Issue by tom-acceleratecompliance** [laverdet/isolated-vm#194]
Apologies for the confusing issue name, hopefully this makes sense:

This is what my user provided code looks like:

```javascript
foo(function(result) {
  bar(result)
})
```

Both foo and bar have been defined like so:

```javascript
context.evalClosureSync(`global.foo = function(...args) {
  return $0.applySyncPromise(undefined, args, { arguments: { copy: true } });
}`, [fooCallback], { arguments: { reference: true }, result: { copy: true } });
```

Then, inside fooCallback,
```javascript
function foo(callback) {
    return new Promise(function (resolve) {
      // Some async work...
      callback(i) // Called many times
      resolve()
    })
}
```

This works, and if 'result' is logged in the user script, we can see `i` being passed back. However, this function is being executed in the main isolate, I know this as calling bar fails with the error: `Error: This function may not be called from the default thread` - due to it being a `applySyncPromise`.

Is it possible to pass a callback to a function, call that callback from non-user code while maintaining the isolate?

Thanks for your help

**Comment by tom-acceleratecompliance** [comment]
Hi @laverdet - I've create an app that reproduced my problem, hopefully it makes more sense:

```javascript
import ivm from 'isolated-vm'

let isolate = new ivm.Isolate();
let context = isolate.createContextSync();
let jail = context.global;
jail.setSync('global', jail.derefInto());

function log(...args) {
  console.log(...args)
}

function findRows(callback) {
  return new Promise(function(resolve) {

    // In actual all these rows are fetched async
    let rows = [
      { label: 'A', value: 'a' },
      { label: 'B', value: 'b' }
    ]
    rows.forEach(function(row) {
      callback.applySync(undefined, [row], {
        arguments: { copy: true }
      })
    })
    resolve()
  })
}

context.evalClosureSync(`global.log = function(...args) {
  $0.applyIgnored(undefined, args, { arguments: { copy: true } });
}`, [log], { arguments: { reference: true } });

context.evalClosureSync(`global.findRows = function(...args) {
  return $0.applySyncPromise(undefined, args, { arguments: { reference: true } });
}`, [findRows], { arguments: { reference: true }, result: { copy: true } });


// This works, but the callback function code seems to be in the main isolate. 
context.eval(`
  findRows(function(row) {
    log(row)
  })
`)

function processRow(row) {
  return new Promise(function (resolve) {
    // Do the async work to process the row
    resolve()
  })
}

context.evalClosureSync(`global.processRow = function(...args) {
  return $0.applySyncPromise(undefined, args, { arguments: { reference: true } });
}`, [processRow], { arguments: { reference: true }, result: { copy: true } });


context.eval(`
  findRows(function(row) {
    // This break as processRow cannot be run from the main thread.
    // How do I get this to be executed in the isolate thread?
    processRow(row)
  })
`)
```

I effectively need a way to be able to pass a callback from the user-defined code, then execute (and pass arguments to), that callback.

The reason I'm looking for this behaviour is in the example above, I'm streaming in a very large amount of rows, being able to stream and pass a single row down directly has a substantially lower memory footprint than returning the entire row set as an array to iterate over.

Really appreciate any guidance you can give!

**Comment by laverdet** [comment]
Thanks for the complete reproduction case, it makes helping you a lot easier.

If you just change `callback.applySync` in `findRows` to `callback.apply` or `callback.applyIgnored` your problem goes away. Calling a sync function will always run in the current thread. So if you call a sync function from the main isolate, it will run in the main thread (main thread and main isolate are different things).

**Comment by tom-acceleratecompliance** [comment]
Wow I can't believe it was that simple. I had thought not using sync would mean the promise wouldn't resolve, but that makes perfect sense, thanks so much!

**Comment by tom-acceleratecompliance** [comment]
Ah sorry I did some further testing, the issue is that the call to get rows is actually an async database call (knex streaming).
This means, that because the function call isn't blocking, the script is completing before all the rows have been streamed in, meaning I get a `Error: Isolate was disposed during execution` when calling apply. Any idea if this is possible to fix?

**Comment by laverdet** [comment]
There's a lot going on here in this example.

`applySyncPromise` is one of the more nuanced methods in this module. It will completely suspend the current isolate and wait for a promise to resolve in the default nodejs isolate. While that promise is outstanding it's impossible for the isolate to do other work unless it's invoked via a *Sync method. If a call to `applySyncPromise` is still unresolved you won't be able to invoke a callback inside of that isolate. The purpose of this function is to make it possible to implement something like `fs.readFile` without blocking the whole process. `fs.readFile` "stops the world" while the work is being done, so that's what this method does.

Invoking a callback once per row from isolate to isolate seems like a bad idea. There's a great deal of overhead involved in these callbacks. I'd recommend just sending over all the rows at once if possible. Unless you're streaming 100,000s of rows I think this will end up being better. If you're streaming a ton of data then I'd recommend some kind of batching algorithm.

I think the classic nodejs callback-style is really messing you up here. If you build this around functions which return it becomes much less finicky. Here is an example that's closer to what you're trying to do?

```js
const ivm = require('isolated-vm');
  
let isolate = new ivm.Isolate();
let context = isolate.createContextSync();
let jail = context.global;
jail.setSync('global', jail.derefInto());

function log(...args) {
  console.log(...args)
}

context.evalClosureSync(`global.log = function(...args) {
  $0.applyIgnored(undefined, args, { arguments: { copy: true } });
}`, [log], { arguments: { reference: true } });

async function findRows() {
  // In actual app all these rows are fetched async
  let rows = [
    { label: 'A', value: 'a' },
    { label: 'B', value: 'b' }
  ];
  // Must use `ExternalCopy` manually because of `applySyncPromise` limitation. This is the same as
  // { return: {copy: true} }
  return new ivm.ExternalCopy(rows).copyInto();
}

context.evalClosureSync(`global.findRows = function(callback) {
  const rows = $0.applySyncPromise();
  for (const row of rows) {
    callback(row);
  }
}`, [ findRows], { arguments: { reference: true } });

// This works, but the callback function code seems to be in the main isolate. 
context.eval(`
  findRows(function(row) {
    log(row)
  })
`)

async function processRow(row) {
  return `processed: ${JSON.stringify(row)}`;
}

context.evalClosureSync(`global.processRow = function(row) {
  return $0.applySyncPromise(undefined, [ row ], { arguments: { copy: true } });
}`, [ processRow ], { arguments: { reference: true } });

context.eval(`
  findRows(function(row) {
    // This break as processRow cannot be run from the main thread.
    // How do I get this to be executed in the isolate thread?
    log(processRow(row))
  })
`)
```
