### ISSUE TITLE
Get individual context usage

### ISSUE THREAD

**Issue by keverw** [laverdet/isolated-vm#195]
I been playing around with this project a bit, since considering using it to power a script engine for a virtual world idea I've been toying around with. The memoryLimit of 8 seems a bit high for my use case... So I was thinking i'd be cool to measure memory, maybe even CPU per context.

I don't use Ruby but I know another library was mentioned https://github.com/rubyjs/mini_racer that seems to have a soft limit for each context. Then ideally I could create an isolate per user and then each script would run in a context.

This is a very cool and inspiring project though :)

**Comment by laverdet** [comment]
v8 is not the engine for you if you want to run JS without using 8mb. Have you *seen* Chrome's memory usage??

**Comment by keverw** [comment]
Yeah, I know that's one of the criticisms of Chrome. I know I was running one script and it was about 700KB. So I was thinking maybe be cool to measure a context individually, I think it might possible (not sure how that other lib does it, if so maybe it's just an extra binding needed that V8 already has).

But yeah not sure if going down the right path, I do love the idea of using a language high level like JS though. I know some of these scripts might only be 1 event and a few functions. I was thinking of WASM too as a possibility, but I really loved the feel of JS and this.
