### ISSUE TITLE
[feature] Provide precompiled libraries

### ISSUE THREAD

**Issue by alumni** [laverdet/isolated-vm#201]
Would it be possible to provide precompiled node bindings? Compiling on Linux is easy, but on Windows it's quite a mess.

**Comment by laverdet** [comment]
Sorry, I don't want to do this. I do this for [node-fibers](https://github.com/laverdet/node-fibers) and it's been a total nightmare.

All you have to do on Windows is install Python and Visual Studio Build Tools.

**Comment by bergundy** [comment]
We'd like to have this for the Temporal node SDK, is there any chance you'd reconsider?
Can we assist you with this?

**Comment by laverdet** [comment]
Binary releases are just a constant and unrelenting cognitive burden. It's not really a feature you can do once and then forget about.

**Comment by bergundy** [comment]
I totally understand,
I see that you've had a bad experience with binary releases for fibers, I don't have that kind of experience and I believe you.
Is this something that can be automated with CI?
I've recently set up binary builds with our Rust (neon) module using Rust's cross compilation features and leveraging n-api's ABI stability, it wasn't too hard to do including automated testing of the prebuilt binaries, but that's Rust and not cpp.

**Comment by orgads** [comment]
Created a prebuilt release. Until #366 is accepted, you can install it using:

```bash
npm install isolated-vm-prebuilt
```

**Comment by alumni** [comment]
@laverdet Could we get prebuilt binaries for v5? Thanks! :)

**Comment by laverdet** [comment]
they are out
