### ISSUE TITLE
Question: difference between external copy and deep copy

### ISSUE THREAD

**Issue by ErkoKnoll** [laverdet/isolated-vm#203]
Hi,

In the version 2 I was using external copy to move data between isolates. In version 3 I'm seeing this additional option to use `copy` as part of `TransferOptions` which is supposed to use "deep copy". What's the difference between them? And when I'm supposed to use "deep copy" and when regular external copy?

**Comment by laverdet** [comment]
The `copy` parameter uses the same algorithm as `ExternalCopy`, the [structured clone algorithm](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm). I'd recommend using `copy` in almost all cases. The reason for the `ExternalCopy` class is that it makes it possible to avoid duplicated work when copying the same value into multiple isolates. Moving a value from one isolate to another is actually a two step process, first the data must be copied *out*, then it must be copied *in*; there is no direct isolate-to-isolate method to copy a value. So if you have some large data structure that must be used in many different isolates you would use an `ExternalCopy` instance to copy it out only once.

**Comment by ErkoKnoll** [comment]
Thanks for the clarification!
