### ISSUE TITLE
How to release context safely for top level async?

### ISSUE THREAD

**Issue by cemremengu** [laverdet/isolated-vm#204]
For the top level async/await like

```js
(async () => {
  await blah();
})()
```

`context.release()` prematurely throws away the context killing the running script. Is there a way to make sure that the context is released only after the script is *really* done?

**Comment by laverdet** [comment]
> context.release() prematurely throws away the context killing the running script. 

This isn't true, it just releases the handle. If there are still outstanding references to values in the context, the garbage collector will keep the context alive. You can confirm with this example:
```js
const ivm = require('isolated-vm');
const isolate = new ivm.Isolate();
const ctx = isolate.createContextSync();
const fn = ctx.evalSync('function fn() { return 123; } fn;', { reference: true }).result;
ctx.release();
console.log(fn.applySync());
```

Logs `123`

**Comment by cemremengu** [comment]
You are right however, in my case, I somehow get this behavior. Here is a mcve:

https://github.com/cemremengu/isolatedvm-mcve

**Comment by laverdet** [comment]
Thanks, this does look like it's incorrect. I just pushed a potential fix. If possible could you install from github and see if it's been resolved on your end?

**Comment by cemremengu** [comment]
Confirmed, seems to be resolved. Thanks for the quick patch!

**Comment by cemremengu** [comment]
Sorry to bother but I have a quick question: what exactly does `{ reference: true }`  for `evalSync` ? In other terms, when should I use it?

**Comment by laverdet** [comment]
It's one of the transfer options. `eval` returns the result of the last statement executed, as long as that value is transferable. In the case of my example `fn` is the last statement. A function is not transferrable but by passing `{reference:true}` it is automatically wrapped in a `Reference` instance.
