### ISSUE TITLE
Using SharedArrayBuffers in snapshots

### ISSUE THREAD

**Issue by Jerska** [laverdet/isolated-vm#208]
Hi @laverdet !

Following your advice in https://github.com/laverdet/isolated-vm/issues/101 , we ended up compiling `whatwg-url` with webpack and loading it as a snapshot in our isolate and it worked great!
A recent update of `whatwg-url` unfortunately broke this setup: it added a direct dependency at load time on `SharedArrayBuffer`.

From my understanding, `SharedArrayBuffer` seems to not be defined on `this` initially, but only to be injected when injecting `global` with:

```js
  const jail = context.global;
  await jail.set('global', jail.derefInto());
```

There are a few keys in that case:

```txt
                 Key | In old | In new
             Atomics |        |   true
FinalizationRegistry |        |   true
   SharedArrayBuffer |        |   true
             WeakRef |        |   true
         WebAssembly |        |   true
              global |        |   true
```

As a result, this code will throw:

```js
const ivm = require('isolated-vm');
ivm.Isolate.createSnapshot([{ code: `SharedArrayBuffer.prototype.byteLength` }]);

// Throws with
// ReferenceError: SharedArrayBuffer is not defined
```

My bet as to why `SharedArrayBuffer` isn't defined in the isolate is because the whole point of the class is sharing stuff across isolates?

I guess that moving this code at the beginning of the `compileScript` call should make it work back as expected.
We'd be happy to put as much code as possible in the snapshot though, so if you have an idea on how we could do that, I'd be happy to have your input.

As I say everytime I open issue here, thanks again for this project, which is probably the most useful library I've ever used.

**Comment by laverdet** [comment]
Can you do something like this:

```js
const snapshot = ivm.Isolate.createSnapshot([ { code: `function install() { try { ${outputFromWebpack} } finally { delete install } }` } ]);
```

And then you would just add: `context.eval('install()')` after you create your contexts.

**Comment by Jerska** [comment]
Thanks for your answer!

This is definitely a valid option.
My knowledge is quite limited, but I always assumed the main value of snapshots came from the warmup more than the parsing.

**Comment by laverdet** [comment]
It's worth trying it out and see if it has a noticeable performance penalty. You could also just try `SharedArrayBuffer = ArrayBuffer` as a preamble.

**Comment by Jerska** [comment]
Thanks for the replies!
I'll close this out, as there's no real issue here, it was more out of curiosity.
