### ISSUE TITLE
Single entrypoint

### ISSUE THREAD

**Issue by PostCrafter** [laverdet/isolated-vm#21]
This is probably caused by some misunderstanding from my side, but I'd like to know how I'd go about providing a single entry point (function) to pass data into my isolate. Since the isolate contains user code, putting data into the global context or declaring a top level named function is not really an option, because the user will be able to call and/or modify the data.

Therefore I've tried the following, wrapped in an IIFE because top level anonymous functions are not allowed.
```javascript
    const isolate = new ivm.Isolate()
    const context = await isolate.createContext()

    const script = await isolate.compileScript(`
        ;(function() {
            return function() {}
        }())      
    `)

    return await script.run(context)
```
Unfortunately this returns `undefined`, since it works with primitives (numbers, strings, null), but not with functions or objects, I assume it has something to do with the value not being transferable.

Could you please explain if I'm missing something here or provide some alternative solution?

Let me know if you need any additonal information regarding my use case.

**Comment by laverdet** [comment]
The trick is to set a global variable and then delete it before you run untrusted code. The first example in the README.md file shows how you would do this. It sets a global with the contents of the ivm module and then deletes that global while bootstrapping, before any untrusted code runs. That way the reference to the module only exists in a closure that the untrusted code doesn't have access to.

Another way to do it would be to make the bootstrap function a global which deletes itself when it gets called. This method would have the advantage that you only have to remember to delete one global and can pass all your `Reference` instances as arguments.
