### ISSUE TITLE
Is this secure?

### ISSUE THREAD

**Issue by Cosbgn** [laverdet/isolated-vm#210]
Hello, I need to run some very basic code from an untrusted source (my users).
I don't need:

- Internet access
- Any external library access
- Any access to process or the system I run the code on.

My users run all on the same AWS lambda serverless environment, so it's very important that nothing is shared between them. Currently I simply do this:

```
		const ivm = require('isolated-vm');
		const isolate = new ivm.Isolate({ memoryLimit: 8, inspector:false });
		const context = await isolate.createContext();
		const data = [324,5,6,5,"67",7,7] // This data changes and I need it inside the script
		context.global.setSync('data', JSON.stringify(data));
		const script = await isolate.compileScript(`let x = JSON.parse(data); [... here goes the untrusted/unknown user script] JSON.stringify(x)`);
		const output = await script.run(context, {timeout:500})
		.then(r => ({response:JSON.parse(r)}))
		.catch(err => ({error:err.message}));
		isolate.dispose()
		return output
```
This seems to work very well, I just would like a confirmation that whatever goes between the `[... here goes the untrusted/unknown user script]` can't access anything related to the machine, my database, environment or anything else.
Sorry for the question here in the issues! Thank you very much in advance!

**Comment by laverdet** [comment]
Yeah that's fine. As a matter of conveinence you can use the `{copy: true}` option to avoid manually passing all your data through JSON. The `eval` family of functions serve as a replacement for compile -> run, as well.

```js
const ivm = require('isolated-vm');
const isolate = new ivm.Isolate({ memoryLimit: 8, inspector:false });
const context = await isolate.createContext();
const data = [324,5,6,5,"67",7,7] // This data changes and I need it inside the script
context.evalClosure(
  'let x = $0; unstrusted...; return x;',
  [ data ],
  { timeout: 500, arguments: { copy: true }, result: { copy: true } })
  .then(r => ({ response: r.result }));
```
