### ISSUE TITLE
How to use external modules inside the VM

### ISSUE THREAD

**Issue by Cosbgn** [laverdet/isolated-vm#217]
I would like to be able to make API calls from the VM. 
Is it possible to allow the use of `axios`, `http/s` or any other http module from inside the VM?

**Comment by Cosbgn** [comment]
So far I tried with all sort of http libraries, even hard-coding them in the script. However I always fail at `"XMLHttpRequest is not defined"`

Is there a way to `import unfetch` `import tiny-json-http` or any other small library to make API requests?

**Comment by laverdet** [comment]
Sorry, please give vm2 a try

**Comment by omercakici** [comment]
> Sorry, please give vm2 a try

supporting the external modules are necessary to use ,i think.
