### ISSUE TITLE
Consider cleaning up release package

### ISSUE THREAD

**Issue by akaustel** [laverdet/isolated-vm#218]
I think the whole thing could be reduced to a few MiB, but it is now 92MiB.

The binaries are not stripped, and unnecessary things are included in the `npm` release.

I'm on a linux-x64 box.

```sh
$ du -hs | grep M
92M	.
```

```sh
19024496 Oct 23 11:39 isolated_vm.node
1830160 Oct 23 11:39 nortti.a
```

stripping took them to: 

```sh
950480 Oct 26 13:51 isolated_vm.node
25358 Oct 26 13:51 nortti.a
```

```sh
node_modules/isolated-vm/build/Release/obj.target/isolated_vm/src$ du -hs .
49M	.
```

**Comment by laverdet** [comment]
I think you're mistaken. The npm package size is 500kb.

```
marcel@marcel ~ $ npm view isolated-vm | grep -i size
.unpackedSize: 500.7 kB
```

As part of the install process node-gyp generates a number of platform-specific object files. This is standard practice for most binary packages. If the disk space is an issue for you then you can nuke them after running `npm install` on your production builds. You would want to do that for other binary packages as well-- again, this isn't unique to isolated-vm.

Please don't strip the binaries, though. If you run into an error that data is instrumental in getting help from me.

**Comment by akaustel** [comment]
Yes, you are right I was mistaking. The package in it self is small it is the build process that creates seemingly excessive output.

The reason I'm looking into this in the first place is that we use pipelines in bitbucket and I'm trying to make some performance improvements there.

There are multiple binaries and the temporary build in the `build/Release/obj.target` directory is 71M, is this really necessary? Could be removed in `postinstall` step?

> Please don't strip the binaries, though. If you run into an error that data is instrumental in getting help from me.

I know, but when reproducing problems one should have the debug data intact.

*By the way, this is really great work, it is amazing what you can do with this!*

**Comment by laverdet** [comment]
I found a pretty clean way to do this without any platform-specific nonsense. It'll be in the next release, whenever that is.

**Comment by akaustel** [comment]
Very nice and clean solution!

I'm sure other packages could benefit from this solution as well.
