### ISSUE TITLE
queueMicrotask support

### ISSUE THREAD

**Issue by mafintosh** [laverdet/isolated-vm#219]
Hi. Great module!

Any plan to support `queueMicrotask` in the isolate?

**Comment by laverdet** [comment]
`queueMicrotask` is part of the HTML specification, not the JS specification. It's not included for the same reason that `setTimeout` isn't included. Mozilla has a polyfill ready to go for you at https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/queueMicrotask:

```js
if (typeof window.queueMicrotask !== "function") {
  window.queueMicrotask = function (callback) {
    Promise.resolve()
      .then(callback)
      .catch(e => setTimeout(() => { throw e; })); // report exceptions
  };
}
```
