### ISSUE TITLE
Is it possible to share node modules?

### ISSUE THREAD

**Issue by jdat82** [laverdet/isolated-vm#22]
Hi,

I just read the documentation but all examples compile very simple code which has no state and no link to the host state.

I'm wondering: is it possible to share node modules like puppeteer for instance? If you don't provide access to the fs module for instance, and the library you provided need it, what happens?

In my case, I have a pool of connections to Chrome and I want to inject it in a isolated script. By reading the documentation I'm not very confident that's possible. It seems to me everything shared with an isolate is serialized and thus it only applies to raw data but not stateful objects. 

I would love a bit of clarification. Thanks.

**Comment by AgentME** [comment]
You could make a stub module (representing a module like puppeteer or fs) within the isolate which uses synchronous calls to the main-isolate for all interactions, and serializes parameters for function calls within the isolate. (Though if you're doing a lot of writes of large buffers with the fs module and don't want to transfer the buffers to the main-isolate, then there could be a real perf cost to copying all of the buffers.)

**Comment by laverdet** [comment]
Yeah you need to stub out the functions you want and send that back and forth to the main nodejs isolate. Sharing state between different isolates is impossible, thus the term "isolated". To share state you need to share a heap, garbage collector, and thread which is what we're trying to avoid in the first place. `SharedArrayBuffer` is one solution to shared state in JS but it's a very new feature and also not really what you're looking for here.

**Comment by jdat82** [comment]
That's what I thought, this library is interesting but not suited for my use case. Thanks.
