### ISSUE TITLE
Promise.race causes exception to be thrown

### ISSUE THREAD

**Issue by bergundy** [laverdet/isolated-vm#222]
Hi,

I've encountered an issue where `Promise.race` throws in an isolated-vm isolate where Chrome and NodeJS don't.

Code:
```js
context.evalSync('Promise.race([1, 2])', { promise: true });
```

```js
context.evalSync(`Promise.race([1, Promise.reject(new Error('error'))])`, { promise: true });

```

It seems like we might not be handling [PromiseRejectCallback](https://github.com/laverdet/isolated-vm/blob/26cc3458eedb60256be0eee046c1250209d2c172/src/isolate/environment.cc#L91) correctly.

The rejection event ([`GetEvent()`](https://v8.github.io/api/head/classv8_1_1PromiseRejectMessage.html#a6faaa07f9bb78ee482b84ef7553c3245)) in the first case is `kPromiseResolveAfterResolved`.
In the second case we get:
```
kPromiseRejectWithNoHandler
kPromiseHandlerAddedAfterReject
kPromiseRejectAfterResolved
```

Not sure what the right solution is but I find the current behavior surprising.

**Comment by laverdet** [comment]
Uncaught promise errors are sent to the top-most execution context, it was a design choice of isolated-vm to avoid orphaned errors.

**Comment by bergundy** [comment]
I understand the need for avoiding orphaned errors but the thrown error isn't really an error.
If you run
```ts
context.evalSync('Promise.race([1, 2])')
```
It throws the number 2 which is unexpected.

**Comment by bergundy** [comment]
Note that you can't catch this exception in the isolate.

**Comment by laverdet** [comment]
Cool thanks for the report and test cases. I'll push the committed fix to npm soon.

**Comment by bergundy** [comment]
Thanks for the quick response but I'm afraid that the fix broke other cases.

For example these now throw where they didn't use to:
```js
context.evalSync(`
  Promise.reject(new Error('abc')).catch(() => {});
`);
```

```js
context.evalSync(`
  (async () => {
    try {
      await new Promise((_, reject) => reject(new Error('abc')));
    } catch (err) {
      // ignore
    }
  })();
`);
```

**Comment by laverdet** [comment]
Ah yeah the previous fix had some sloppy issues. I just pushed an updated version to `main`, do you want to take a look and see if the behavior is as expected?

**Comment by bergundy** [comment]
Looks like the issue is solved in main, thanks again!
