### ISSUE TITLE
Suppress nodegyp compilation warnings related to: "cast between incompatible function types"

### ISSUE THREAD

**Issue by KalleV** [laverdet/isolated-vm#223]
It's not causing any errors with functionality, but we've been seeing a lot of nodegyp-related warnings related to function type casting when installing the isolated-vm dependency. After some investigation, it seems like the specific typecasting error could be suppressed with the **-Wno-cast-function-type** flag (e.g. https://github.com/DataDog/dd-trace-js/pull/943/files). Would there be any downsides to suppressing this particular warning?

**Comment by laverdet** [comment]
I guess the downside is that it would suppress this error project-wide.

For what it's worth the v8 team has already silenced this error upstream https://github.com/v8/v8/commit/f08cbfdc4051266e4200b6e26775d35307b1259b
