### ISSUE TITLE
Native example doesn't compile

### ISSUE THREAD

**Issue by bergundy** [laverdet/isolated-vm#224]
Hi,

I tried compiling the native example and I've encountered a few issues on MacOS:
1. `binding.gyp` is missing:
```
      'cflags_cc!': ['-fno-exceptions'],
      'conditions': [
        ['OS=="mac"', {
          'xcode_settings': {
            'GCC_ENABLE_CPP_EXCEPTIONS': 'YES'
          }
        }]
      ],
```

2. `package.json` is missing an `isolated-vm` dependency.

Once I've managed to compile it I got a segfault when trying to run the code at `isolated_vm::IsolateHolder::GetCurrent()`.
Happened in node `12.20.1` and `14.5.0`.

I can submit a PR to fix compilation but I'd like to hear some thoughts about the segfault.

Thanks!

**Comment by laverdet** [comment]
The native add-on API has fallen out of support because nobody used it. Do you have a good use-case for it?

**Comment by bergundy** [comment]
I'm writing an SDK for Temporal which requires a completely deterministic JS runtime.
In order to achieve that I need to swap and add some globals in the isolate such as `Date()`, `Math.random()`, `setTimeout()`.
I'm currently using function references injected from the main isolate with `evalClosure` and called using `applySync()`.
FWIU, `applySync()` will not work well in multithreaded node since it blocks the caller thread until function completion.
I wanted to use native modules so I don't have to enter the main nodejs isolate for every synchronous function call.
Does that make sense?

**Comment by bergundy** [comment]
https://temporal.io/
This is the SDK's proposal https://github.com/temporalio/proposals/blob/master/node/node-sdk.md

**Comment by bergundy** [comment]
Thanks!

**Comment by laverdet** [comment]
I tweaked this in `main` so it runs now, I'd definitely consider this experimental though.

Also you might not actually need a native extension here. Take a look at `applySyncPromise` which lets you invoke an async function belonging to the nodejs isolate, which will be sync/block in the isolate until a promise resolves.

**Comment by bergundy** [comment]
With applySyncPromise does the isolate thread block or is it just the isolate that's paused?

I wanted to use a native module to bypass the switch to the default isolate because I have a native library that I need to communicate with.
How much locking does applySyncPromise require, what's the overhead?

**Comment by laverdet** [comment]
applySyncPromise will cause the isolate and the thread it's running on to block. This would be true with a native extension as well. The nodejs/uv thread would remain asynchronous though.

You'd have to test the overhead yourself, but `applySyncPromise` shouldn't be any more heavy than `apply`. If you're just communicating directly with some native API then nodejs via applySyncPromise would just be acting as an unneeded middleman.

**Comment by bergundy** [comment]
Looks like it works, thanks for this awesome module!
