### ISSUE TITLE
what does ivm.lib contains?

### ISSUE THREAD

**Issue by bodinsamuel** [laverdet/isolated-vm#225]
Hello,

I noticed an [example](https://github.com/laverdet/isolated-vm/blob/98971924d21d7f0aec3c90fa64d87e6e30b2c49e/tests/hrtime.js) where you use ivm.lib.hrtime, 
however this prop `lib` is not documented in the d.ts so i'm not sure it's a stable api.

Thanks ☺️

**Comment by laverdet** [comment]
It just contains the one function, `hrtime`, which was added so Screeps could have a way to measure execution time. The thought was that maybe I could add low-level POSIX primitives like `open` and `recv` to this namespace but there hasn't really been a demand for that, and `applySyncPromise` now meets those needs anyway.

**Comment by bodinsamuel** [comment]
ah perfect, thanks for the very quick answer <3
