### ISSUE TITLE
Memory leak introduced in 3.3.6

### ISSUE THREAD

**Issue by isker** [laverdet/isolated-vm#227]
Hi.  We recently upgraded to isolated-vm 3.3.7.  Doing so introduced a memory leak in our service, which uses isolated-vm to render React templates on the server.  (We can provide more details of our usage if you think it'd be helpful.)  

We bisected and load tested isolated-vm versions to reveal that the leak was introduced in 3.3.6.  This plot shows the memory usage (specifically [`process.memoryUsage().heapTotal`](https://nodejs.org/api/process.html#process_process_memoryusage)) of two instances of our service under our load test.  The instances are identical except for the isolated-vm version:  yellow is 3.3.6, blue is 3.3.5.

<img width="1631" alt="Screen Shot 2021-01-16 at 2 37 46 AM copy" src="https://user-images.githubusercontent.com/5225653/105082631-deba2200-5a61-11eb-87a6-a75ea66b411d.png">

There are only a handful of native commits in 3.3.6, but some of them are non-trivial: https://github.com/laverdet/isolated-vm/compare/v3.3.5...v3.3.6.  Do you have suspicions on any particular one?

Also, we identified this leak using `heapTotal` in the main thread simply because that's what our monitoring and alerting on our service was looking at beforehand.  After the fact, we noticed that another property on `process.memoryUsage()` has this note in the docs:
> When using Worker threads, `rss` will be a value that is valid for the entire process, while the other fields will only refer to the current thread.

Do you know whether this applies to Isolates as well?

Thanks for your help.  Let us know whether you need more information.

**Comment by laverdet** [comment]
`heapTotal` returns memory usage as reported by the main v8 isolate, so the documented behavior with regards to Worker threads is the same as isolates. It's peculiar that the leak was noticed by this metric which turned out to be a good enough clue to find the problematic commit.

You can try `npm install laverdet/isolated-vm#main` and see if that resolves your leak.

**Comment by isker** [comment]
Thank you!  Will run a test overnight and let you know.

**Comment by isker** [comment]
That fixed it!  Thanks!

**Comment by laverdet** [comment]
The github version you installed is available on npm as 3.3.10 now if you want to update the dependency to something stable.

**Comment by isker** [comment]
Thank you.
