### ISSUE TITLE
Assertion failed: (tasks.empty())

### ISSUE THREAD

**Issue by jeromegn** [laverdet/isolated-vm#23]
I get the following error sometimes when trying to dispose of an Isolate:

```
Assertion failed: (tasks.empty()), function Dispose, file ../src/shareable_isolate.h, line 357.
```

I'm only running one context and am waiting for all the code I'm running to be done before disposing of its isolate.

Anything I should be doing before disposing of my Isolate?

Note: I'm using master.

**Comment by laverdet** [comment]
Thanks. This is caused when the isolate still has unresolved promises outstanding and you call dispose() on the isolate. I fixed the crash here and it'll throw a catchable exception instead. I'll need to consider making dispose asynchronous in the future.
