### ISSUE TITLE
isolated-vm boundary issue

### ISSUE THREAD

**Issue by tigercosmos** [laverdet/isolated-vm#233]
I encountered the issue below, which is not likely to happen if not using isolated-vm.
How can I set the memory limit bigger?

```
Error: Isolate was disposed during execution due to memory limit
    at (<isolated-vm boundary>)
```

Enviroments: isolated-vm 4.0.0 with NodeJS 14

**Comment by laverdet** [comment]
There is an option on the Isolate constructor for `memoryLimit`, please see the docs.
