### ISSUE TITLE
TypeError: #<Promise> could not be cloned.

### ISSUE THREAD

**Issue by carlosdp** [laverdet/isolated-vm#234]
On 4.0.0, no matter what transfer options I choose, if I return a Promise from an in-isolate function and I call or `apply` that function, I get the error: `TypeError: #<Promise> could not be cloned.`

This is with an extremely simple Promise being returned: `new Promise((resolve, reject) => { return {} });`

This worked fine on v3.x

**Comment by laverdet** [comment]
Do you mind posting a complete repro?
