### ISSUE TITLE
How to catch errors when using await?

### ISSUE THREAD

**Issue by vanesca88** [laverdet/isolated-vm#235]
I have the following code.
It seems that using await, will prevent any following errors from being caught.
Not sure if its a bug, or if I'm doing it wrong.

If you comment the await test(), then the fake foobar() gets caught.
If you don't comment it, it completely gets ignored by isolated-vm.
How can I catch the error?
Thanks in advance. Great library.

```javascript
const ivm = require('isolated-vm');
let isolate = new ivm.Isolate;
let context = isolate.createContextSync();

const jail = context.global;
jail.setSync('global', jail.derefInto());

const returnCallback = function(...args) {
  return new Promise((resolve ) =>{
        setTimeout( () => {
            console.log('a')
            resolve()
        }, 1000)
    });
};
context.evalClosureSync(`global.test = function(...args) {
  return $0.applySync(undefined, args, { arguments: { copy: true }, result: { promise: true } });
}`, [ returnCallback ], { arguments: { reference: true } });

let script = isolate.compileScriptSync(`
(async() => {
        await test() // <----- comment line, so errors get caught again!
        foobar()
    })();
`);
script.runSync(context);
```

**Comment by vanesca88** [comment]
Already found a possible solution
Seems that a promise shouldn't use a return.
That exact same return it why the followup errors are being dismissed.

Leaving this here, in case it helps someone:

```javascript
const returnCallback = function(...args) {
    // return new Promise((resolve ) =>{ // <----- don't use return before the promise!
    new Promise((resolve ) =>{ // <----- correct
        setTimeout( () => {
            console.log('a')
            resolve()
         }, 1000)
    });
};
```

**Comment by laverdet** [comment]
Your call to `runSync` is throwing away a promise.

You need to change it [line 26] to something like this:
```js
script.runSync(context, { promise: true }).then(console.log, console.error);
```

With that change the error is printed to stdout.

I recommend thoroughly reading JS promise documentation: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

**Comment by vanesca88** [comment]
I already know how JS promises work.
That wasn't the question.
Just that your library good, but also extremely confusing.
