### ISSUE TITLE
No longer limit script execution time

### ISSUE THREAD

**Issue by bodinsamuel** [laverdet/isolated-vm#237]
Hey following yesterday bug report,
I have a second one that might be related.

Simple execution no longer respect timeout and continue to execute for ever in async/ref version.

```js
// Async with ref example not working
(async () => {
	let isolate = new ivm.Isolate();
	let context = isolate.createContextSync();
	let script = isolate.compileScriptSync(`
                function top() {
			while (true) {
				// will cause a timeout error,
			}
                }
	`);
	await script.run(context);
	try {
		let fnReference = await context.global.get('top');
                await fnReference.apply(undefined, [], { timeout: 1000 });
		assert.fail("Did not throw");
	} catch (err) {
		assert.match(err.message, /Script execution timed out/);
	}
})()

// Sync example working
{
	let isolate = new ivm.Isolate();
	let context = isolate.createContextSync();
	let script = isolate.compileScriptSync(`
		while (true) {
			// will cause a timeout error,
		}
	`);
	try {
		script.runSync(context, { timeout: 1000 });
		assert.fail("Did not throw");
	} catch (err) {
		assert.match(err.message, /Script execution timed out/);
	}
}
```

**Comment by laverdet** [comment]
`let fnReference = await context.global.get('top');`

In this case `fnReference` is a plain function that calls the underlying reference in sync mode with no timeout. When you use `.apply` on it you're literally just calling `Function.prototype.apply` and the 3rd argument is totally ignored. Basically this is meant for delivering API functions *into* isolates. If you're plucking functions *out of* isolates you should probably still use a Reference instance. So I'd suggest changing that to `.get('top', { reference: true })`.

I should have renamed `apply` on `Reference` as part of this change but didn't think of it.

**Comment by bodinsamuel** [comment]
Indeed, it works with `.get('top', { reference: true }).`

I'm not sure at this point our implem is very good, would you recommend not using `.apply()` (I'm not sure if it changes anything security wise)
I could probably change the code to execute the same way without the `get()` like this:
```js
let script1 = isolate.compileScriptSync(`
  function top() {
    while (true) {
      // will cause a timeout error,
    }
  }
`);
await script1.run(context);

let script2 = isolate.compileScriptSync(`
  top();
`);
await script2.run(context);
```

**Comment by laverdet** [comment]
Since you're asking about timeouts I'm assuming that you're extracting some user code *out of* an isolate. In that case it's perfectly safe to use `{reference:true}` as long as you make sure not to give that reference back to untrusted code.

**Comment by bodinsamuel** [comment]
thanks 🙏🏻
