### ISSUE TITLE
Segfault on RemoveWeakCallback

### ISSUE THREAD

**Issue by bodinsamuel** [laverdet/isolated-vm#239]
Hey, 
we are debugging a segfault happening only in production,
while trying to write a local repro I encountered one segfault.

I'm not even sure it's a real issue and even if it's the one we are looking for, 
but very not often I have this one.

machine: macOs Big Sur 11.2.3  - 3,1 GHz Dual-Core Intel Core i5

```bash
(lldb) run
prout
prat <?xml vers
Process 33916 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x2e2)
    frame #0: 0x0000000104c6cc7f isolated_vm.node`ivm::IsolateEnvironment::RemoveWeakCallback(v8::Persistent<v8::Value, v8::NonCopyablePersistentTraits<v8::Value> >*) + 15
isolated_vm.node`ivm::IsolateEnvironment::RemoveWeakCallback:
->  0x104c6cc7f <+15>: cmpb   $0x0, 0x2e2(%rdi)
    0x104c6cc86 <+22>: jne    0x104c6ccc8               ; <+88>
    0x104c6cc88 <+24>: movq   %rdi, %rbx
    0x104c6cc8b <+27>: addq   $0x6a0, %rbx              ; imm = 0x6A0
Target 0: (node) stopped.

Process 33916 launched: '/Users/samuelbodin/.config/nvm/14.16.1/bin/node' (x86_64)
(lldb)
```

I'm running this script

```bash
while true; lldb -b -o run -- node --max-old-space-size=13 tests/big-param.js; end
```

```js
const fs = require('fs');
const path = require('path');
let ivm = require('isolated-vm');


(async () => {
  let isolate = new ivm.Isolate();
  let context = isolate.createContextSync();
  let script = isolate.compileScriptSync(`
    function top(file) {
      const t = file.substr(0, 10);
      console.log(t);
      return t;
    }
  `);

  const file = fs.readFileSync(
    path.join(
      __dirname,
      'sitemap-10mb.xml'
    )
  )
  .toString();

  await script.run(context);
  console.log('prout');

  let fnReference = await context.global.get('top', { reference: true });
  const res = await fnReference.apply(undefined, [file], { timeout: 1000 });

  console.log('prat', res);
})()
```

The file (10mb) https://storage.googleapis.com/algolia-crawler-assets/_test/sitemap-10mb.xml

---

It happen once in a while, I'm not sure it's because of the big file itself or not.
(N.B: I was trying to see what happen if we pass a big param, when being very close to max out the mem)

Please feel free to discard if it's normal or irrelevant,

**Comment by bodinsamuel** [comment]
Not related to the reported issue above:
I have finally reproduced the segfault I was looking for in prod however the stack is not helping. It seems to be V8 related, and found this related issue (updated yesterday). https://bugs.chromium.org/p/v8/issues/detail?id=11615#c12
Maybe it's worth checking and upgrading V8.


![Screen Shot 2021-04-16 at 16 16 22](https://user-images.githubusercontent.com/1637651/115038731-19502100-9ed0-11eb-9dd4-2c9151342a3a.png)
(NB: `bt` leads to 16K of `in ?? ()` unfortunately)

**Comment by laverdet** [comment]
I took a look at the first issue you reported and was able to reproduce, thanks for the good test case. This is an issue that will only show up when nodejs is terminating. The issue is that nodejs frees up all v8 handles it's holding which totally unloads the isolated-vm module from memory. After it cleans, up v8 runs all outstanding garbage collection tasks which actually ends up invoking isolated-vm again but since the module is already unloaded all the data structures are no longer valid. I'm sure I can patch it up but I wanted to point out that if you're seeing issues in long running processes then it's not going to be the same issue.

**Comment by bodinsamuel** [comment]
It might indeed not be the same, I still need to figure out a repro in my machine.
Currently our main issue is `isolated + kube + cheerio + a big file`. I'll reach out again when I finally figured out.

For the initial report, would love a patch, can still help 🙏🏻

**Comment by bodinsamuel** [comment]
We investigated a bit more and we have found out it happen because of a recursive call in a third party package.

But it's "reproductible easily" with.
```
function recur() {
  return recur();
}
recur();
```

The big BUT is that it still only happen in our prod:  
`<= GKE 1.19.9-gke.1900` (did not test higher version)
`Container-Optimized OS with Docker (cos)`
`e2-highcpu-4 => 3.92 CPU + 2.96 GB `

**Comment by laverdet** [comment]
If the case is reproducible would you mind posting an entire program? I'm not sure what to do with this snippet.

**Comment by bodinsamuel** [comment]
Tried to achieve the minimum possible, this should do it.

Locally it runs fine (throws `Maximum call stack size exceeded`), but in GKE it segfault.
https://github.com/bodinsamuel/isolated-vm-repro

**Comment by laverdet** [comment]
Can you try tweaking this constant? Maybe 16kb or 32kb?

https://github.com/laverdet/isolated-vm/blob/b386b225603d908a96eae1443966283771564b68/src/isolate/environment.cc#L232-L233

I'm on the road so I'm unable to give it a try for at least another week.

**Comment by bodinsamuel** [comment]
I'll need to fork and publish a new package just for that try, I'll wait for you to come back and try/out or expose this as a configuration. Thanks for taking the time, much appreciated 🙏🏻

**Comment by bodinsamuel** [comment]
Thanks for pushing this test. 
I just deployed to try out, no luck there still segfaulting only in GKE 😢

**Comment by laverdet** [comment]
Thanks for the comprehensive reproduction. This seems to be caused by musl creating really small stacks [~128kb] which is lower than the v8 default stack size. You can try the fix by installing directly from GitHub. I'm out of travis-ci credits at the moment and am waiting for their customer support to give me more OSS credits to finish the testing process before I push to npm.
