### ISSUE TITLE
V8 Inspector support

### ISSUE THREAD

**Issue by jeromegn** [laverdet/isolated-vm#24]
Any plans to support inspecting isolates via the V8 Inspector API? https://github.com/v8/v8/wiki/Debugging-over-the-V8-Inspector-API

I'm not sure if the right packages are imported by default or if we'd need to add the d8 stuff.

**Comment by jeromegn** [comment]
I played with the basic implementation you made, it's working alright :)

I've been able to do some profiling, look at code, break on exception, debug and such. I haven't been able to inspect values of variables though. Maybe it's just the nature of our service (http requests), but when I try to inspect something, it seems to put the isolate in a weird state and I need to restart it.

Maybe it's missing some of the inspector API implementation? I'm not sure.

**Comment by laverdet** [comment]
Please try again with the change I just pushed.

**Comment by laverdet** [comment]
Also I've added a `transfer` option to ExternalCopy which lets you directly transfer ownership of ArrayBuffers in or out of isolates without a full copy.

**Comment by jeromegn** [comment]
Inspector works great now! I'm going to try to hook into the console in there while it's open.

Concerning the ExternalCopy transfer: true, that's a pretty amazing feature. Our test suite is now failing with it, I'm investigating. I did see a bunch of `dtor` log lines being printed, looks like it's coming from this line: https://github.com/laverdet/isolated-vm/blob/08e8c2a48a217f22a6dba2844a5d4cd3766e3e75/src/external_copy.h

Was that intended or just for debugging purposes?

**Comment by laverdet** [comment]
That's definitely not supposed to be there, good catch. It's gone now~
