### ISSUE TITLE
#<Promise> could not be cloned

### ISSUE THREAD

**Issue by andyrunciman** [laverdet/isolated-vm#240]
We have an issue when a function returns a promise after upgrading to version 4.  Attached is a simplified snippet of code that works on 3.3.10 but is failing on 4.1.0

`
const ivm = require('isolated-vm');
let setup = async function(){
    const isolate = new ivm.Isolate();
    const context = await isolate.createContext();
    const fn = 'async function execute(o) {return o}';
    const compiledFn = await isolate.compileScript(fn);
    await compiledFn.run(context);
    const fnReference = await context.global.get('execute');
    const result = await fnReference.apply(
        undefined,
        [{a:20}],
        { arguments: { copy: true }, result: { promise: true, copy: true } }
      );
    return result;
}

setup().then((result)=>{
    console.log(result);
}).catch((err)=>{
    console.log(err);
});
`

**Comment by laverdet** [comment]
I think you need to change `context.global.get('execute');` to ``context.global.get('execute', { reference: true });` in this case.

**Comment by andyrunciman** [comment]
Thank you - that now works as expected.
