### ISSUE TITLE
Error: Module has not been instantiated

### ISSUE THREAD

**Issue by MichielvdVelde** [laverdet/isolated-vm#244]
I'm sure this is a rookie mistake, but I'm getting nowhere. I'm getting the following error:

```
Error: Module has not been instantiated.
    at run (C:\Users\michi\Google Drive\Development\vm\dist\ivm.js:14:30)
```

My goal is to allow users to write the loop function, which should be called on each tick (not included in the example). The below test code instantiates a module (without dependencies, which are currently out of the scope of my question) and attempts to call its default exported function. Some global context objects will have changed between ticks (not included in example).

Below is my test code, where I attempt to instantiate a module and call its default exported member.

```typescript
import { Isolate } from 'isolated-vm'

const code = `export default function loop() {
  // some code here
}`

async function run() {
  const isolate = new Isolate({  memoryLimit: 128 })
  const context = await isolate.createContext({ inspector: false })

  const module = await isolate.compileModule(code)

  await module.instantiate(context, specifier => {
    throw new Error(`Missing module: ${specifier}`)
  })

  const reference = module.namespace // this generates the error
  const loop = await reference.get('default')
  await loop.apply(null)
}

run()
  .then(() => console.log('ran'))
  .catch((err: any) => console.error(err))
```

I'm finding the documentation a little difficult to interpret, which may be my lack of understanding.

Thanks in advance for any help. Since this is not an issue per say I understand if this issue is closed. I had to try.

**Comment by laverdet** [comment]
You need to invoke `await module.evaluate();`
