### ISSUE TITLE
Code causes "Promise could not be cloned error" on v4.3.2 and not on v3.3.10

### ISSUE THREAD

**Issue by tomershv** [laverdet/isolated-vm#250]
Hi!
Sorry in advance for including a CodePen link instead of a code block, couldn't properly do it in the GitHub UI...

[This code](https://codepen.io/tomer-shvadron/pen/WNjQLbJ) works perfectly when using isolated-vm@3.3.10, but raises the following error on version 4.3.2:
`TypeError: #<Promise> could not be cloned. at (<isolated-vm boundary>)`

**Comment by laverdet** [comment]
Change the earlier line to this:
```js
const greet = await context.global.get('greet', { reference: true })
```

`get` returns a `Callback` instance on functions by default now, as a security precaution. The `apply` you're calling isn't `Reference.prototype.apply`, it's `Function.prototype.apply`
