### ISSUE TITLE
Help regarding `EvalError: Code generation from strings disallowed for this context`

### ISSUE THREAD

**Issue by bergundy** [laverdet/isolated-vm#251]
Hi again,

I have an issue in the Temporal Node SDK that's not strictly related to `isolated-vm`.
In the SDK we need to dynamically eval user code which is bundled using webpack into a startup snapshot - this is done mostly for performance reasons.
The isolate pretends to be a browser in order to get webpack to cooperate, code can be found [here](https://github.com/temporalio/sdk-node/blob/9ba6424b9cc2c17f7b4125bb2324798327c7073f/packages/worker/src/isolate-builder.ts#L71) and [here](https://github.com/temporalio/sdk-node/blob/9ba6424b9cc2c17f7b4125bb2324798327c7073f/packages/workflow/src/worker-interface.ts#L96).
This has been successfully tested using different node versions on both Linux and MacOS.

A while ago @zomble encountered an error when trying to run our basic example where v8 was throwing an error with the message `Code generation from strings disallowed for this context` during the dynamic evaluation step where we call `require` after an isolate has been loaded from a snapshot.

I've tried to reproduce this error in different environments without success.

Today I tried again by setting the [`--disallow-code-generation-from-strings`](https://nodejs.org/api/cli.html#cli_disallow_code_generation_from_strings) CLI option and my process failed in a different way than reported in the issue:
```shellsession
$ node --disallow-code-generation-from-strings lib/worker
EvalError: Code generation from strings disallowed for this context
    at new Function (<anonymous>)
    at compileBoundsSearch (/Users/bergundy/example/node_modules/webpack/lib/util/binarySearchBounds.js:76:17)
    at Object.<anonymous> (/Users/bergundy/example/node_modules/webpack/lib/util/binarySearchBounds.js:81:6)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/bergundy/example/node_modules/webpack/lib/javascript/JavascriptParser.js:13:28)
```

Orignal issue can be found [here](https://github.com/temporalio/sdk-node/issues/139
).

Any ideas?

**Comment by laverdet** [comment]
I'm not sure I understand the issue, it sounds like the --disallow-code-generation-from-strings flag is working as expected. Does the error go away if you omit this flag?

**Comment by bergundy** [comment]
Hi,
@zomble claims he hasn't set this flag (at least not explicitly) and when I set it my process fails at an earlier stage so I thought there might be some other flag that could be causing the error he's seeing.
I also tried to figure out if there's an environment variable that could be causing v8 (via node) to trigger this behavior but couldn't find one.

**Comment by laverdet** [comment]
Are you using snapshots? This might happen with snapshots.

https://github.com/laverdet/isolated-vm/blob/19b3624b962c13526f78949fd8a6391895a9463d/src/isolate/environment.cc#L482

We explicitly opt out of this protection via the above hook but it may not fire for snapshot contexts. I'm not able to actually test it now though (via mobile)

**Comment by laverdet** [comment]
Actually maybe that false should be a true. Let me know if that helps. Weird it hasn't come up yet in practice

**Comment by bergundy** [comment]
I am using snapshots but we run the same sample in CI with node 14 and 16 on both linux and macos so I don't understand why only @zomble is getting this error.
I was not able to reproduce in any environment.

**Comment by bergundy** [comment]
He's using node 14.17.1 installed with nvm on ubuntu.

**Comment by bergundy** [comment]
The error is happening in a context created in an isolate that was created from a snapshot.

**Comment by laverdet** [comment]
I think the issue here is that this person is trying to eval a very large string. The v8 parser has the tendency to kill the entire process if you pass a large string to it, so `isolated-vm` has a limit in place which requires 8x `memoryLimit` in order to pass a string to eval. For example:
```js
const { Isolate } = require('isolated-vm');

async function main() {
  const isolate = new Isolate({ memoryLimit: 128 });
  const context = await isolate.createContext();
  await context.eval('eval("".padStart(16 * 1024 * 1024 + 1))');
}

main().catch(err => console.error(err))
```

Logs: `Error [EvalError]: Code generation from strings disallowed for this context`

**Comment by bergundy** [comment]
Thank you very much @laverdet, that might explain it.
We'll check and post back if that was the cause.

**Comment by bergundy** [comment]
@laverdet I've managed to reproduce this with the temporal node SDK with the help of @vkarpov15.
Posting the findings here for your convenience:

---
Interestingly, the error appears if with the isolate memory limits of:

- 30944.29296875
- 30944
But not with these values:
- 65000 (more than I have on my 16GB MBP)
- 200

**Comment by laverdet** [comment]
I had to revert the error message change because of a spooky v8 bug. The memory limits you posted above aren't very helpful in the absence of a complete program. It's not surprising that different memory limits result in different GC patterns. My theory is still that a large string is being passed to `eval`, but please let me know if you think that isn't the case.

**Comment by bergundy** [comment]
The complete program is pretty complex, I can try and reproduce this with a simpler program but it might take some time.
The `eval`ed string shouldn't be too big though, I believe it's only a single JS file since webpack should have already required all of the dependencies.
```ts
import { Example } from '../interfaces/workflows';
import { greet } from '@activities/greeter';

// A workflow that simply calls an activity
async function main(name: string): Promise<string> {
  return greet(name);
}

// Declare the workflow's type to be checked by the Typescript compiler
export const workflow: Example = { main };
```

I'll try and get more details or a simpler reproduction.

**Comment by laverdet** [comment]
5253edfee4ec00ea825ae82f4930d5a75db536ef may help. It will be on npm soon as 4.3.4

**Comment by bergundy** [comment]
TBH I don't know if this is still an issue now that we're not using snapshots but I'll check if I can repro with the example above.
Thanks!

**Comment by bergundy** [comment]
Confirmed, the latest change fixes the issue, I was not able to reproduce.
