### ISSUE TITLE
TypeError: #<Promise> could not be cloned 

### ISSUE THREAD

**Issue by tstreamDOTh** [laverdet/isolated-vm#257]
Here is a simple piece of JS code I want to execute in isolation - 
```
const ivm = require("isolated-vm");
const fetch = require("node-fetch");
const isolate = new ivm.Isolate({ memoryLimit: 128 });

const context = isolate.createContextSync();

const contextGlobal = context.global;
contextGlobal.setSync("global", contextGlobal.derefInto());

// This makes the global object available in the context as `global`. We use `derefInto()` here
// because otherwise `global` would actually be a Reference{} object in the new isolate.
contextGlobal.setSync("fetch", fetch);
contextGlobal.setSync("console", "2");
contextGlobal.setSync("log", (a) => console.log(a));

const hostile = isolate.compileScriptSync(`
  fetch("https://github.com/").then(res => log(res))
`);

hostile.run(context).catch((err) => console.error(err));


```

Getting error -
```
TypeError: #<Promise> could not be cloned.
    at (<isolated-vm boundary>)
    at <isolated-vm>:2:3
    at (<isolated-vm boundary>)
    at /Users/thiyaga/Desktop/vmtimeout/main.js:36:9

```

Is there something extra needs to be done for supporting promises?

**Comment by vimalraj-a** [comment]
I'm also facing same problem from 4.x.x. But the same code works in 3.3.10.

@laverdet How to wait for promise outside the isolate in 4.x.x?

**Comment by eyudinkov** [comment]
I have the same issue. Could you please tell how to fix it?
@laverdet

**Comment by deadlinecode** [comment]
Same @laverdet

**Comment by laverdet** [comment]
isolated-vm is isolated. You unfortunately can't drop fetch into a new environment and expect it to work. It's like asking how to import node:fs from Safari. You need lots of shims and wrappers.

**Comment by deadlinecode** [comment]
Isn't there a way fetch get's called in the main proc and the result will be copied to the isolated proc?
Also could you share a solution to do this
I still didn't get Promises working right
For example i wan't a method called fetch to be existend inside the isolated vm but as a promise and when the funtion get's called it returns a promise so the isolated proc would have to await the funtion.
And the function will be executed and the result (JSON Body) will be transfered to the isolated process

**Comment by deadlinecode** [comment]
@laverdet why did you close?

**Comment by laverdet** [comment]
`fetch` isn't just a JSON result. It is a huge specification with at least 6 classes that need to be implemented, with dozens of methods and properties in total amongst them. There are examples in the readme about transferring simple payloads, but for fetch you will need a *custom* polyfill (like you have to write it yourself). What if your user tries to fetch, for example, `file:///etc/passwd`? What if they run a local services scan and find your AWS IAM provider? What kind of rate limiting do you want to implement? These are all difficult questions that I am not in a position to answer.

`isolated-vm` uses the [Structured Clone Algorithm](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm) to transfer **data** between isolates. You can transfer a callback, one at a time, using references but you will need a lot of them for arbitrary network code to run.

**Comment by deadlinecode** [comment]
@laverdet i understand that implementing all of that is not possible because of the huge requirements
And im not asking you about what makes calling fetch insecure

All im asking is if you could give me a simple example that enables me to call a async function from the isolated process inside the main process so that the main process makes the actuall fetch call and then just give back simple json data (even as string or idc whatever)
All i care about is using await inside the isolate to call a async function in the main that returns simple data back to the awaiting isolate
Nothing more
Because reading all the docs/readme and all the issues regarding async stuff i wasn't able to make something like this

**Comment by laverdet** [comment]
You can do something like this. Promises are transferable as well but when resolving the promise you don't have an opportunity to set a timeout, so I recommend providing an adapter in this way.

```js
const ivm = require('isolated-vm');
const fs = require('fs');
void async function() {
    const isolate = new ivm.Isolate();
    const context = await isolate.createContext();

    // this is your setup code
    await context.evalClosure(
    `globalThis.readFile = function(file) {
        return new Promise((resolve, reject) => {
            $1.apply(undefined, [ file, new $0.Reference(resolve), new $0.Reference(reject) ], { reference: true });
        });
    }
    globalThis.print = function(message) {
        $2.applySync(undefined, [ message ]);
    }
    `, [
        ivm,
        new ivm.Reference(function(file, resolve, reject) {
            fs.readFile(file, 'utf8', (err, data) => {
                if (err) {
                    reject.apply(undefined, [ err ], { timeout: 1000 }).catch(() => {});
                } else {
                    resolve.apply(undefined, [ data ], { timeout: 1000 }).catch(() => {});
                }
            });
        }),
        new ivm.Reference(function(message) {
            console.log(message);
        }),
    ], { timeout: 1000 });

    // this is the code the user supplies
    await context.evalClosure(
    `void async function() {
        const file = await readFile('test');
        print(file);
    }()`);
}();
```

**Comment by syntaxc** [comment]
Hi @laverdet,
The previous code is now failing using 4.6.

Error:
`TypeError: A non-transferable value was passed`

The error is thrown at this line:
`resolve.apply(undefined, [data], { timeout: 1000 }).catch((error) => {console.log(error)});`

What is the proper way to pass the data back to the iso?
I tried using ivm.Reference and ivm.ExternalCopy, but couldn't get either to work.

Thank you,
C
