### ISSUE TITLE
Snapshot Isolate

### ISSUE THREAD

**Issue by PostCrafter** [laverdet/isolated-vm#26]
I would like to create snapshots of already created isolates.
This can be useful if the isolate contains a state that can be modified with the exposed functions and which should be reused at repeated execution.

**Comment by laverdet** [comment]
I don't think this is going to be possible. The API for creating snapshots in v8 is pretty locked down with lots of restrictions. Basically, the way you go about creating a snapshot is very different from the way you go about using an isolate for general purposes. You can put as many scripts as you want into the snapshot initialization though, that gives you lots of freedom for what goes into your snapshot.

**Comment by PostCrafter** [comment]
That's unfortunate, I'll see if I can get something done with the current snapshot feature, but I don't think this is going to work out the way I want to.

Thanks for the reply anyways.

**Comment by lev-kazakov** [comment]
@laverdet we'd also be grateful for this feature. is there any chance this will be implemented? thx.

**Comment by laverdet** [comment]
@lev-kazakov it's impossible. The snapshot feature is intended to just cache library code.

**Comment by lev-kazakov** [comment]
@laverdet thx, another question if i may:
will it be possible for `ivm.Isolate.createSnapshot()` to receive a third parameter, say `"global"`/`"bindings"`/`"polyfills"` that will receive a set of transferrables/references, and make them available from the global scope of the isolate?
e.g if i do something like this:
```js
const snapshot = ivm.Isolate.createSnapshot([{code: `log('crap')`}], undefined, {
  log: new ivm.Reference(function(...args) {
    console.log(...args);
  }
})
```
then `log` would be available to any script on the `scripts` array.

if this is realistic, i'll open a new issue of course :)

**Comment by laverdet** [comment]
@lev-kazakov that's not possible either because the 3rd parameter in your example would only last as long as the nodejs process is alive. You can save a snapshot to disk and load it into any number of new nodejs processes, and in those processes your log function wouldn't exist anymore.

**Comment by lev-kazakov** [comment]
@laverdet maybe this can be done by providing an additional `polyfills` option to the `options` object in `new ivm.Isolate(options)`.
it will be the responsibility of the user to creating an isolate from snapshot to provide the same polyfills (by name) used to create the snapshot.

**Comment by laverdet** [comment]
I think you're expecting too much from snapshots. Snapshots in v8 are very fragile and based on my experience I believe they are intended to cache only parsed/compiled JS code *not* to cache a "warmed up" application with lots of state on the heap.
