### ISSUE TITLE
Would running on deno provide security benefits?

### ISSUE THREAD

**Issue by getcashier** [laverdet/isolated-vm#261]
Would running on [Deno](https://deno.land/) (potential successor to Node; written by the original author of Node) provide inherent security benefits or synergies?  [Here](https://www.imaginarycloud.com/blog/deno-vs-node/) is a comparison of Node and Deno.  Would any changes be necessary to isolated-vm?

**Comment by laverdet** [comment]
It wouldn't provide any security benefits. I don't know how much work it would take to port over to Deno but I don't think it would be too bad.
