### ISSUE TITLE
Simplest way to spread object into global

### ISSUE THREAD

**Issue by michael-melodyarc** [laverdet/isolated-vm#263]
I'm curious if the below snippet is the simplest way to pass an object while making it's top-level keys accessible as a global.

```js
(async () => {
  const obj = { aa: 11, bb: 22, cc: { dd: [1, 2, 3] } };

  const isolate = new ivm.Isolate({ memoryLimit: 8 });
  const context = await isolate.createContext();

  for (const [k, v] of Object.entries(obj)) {
    await context.global.set(k, v, { copy: true });
  }

  const result = await context.eval("cc.dd[2] * 2");
  console.log(result); // prints 6
})();
```

Is there a simpler way to do this, or is looping through the top-level keys and setting them individually the correct way?  On a related note, is setting the transfer property of `copy: true` just a shorter way than manually calling `new ivm.ExternalCopy(v).copyInto();` on each value before it gets set?

Appreciate any help :)

**Comment by laverdet** [comment]
I would personally do something like this:

```js
await context.evalClosure(
  'Object.entries($0).forEach(([ key, val ]) => globalThis[key] = val)',
  [ { foo: 1, bar: 2 } ],
  { arguments: { copy: true } });
```

That way it's only one invocation to the serializer, and one round trip to the siolate.

`{copy:true}` is basically just a shortcut for the same internal routine that `ExternalCopy` uses. `ExternalCopy` is meant for the case where you want to copy a value into many isolates (and avoid serializing it each time), or the case where you aren't sure if you want to copy into an isolate so you don't want to pay the deserialization and GC cost upfront.

**Comment by michael-melodyarc** [comment]
@laverdet Thanks for the reply.

To clarify, would you suggest tacking on the actual code to execute at the end of that? Or would it be a separate call using the same context?  In other words, is your snippet just replacing the `for...of` loop or also the subsequent `context.eval` call?

**Comment by laverdet** [comment]
That line would replace the for-of loop. One payload is delivered to the isolate and then the loop happens inside the isolate.
