### ISSUE TITLE
Function could not be cloned

### ISSUE THREAD

**Issue by JSH32** [laverdet/isolated-vm#265]
I am trying to pass a function/closure to the main isolate through a method, but it will not clone. I have passed an ivm instance to the script which is returning the function and have tried using ExternalCopy but I get the same error. Reference works but dereferencing it does not get me the actual value. This is the original script below (console is my own implementation).
```js
const internalConsole = internal.getSync("console")
const _ivm = internal.getSync("ivm")

const defineConsoleFunction = (operation) =>
    (...args) => internalConsole.getSync(operation)(...args)

const console = Object.fromEntries(
    ["log", "debug", "info", "warn", "error", "table", "clear", "time", "timeEnd", "count", "assert"]
    .map(
        operation => [operation, defineConsoleFunction(operation)]
    )
)

export default console

export const {
    log, debug, info, warn, error, table, clear, time, timeEnd, count, assert
} = console
```
I have tried mapping all args to ExternalCopy and it gives the same error, if any value that is passed contains a function it just refuses to work.

**Comment by laverdet** [comment]
Yes that's correct, they are different isolates. It would be like asking how to clone a function from nodejs into Internet Explorer.

**Comment by JSH32** [comment]
> Yes that's correct, they are different isolates. It would be like asking how to clone a function from nodejs into Internet Explorer.

Yeah I figured that objects are fine since they are representable data (kinda like JSON) but functions would be isolate specific bytecode
