### ISSUE TITLE
Build fails on Windows 10 in installing

### ISSUE THREAD

**Issue by KaffinPX** [laverdet/isolated-vm#269]
![image](https://user-images.githubusercontent.com/73744616/143503420-5004c66e-9d4d-41c8-bc4c-beffe4f493b1.png)

**Comment by KaffinPX** [comment]
Node 16, node-gyp is latest.

**Comment by LuvbCa** [comment]
are you using windows 10 or 11?

**Comment by LuvbCa** [comment]
Try installing VS Studio 2022 Preview and installing it from the Developer Powershell, also use `npm i node-gyp@latest`, and newest Node Version
