### ISSUE TITLE
Access node's I/O from any Isolate

### ISSUE THREAD

**Issue by legraphista** [laverdet/isolated-vm#27]
Hi! 
I was wandering if there is any possibility to access the file system or make network calls from an Isolate without a stub in the main isolate.

My goal here is to possibly make a `require`-like system that can be used inside any Isolate and load code via it. I tried to share the `require` function of the main isolate, but the only way i could do it was through a stub that requires the module and then passes it as a reference, but in my understanding, that will still execute on the main isolate.

Any guidance will be appreciated 😃

**Comment by laverdet** [comment]
At this time all i/o must be done through stubs back to the main isolate. Though it's definitely a possible feature I could add in the future. Such an API would probably more closely resemble libuv's minimalistic interface, as opposed to node's feature-rich interface.

My advice is to implement this now with stubs back to node's fs library. I don't think the overhead will be that bad.

**Comment by jeromegn** [comment]
It would be practical, but it could potentially break the isolated feature of this project.

I've been using webpack to pre-compile larger JS projects to compile and run them in the in isolated VMs. It's been working great!

**Comment by legraphista** [comment]
Hi @jeromegn! I also tried to use Webpack to bundle everything in a big JS file, but in one way or another, you'll still find a module here and there that requires access to native modules, for example `net`, `dns`, `fs` and so on. I'm currently exploring possibilities to introduce bootstrap code that would make a lightweight require-like function which will call a stub in the main process to access native module functions/properties.

**Comment by jeromegn** [comment]
Ah right. Yes, you'd be pretty much limited to packages that also work in browsers and even then you may need to stub some browser functionalities.

An issue with the require stuff is that it's synchronous, that means you'd have to run your script in a synchronous manner (via `runSync`.) You can't use `apply` or other asynchronous functions within an isolate if you're running it synchronously. It's a huge bummer :( (it also makes a lot of sense.)

It sounds like you'd be able to modify the packages requiring those libraries to fit with isolated-vm. Maybe a whole new category of packages would make sense. There are currently packages for node.js or for the browser (or both,) but for "raw" v8, not so much.

**Comment by legraphista** [comment]
Indeed, you'd need something compatible with pure V8. Even Webpack with the bowser environment assumes the presence of browser functions, like XHR requests.

Regarding running synchronous code, it should only happen when requiring a package and/or using a stub of a native module. Requiring can be cached (just like node does) and calling native packages from an isolate shouldn't have much more of an overhead than just calling from inside the main isolate.

**Comment by PostCrafter** [comment]
Using Bundlers like Webpack seems like a great solution, but this makes us lose the ability to require a dependency from a subsequently loaded script (`require('some-package')`) without having to bundle it again. I'm fine with using a fairly limited amount of packages inside the isolate that do not depend on nodejs core modules. I would still like to be able to use nodejs' `require` functionality or ES2015 `import`s acting like I'm loading multiple modules into the isolate.

**Comment by xc2** [comment]
@legraphista Considering [Worker Threads](https://nodejs.org/docs/latest-v10.x/api/worker_threads.html}

**Comment by ayZagen** [comment]
I would be very glad to see `require` support. module support like [vm2](https://github.com/patriksimek/vm2) does would be such a great  feature. It is the only thing that I think this library lacks.

**Comment by ayZagen** [comment]
@idleman Even if it could be created I believe it should be included in this library because this is a `node` sandbox.

**Comment by idleman** [comment]
I cannot see how this library is a "node sandbox". Most people will just use isolated-vm to run untrusted ECMAScript code, which is totally different than the complete node runtime. The "process" object in node, in my opinion is for example more critical than "require" function. You can bundle every "require" call away, but it is impossible to even console log a single token without process.stdout (console.log is just a function that calls it last time I checked).

Another issue would also be how such implementation should be done, if it is implemented. Its security considerations and its flexibility may suit pure nodejs environments, but making it less obvious for using it for pure ECMAScript environments, making no assumption at all.

But yeah, it is just my 5 cents.

**Comment by jeromegn** [comment]
This is defintely more of a "V8" sandbox. It supports ECMAScript modules (via `import`).

**Comment by laverdet** [comment]
`require` isn't included because there's no "one size fits all" implementation. For example in Screeps they load all user code from MongoDB instead of the filesystem. Making too many assumptions can actually limit functionality. Also because CommonJS isn't part of JS and is quickly being obsoleted.

The goal of `isolated-vm` is to implement all the hard parts for you and then you're on your own for the rest.

**Comment by PostCrafter** [comment]
I don't really see a need for `require` either, especially since `isolated-vm` now supports ES2015 modules  and imports.

**Comment by FTAndy** [comment]
there is no `libev` in `isolated-vm`, no require is fair. it is just a pure JS exec runtime, no heavy stuff.

**Comment by mateuszmazurek** [comment]
> I tried to share the `require` function of the main isolate, but the only way i could do it was through a stub that requires the module and then passes it as a reference

I can't event do it like that 😂 Can you share some snippet?

**Comment by sandipmohod** [comment]
> > I tried to share the `require` function of the main isolate, but the only way i could do it was through a stub that requires the module and then passes it as a reference
> 
> I can't even do it like that 😂 Can you share some snippet?

Did you get some code snippet how to stub require files ?

**Comment by jeremiaswerner** [comment]
I would like to second the previous comment. An example of how to stub require would be really great. My use case is to use `request` module within an isolate. If someone has an example just for that would also be really great.

**Comment by RyanElfman** [comment]
I would also really like to know how to get require stub inside of isolate.

**Comment by laverdet** [comment]
If a full-featured `require` is important to you then you should consider using the alternative [`vm2` ](https://github.com/patriksimek/vm2) module instead of this project.

`isolated-vm` provides a plain old JS execution environment which is *completely* separate from the nodejs isolate. Asking for `require` within `isolated-vm` is like asking how to `require('mongodb')` on AWS from within Internet Explorer.

You need to implement each and every thing from scratch in your new isolate.
