### ISSUE TITLE
Failed to call async function inside ivm

### ISSUE THREAD

**Issue by Y-qwq** [laverdet/isolated-vm#270]
I made some changes based on this https://github.com/laverdet/isolated-vm/issues/166#issue-577381374, I want to run directly inside the vm, but the execution result is not correct, and no "end" and result are output.

![image](https://user-images.githubusercontent.com/43369548/144544251-9fee1337-cf52-4b24-a262-695a8ec0251f.png)

```javascript
const axios = require('axios');
const ivm = require('isolated-vm');
const isolate = new ivm.Isolate({ memoryLimit: 128 });
const context = isolate.createContextSync();

class Logger {
    static methods = [this.log];

    static log(...obj) {
        console.log("log called:");
        console.log(...obj);
    }
}

class AxiosWrapper {
    static methods = [this.get];

    static async get(...args) {
        const result = await axios.get.apply(this, args);
        console.log('fetched')
        return JSON.stringify(result)
    }
}

// Logger.
context.evalClosure(`
  log = function(...obj) {
      $0.applyIgnored(undefined, obj,  { arguments: { copy: true } });
  };
`, Logger.methods, { arguments: { reference: true } });

// Axios.
context.evalClosure(`
  axios = {
      get: function (...args) {
          return $0.apply(undefined, args, { arguments: { copy: true }, result: { promise: true, copy: true } });
      }
  };
`, AxiosWrapper.methods, { arguments: { reference: true } });

context.eval(`
    async function fetch() {
        log('start')
        const result = await axios.get('https://jsonplaceholder.typicode.com/posts', {params: {test: 'test'}})
        log('end')
        log(result)
    }
    fetch()
`)


```

**Comment by laverdet** [comment]
You're returning an abandoned promise from eval. You need to add `{ promise: true }` to the eval call as well.

**Comment by Y-qwq** [comment]
Thanks, although`promise: true` is not what I want, but it made me find my mistake, I can't `JSON.stringify(result)`!

**Comment by tagchat** [comment]
Hi, guys!

I have the same problem! I can't access result values in function. Example based on #270

`context.eval(`
    async function fetch() {
        log('start')
        const result = await axios.get('https://jsonplaceholder.typicode.com/posts', {params: {test: 'test'}})
        const firstElement = result.data[0];
        .
        .
        .
    }
    fetch()
`)`

Obviously that this don't works! Someone can help me about this? The result returns only Reference{ } if delete `copy: true`, and with `copy: true`, returns nothing!
