### ISSUE TITLE
Error building with electron-rebuild

### ISSUE THREAD

**Issue by LuvbCa** [laverdet/isolated-vm#272]
```
external_copy.obj : error LNK2019: Verweis auf nicht aufgel÷stes externes Symbol ""__declspec(dllim
port) public: static class v8::Local<class v8::ArrayBuffer> __cdecl v8::ArrayBuffer::New(class v8:: 
Isolate *,class std::shared_ptr<class v8::BackingStore>)" (__imp_?New@ArrayBuffer@v8@@SA?AV?$Local@ 
VArrayBuffer@v8@@@2@PEAVIsolate@2@V?$shared_ptr@VBackingStore@v8@@@std@@@Z)" in Funktion ""public:  
virtual class v8::Local<class v8::Value> __cdecl ivm::ExternalCopyArrayBuffer::CopyInto(bool)" (?Co 
pyInto@ExternalCopyArrayBuffer@ivm@@UEAA?AV?$Local@VValue@v8@@@v8@@_N@Z)" 
```

tried compiling with differnet node versions without electron rebuild without any succes because electron 16 uses NODE_MODULE_VERSION 99 but the node uses 93 till node 16 and node 17 uses 102. Also forking the electron porcces as node process also didn't work so im really out of options here? are there any alternatives to this library or is this issue fixable?

**Comment by laverdet** [comment]
I'm able to get isolated-vm compiled for electron with no issues with the following:
```
cd node_modules/isolated-vm
HOME=~/.electron-gyp node-gyp rebuild --target=16.0.4 --dist-url=https://electronjs.org/headers
```

**Comment by LuvbCa** [comment]
still not working, i would think this is a Windows 10/11 bug im digging into it but it seems like MSBuild.exe can't resolve dllimports or something like that. Any advice is appreciated 💯

**Comment by alexsunday** [comment]
> 

not working on win10 && visual studio 2015/2019  

![picture.](https://user-images.githubusercontent.com/1531092/147866853-23da4074-34e2-4ca8-9b6b-9ac03775ee1d.png)

**Comment by alexsunday** [comment]
ubuntu linux, g++ 9.x, compile(electron-rebuild) and run succeed.

![图片](https://user-images.githubusercontent.com/1531092/147871044-bed611ba-96b3-4b96-a83b-258da9231624.png)


> I'm able to get isolated-vm compiled for electron with no issues with the following:
> 
> ```
> cd node_modules/isolated-vm
> HOME=~/.electron-gyp node-gyp rebuild --target=16.0.4 --dist-url=https://electronjs.org/headers
> ```

**Comment by pigalot** [comment]
This error still happens on windows, is there no resolution to this?
using version 4.3.6 and electron 16.0.7

**Comment by LuvbCa** [comment]
Seems like a compiler problem, i don't know excatly tho. Maybe try switching your c++ compiler to g++ and away from clang :)

**Comment by pigalot** [comment]
if you know of a way to make node-gyp not use msbuild on windows (i have yet to find one) that might work, however it works for building it normally and only doesn't when you try to build for electron.

**Comment by LuvbCa** [comment]
The error probably happens because msbuild and the electron headers conflict in some way or another. But for the node-gyp part i have no clue...
