### ISSUE TITLE
Create Reference/Callback from code running inside Context

### ISSUE THREAD

**Issue by Saghetti0** [laverdet/isolated-vm#278]
I'm wondering how to create a reference from code running inside of a Context. I'm implementing a `setTimeout` function, and I want to be able to pass a reference to my function defined outside of the context.

Here's what I want to do (from inside the context):
```js
setTimeout(Callback(() => {
  log("hello from setTimeout!");
}), 1000);
```

My problem is that I can't add `Callback` to the context like this: `context.global.setSync("Callback", ivm.Callback);`, as it can't copy the class. I figured out that I can pass in the entire library to the context like this: `context.global.setSync("ivm", ivm);`, but this allows access to a lot of functionality that I don't want it to access. Is there any way to provide access to only `Callback` and `Refernece`?

**Comment by laverdet** [comment]
I recommend passing `ivm` into evalClosure in this case.

```js
const ivm = require('isolated-vm');
const isolate = new ivm.Isolate;
const context = isolate.createContextSync();
context.evalClosureSync(`
globalThis.log = $1
globalThis.setTimeout = (fn, ...rest) => $2(new $0.Reference(fn), ...rest);
`,
[
	ivm,
	(...args) => console.log(...args),
	(fn, timeout) => void setTimeout(() => fn.applySync(), timeout),
]);

context.evalSync('setTimeout(() => log("wow"), 100)');
```
