### ISSUE TITLE
ivm somehow changes between context

### ISSUE THREAD

**Issue by jeromegn** [laverdet/isolated-vm#28]
Hey Marcel,

I found this weird behaviour where contexts will have a different `ivm` (initially set globally) in subsequent runs.

I'm not sure how to explain this better, I have a test case:

```javascript
const ivm = require('isolated-vm');

const iso = new ivm.Isolate()
const script = `function test(arg1){
  return arg1 instanceof ivm.Reference
}`

async function makeContext() {
  const ctx = await iso.createContext()

  const g = await ctx.globalReference()
  await g.set("ivm", ivm)

  const s = await iso.compileScript(script)
  await s.run(ctx)

  const fn = await g.get("test")
  console.log(await fn.apply(null, [new ivm.Reference(function () { })]))
}

makeContext()
makeContext()
```

This outputs:

```
true
false
```

Am I doing something wrong? I would expect the returned value to be true all the time.

**Comment by laverdet** [comment]
This was because I was caching the transferred `ivm` object per isolate, but that gives you weird behavior with more than one context. Now each context gets their own copy of the `ivm` object with correct prototypes.

**Comment by jeromegn** [comment]
Awesome, that does it!

**Comment by jeromegn** [comment]
Can you cut a release that includes this fix?

We're beta-launching our product and would rather not have to point to a repository for the isolated-vm package.

**Comment by laverdet** [comment]
0.1.5 is in npm for you
