### ISSUE TITLE
Install failed on Windows

### ISSUE THREAD

**Issue by W--7V** [laverdet/isolated-vm#282]
![image](https://user-images.githubusercontent.com/9429451/148730772-837f2f35-2169-4502-8e9c-56d9b7315496.png)
Is this a known issue? I didn't find duplicate issue.

**Comment by laverdet** [comment]
Never seen that one before. My guess is that it's an internet or proxy configuration issue. Googling for "node-gyp TAR_BAD_ARCHIVE" provides more information. Some users recommend deleting your npm cache and trying again.
