### ISSUE TITLE
Calling fetch == API error TypeError: #<Promise> could not be cloned.

### ISSUE THREAD

**Issue by jtewright** [laverdet/isolated-vm#284]
Hello,

Fantastic module :)

Could I ask for your help in enabling the evaluated code to make http requests via fetch pease?

Here is how I am setting it up:
```
import ivm from 'isolated-vm'

export async function TestCode(code) {

    const isolate = new ivm.Isolate({ memoryLimit: 128 });
    const context = isolate.createContextSync();
    const ctxGlobal = context.global;

    ctxGlobal.setSync('global', ctxGlobal.derefInto());
    
    ctxGlobal.setSync('fetch', function(...args) {
        return fetch(...args);
    });

    const result = context.evalSync(code);

    return result;
    
}
```

Here's the code I am running through `evalSync` (with some redactions):
```
async function call() {
  const response = await fetch('http://api.weatherapi.com/v1/current.json?key={blah blah params'};
  const data = await response.json();
  const blah = data.something;
  return blah;
}
call();
```

I keep getting the error: `API error TypeError: #<Promise> could not be cloned.`

I've read through the other relevant Issues and tried adding `{ promise: true }` as a transfer option to various functions in my implementation. It sometimes changes the stack trace, but not the ultimate error.

Where am I going wrong?

**Comment by jtewright** [comment]
Update: I think the real problem is transferring the response object around the vm... because it has nested promises / functions. I'm trying to allow people to write vanilla ES6 so the goal is for fetch() to return the response promise... Doesn't seem possible without (re)building it in a transferrable form, afaik.

**Comment by laverdet** [comment]
Yes you'll have to do some heavy lifting to get this working. The two environments are *isolated*. One might also ask the question "how do I call `fetch` on the user's browser but from nodejs".
