### ISSUE TITLE
Using isolates in Electron renderer processes

### ISSUE THREAD

**Issue by BasBuur** [laverdet/isolated-vm#285]
I'm working on an application where I need to create and manage isolates from within the Electron's renderer process.

Creating isolates in main.js (the main process) seems fine, but when creating them in one of the app's JS files with nodeIntegration set to true, the entire Electron process crashes. No crash log unfortunately, it just dies. What can I do to investigate / debug this issue?

**Comment by laverdet** [comment]
Unfortunately due to architectural consequences of v8's design you won't be able to use isolated-vm in the renderer process. It's the same with worker_threads.
