### ISSUE TITLE
What is the best / easiest way to return an object containing functions as a return value?

### ISSUE THREAD

**Issue by BasBuur** [laverdet/isolated-vm#287]
Imagine I have a function like this on the main isolate that I want to call from other isolates:
```js
function getDocument(documentName) {
    return {
        content: getDocumentContents(documentName), // Just a string
        delete() {
            fs.deleteSync(somePath + '/' + documentName); // Example
        }
    }
}
```

Now from an isolate I want to be able to run
```js
let myDocument = Documents.get('myAwesomeDocument.txt');
myDocument.delete();
```
If I understand it correctly we cannot transfer objects containing functions. Does that mean that such return values are simply not possible with isolated vms?

**Comment by laverdet** [comment]
Nope, not possible! You might as well be asking how to return such an object from nodejs to a client running Internet Explorer. These are two different environments that are *isolated* from each other. You need to do the RPC stuff manually.
