### ISSUE TITLE
Access / evaluate on instantiated module contexts

### ISSUE THREAD

**Issue by BasBuur** [laverdet/isolated-vm#288]
Say I have a simple `add` module instantiated. Now I want to have a context that I can evaluate expressions in.

Say this is a 'module' that uses my `add` module. This module compiles fine by the way:
```js
import add from './add';

let a = add(5, 6);
let b = 'c';

function a() {
    ......
}

function b() {
    .......
}
```

Now from the Node process I want to be able to get the value of `a` with `getSync('a')` and use other functions like `evalSync("c()")`, `evalSync("b = 'd'")` on this context.  I got all of this to work with regular scripts and then getting the value from the context, but here it does not seem to work that way. Is this possible with this library? Or can isolated-vm modules only export things for use in other modules?

**Comment by laverdet** [comment]
Sorry, your question is really unclear so I'm not sure how to help you. The sample code just doesn't make any sense. Please reopen with more information or a sample application if you'd like.
