### ISSUE TITLE
Assertion failed for null pointer

### ISSUE THREAD

**Issue by jeromegn** [laverdet/isolated-vm#29]
From time to time, I get

```
node: ../src/platform_delegate.h:45: virtual void ivm::PlatformDelegate::CallOnForegroundThread(v8::Isolate*, v8::Task*): Assertion `s_isolate != nullptr' failed.
```

While running our specs on travis. I have not seen that locally. It's not happening consistently on travis either (we have some succeeding builds with the same code.)

It seems to happen at the same spot every time. Which is strange. It's not a particularly special scenario.

I'm sure this is due to some weird logic in our code, like a race condition, but I would expect isolated-vm to fail in a catchable way. Now it just crashes the process.

You can see relevant logs here: https://travis-ci.org/superfly/fly/builds/333482078 you can run the https://github.com/superfly/fly specs with `npm test` if you want to try and reproduce it.

**Comment by jeromegn** [comment]
I've been able to replicate this locally. It happens when the tests run fast enough, all the printing to stdout was slowing it down on my computer, so I ran them in a smaller terminal window and was able to get 2-4x performance boost.

It tends to happen always at the same point.

It happens when creating the context via `Isolate.prototype.createContext` (same with the synchronous version.)

I'm not entirely sure, but it may happen when a lot of contexts are created very fast? If that were the case, I would've expected a setTimeout to fix it, but it didn't.

I've greatly simplified the way `@fly/fly` creates and manages isolates/context. It's now very naive, I have 1 big isolate, for every request it creates a new context and sets it up. I thought that would be a fool-proof way of making it work, but it created this new problem.

**Comment by laverdet** [comment]
Strange, I've tried it on two different computers and on each computer it failed the very first time but not after that.

**Comment by jeromegn** [comment]
It happens sporadically.

I can take 10-20 runs until I can replicate it locally. It tends to happen only when the tests run very fast (1-2s total.)

I can't replicate in a simple test case, it seems to happen when there's a bunch of things happening in the isolate/contexts.

**Comment by laverdet** [comment]
Can you try this again on master? I just pushed a huge refactor I've been working on. I haven't been able to reproduce this with the current master.

**Comment by laverdet** [comment]
Also this is unrelated to this issue but you may be interested in the `.release()` method I added to context handles.

**Comment by jeromegn** [comment]
That's great! I will try to replicate it and will report in a few days. It's a hard one to replicate.

With both that fix and the `Context#release`, I think this should get us where we want :)

**Comment by jeromegn** [comment]
I haven't been able to reproduce the issue I was originally having. I'll re-open if I do!
