### ISSUE TITLE
Making built-in modules available in ivm

### ISSUE THREAD

**Issue by mkherlakian** [laverdet/isolated-vm#290]
I was wondering if there is an easy way to make some of the node built-in modules available in an ivm context...

Our use case is that we allow our users to execute arbitrary code on our platform that basically transforms http requests. We'd like for instance that our users be able to either `const crypto = require('crypto')`, or be able to have crypto in scope in the isolate that runs their code... I believe that this may be achievable with `Module` but I'm not sure.

the ultimate goal in this case is to allow users to pack libraries like https://github.com/dvsekhvalnov/jose-jwt and be able to run them. Jose relies on crypto to run…

is there any way to make this work?

**Comment by laverdet** [comment]
You have to make a shim

**Comment by laverdet** [comment]
`crypto` is an easy one because it can be polyfilled without a shim. Just use `crypto-browserify` and build your library with webpack or esbuild.

**Comment by mkherlakian** [comment]
Ah, yes indeed good idea! Thanks for the reply and the help!
