### ISSUE TITLE
Will Isolated VM be accepted by Google play store and work with Nodejs for Mobile

### ISSUE THREAD

**Issue by squidis** [laverdet/isolated-vm#295]
Hi, I've been searching you repo and couldn't find an answer.

Have you any experience of whether Isolated VM would work with Node JS for Mobile (https://github.com/JaneaSystems/nodejs-mobile) or whether user generated code code ran through IsolatedVM would be accepted by Google play store as they have this rule:

> An app distributed via Google Play may not modify, replace, or update itself using any method other than Google Play's update mechanism. Likewise, an app may not download executable code (e.g., dex, JAR, .so files) from a source other than Google Play. This restriction does not apply to code that runs in a virtual machine or an interpreter where either provides indirect access to Android APIs (such as JavaScript in a webview or browser). 
https://support.google.com/googleplay/android-developer/answer/9888379?hl=en

Many thanks

**Comment by laverdet** [comment]
Probably not

**Comment by squidis** [comment]
Oh right why do you say that?

**Comment by laverdet** [comment]
Because it's a shared library with very specific hooks into libv8 and usually that doesn't work on weird projects like nodejs-mobile.

**Comment by laverdet** [comment]
I mean no one is stopping you from trying. Give it a shot.
