### ISSUE TITLE
Publishing Prebuild binaries

### ISSUE THREAD

**Issue by kiddkai** [laverdet/isolated-vm#297]
Hi @laverdet !

Thanks again for this great library. I am wondering if it's possible to publish prebuilt binaries that are similar to https://github.com/sass/node-sass/releases for easier installation for different platforms/arch?

I am happy to help if any work need to be done. I saw that currently this repo is using travis to build. And the pricing for the free tier  on travis doesn't seem to be friendly for the prebuild binaries. 

If publishing binaries becomes an option, this repo may need to switch to something like `github action` or `appveyor`

**Comment by laverdet** [comment]
No can do #201

**Comment by orgads** [comment]
Created a prebuilt release. Until #366 is accepted, you can install it using:

```bash
npm install isolated-vm-prebuilt
```
