### ISSUE TITLE
Assertion failed: (try_catch.HasCaught())

### ISSUE THREAD

**Issue by jeromegn** [laverdet/isolated-vm#30]
Another assertion failure.

```
Assertion failed: (try_catch.HasCaught()), function operator(), file ../src/shareable_isolate.h, line 776.
```

I was able to get there running this code:

```javascript
const ivm = require('isolated-vm')

const iso = new ivm.Isolate();

(async function () {
  let i = 0
  while (true) {
    console.log("iteration", i)
    await iso.createContext()
    i++
  }
})()
```

Wouldn't it be better to not use those assertions? They appear to crash the process entirely. Couldn't they just throw some errors that could be caught in node?

**Comment by laverdet** [comment]
The assert() calls are important, if they are ignored then the process enters the territory of "undefined behavior" which at best means it will segfault soon anyway.

**Comment by jeromegn** [comment]
Oh I see. Makes sense!

So the fix is at a different level. I imagine these issues are avoidable some way.

I seem to be hitting that assertion exception after a consistent number of iterations (a bit under 800, but I expect that's different on another computer.)

I understand spamming contexts like that is not a good idea, I was trying to replicate another issue (#29) when I stumbled on this one.
