### ISSUE TITLE
How to create class instance from module, loaded to isolated-vm? 

### ISSUE THREAD

**Issue by StNekroman** [laverdet/isolated-vm#312]
I have code
```
export default class SampleSeedGame {
    initialize() {
        console.log("onInit");
        return Promise.resolve();
    }
    destroy() {
        console.log("onDestroy");
        return Promise.resolve();
    }
}
console.log("1");
```

I load it with
```
       const isolate = new ivm.Isolate({
            memoryLimit: this.instanceMemoryLimit
        });

        const context = isolate.createContextSync();
        const jail = context.global;
        jail.setSync('global', jail.derefInto());

        jail.setSync("console", new ivm.ExternalCopy({}).copyInto());
        const vmConsole = jail.getSync("console");
        vmConsole.setSync("log", (...args : any[]) => {
            console.log(...args);
        });
        vmConsole.setSync("error", (...args : any[]) => {
            console.error(...args);
        });

        const content = /* content */;
        const module = isolate.compileModuleSync(content.toString());

        module.instantiateSync(context, function noModule(specifier) {
            throw new Error(`Cannot import module '${specifier}'`);
        });

        module.evaluateSync();

        const clazz2  = module.namespace.getSync("SampleSeedGame",  {
            reference: true
        }); // here I receive Reference to SampleSeedGame
```

How to create new instance of SampleSeedGame (inside that isolated jail) and communicate with it, invoking methods?

**Comment by laverdet** [comment]
You'd have to use `evalClosure` for this, since there is no `new` feature on `Reference`. Something like: `context.evalClosure('new $0()', [ clazz2 ], { result: { reference: true } })`

**Comment by StNekroman** [comment]
@laverdet I already tried different ways to achieve this pretty simple task.
On
`context.evalClosureSync('new $0()', [ clazz2 ], { result: { reference: true } })`
I receive 
`$0 is not a constructor`

Additionally, I tried to create another module, which will import first and create object from class internally, returning me ref.
```
const proxyModule = isolate.compileModuleSync(`
            import gameModule from "GamePluginEntryPoint";

            export function instantiateClass(className) {
                console.log(gameModule);
                return new gameModule();
            }
        `);

        proxyModule.instantiateSync(context, (specifier) => {
            if (specifier === "GamePluginEntryPoint") {
                return module;
            }
            throw new Error(`Cannot import module '${specifier}'`);
        });

        const ev = proxyModule.evaluateSync({
            reference: true
        });

        
        const ggg = proxyModule.namespace.getSync("instantiateClass", {
            reference: true
        });
        const hhh  = ggg.applySync(undefined, [gameDefinition.entryPointClass]);*/
```

That gives me:

```TypeError: class SampleSeedGame {
    initialize() {
        console.log("onInit");
        return Promise.resolve();
...<omitted>...
} could not be cloned.```

**Comment by StNekroman** [comment]
Addition: `could not be cloned` comes from console.log().
So, without log, with help of additional module and internal VM code I'm able to get the ref. At least, at first look work.
But normal solution is wanted.

**Comment by laverdet** [comment]
Sorry you'd probably need: `context.evalClosureSync('new $0()', [ clazz2.derefInto() ], { result: { reference: true } })`

Your second example is a partial program that has a syntax error and missing declarations (module, gameDefinition) so I'm unable to help you with it.

**Comment by StNekroman** [comment]
`context.evalClosureSync('return typeof $0', [clazz.derefInto()], {result: {reference: false}})`
=> 'undefined'
`context.evalClosureSync('return typeof $0', [clazz], {result: {reference: false}})`
=> 'object'

So I assume, that I don't need .derefInto()

`context.evalClosureSync('return new $0()', [clazz], {result: {reference: true}})`
=> TypeError TypeError: $0 is not a constructor

I even tried:
```context.evalClosureSync('return (function (arg) {return new arg()})($0)', [clazz], {arguments: {reference: true}, result: {reference: true}})```
Gives `arg is not a constructor`
Just doesn't want to invoke `new` on argument.

Event this:
```
context.evalClosureSync('return (function (arg) {return typeof new arg()})(String)', [clazz], {arguments: {reference: true}, result: {reference: false}})
'object'
context.evalClosureSync('return (function (arg) {return typeof new arg()})($0)', [clazz], {arguments: {reference: true}, result: {reference: false}})
Uncaught TypeError TypeError: arg is not a constructor
    at eval (repl:1:9)
```
In first line I receive typeof = object.
In second (passing $0) = error

**Comment by StNekroman** [comment]
New input:

`module.namespace.getSync(gameDefinition.entryPointClass, {reference: true});`
Reference, where type = 'undefined'

**Comment by StNekroman** [comment]
Ok, it was surprise for me, that get/getSync always return reference if options have reference=true, despite nothing was found.
So wrapper around "undefined" is returned.
So I managed to retrieve ref to created object using next code:
```
        const module = isolate.compileModuleSync(content.toString());

        module.instantiateSync(context, function noModule(specifier) {
            throw new Error(`Cannot import module '${specifier}'`);
        });

        module.evaluateSync();

        const clazz = module.namespace.getSync("default", {
            reference: true
        });

        const obj = context.evalClosureSync('return new $0()', [ clazz.derefInto() ], { result: { reference: true } });
```

Note word "default" - I can access it only by that - module.namespace.getSync("default"
Just `SampleSeedGame` doesn't work. While isn't a big problem for me as soon as I need only one thing from module.
But would be good to understand why "SampleSeedGame" isn't exposed to namespaces.

**Comment by StNekroman** [comment]
Now I hit another problem:
`context.evalClosureSync('return $0.initialize()', [ obj.derefInto() ], { result: { reference: true } });`
this works fine - so method "initialize" definitely exists and event calls console.log internally, just as planned.

But
```
obj.getSync("initialize", {
            reference: true
        });
```
returns just a Reference around "undefined" - like nothing found.
Any thoughts? @laverdet

**Comment by laverdet** [comment]
This is just how javascript works, it has nothing to do with isolated-vm. If you want to export this class by its name then you would omit the "default" keyword: `export class SampleSeedGame { ... }`. MDN is a good resource if you want to learn more about modules https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules

About `obj.getSync("initialize",` it's because this is an inherited property. Look for the documentation on `unsafeInherit`.
