### ISSUE TITLE
Script execution does not timeout when waiting for promises

### ISSUE THREAD

**Issue by ElMatella** [laverdet/isolated-vm#318]
Hi, thank you very much for this amazing piece of software...

I have issues regarding the `timeout` option when using Promises into isolates.

The problem only happen if I wait for a promise somewhere. I feel I'm missing something regarding basic functionalities, I'm sorry if it looks trivial to you.

On the following example, the timeout error is not triggered. I don't understand why because neither the main thread nor the isolated vm seem to be blocked.

What am I doing wrong?

```js
const ivm = require('isolated-vm')

const minimalReproduction = async () => {
  const isolate = new ivm.Isolate()

  const context = await isolate.createContext()

  const script = await isolate.compileScript(`
    async function main () {
      await new Promise(resolve => null)
    }
  `)

  await script.run(context)

  const mainFn = await context.global.get('main', {
    reference: true
  })

  await mainFn.apply(undefined, [], {
    result: {
      promise: true
    },
    timeout: 1000
  })
}

minimalReproduction().then(resolved => {
  console.log('promise resolved')
}).catch(error => {
  console.error(error)
})

setInterval(() => {
  console.log('main thread not locked', new Date().getTime())
}, 1000)
```

On the other hand, if I don't call any function from the main thread from my isolate, I get a normal timeout error on an infinite loop. The following code triggers the timeout normally:

```js
const ivm = require('isolated-vm')

const minimalReproduction = async () => {
  const isolate = new ivm.Isolate()

  const context = await isolate.createContext()

  const script = await isolate.compileScript(`
    async function main () {
      let i = 0
      while (true) {
        i++ 
      }
    }
  `)

  await script.run(context)

  const mainFn = await context.global.get('main', {
    reference: true
  })

  await mainFn.apply(undefined, [], {
    result: {
      promise: true
    },
    timeout: 1000
  })
}

minimalReproduction().then(resolved => {
  console.log('promise resolved')
}).catch(error => {
  console.error(error)
})

setInterval(() => {
  console.log('main thread', new Date().getTime())
}, 1000)
```

However, if I set a new infinite loop into the Promise function, the timeout gets thrown again. I feel like the isolate clock needs to compute something in order to advance, I just don't have an idea of how things work:
```js
const script = await isolate.compileScript(`
  async function main () {
    while (true) {
      await new Promise(resolve => {
        while (true) {
          
        }
        resolve()
      })
    }
  }
`)
```

As a workaround, I could dispose the `isolate` like this. Do you think it's a bad idea?

```js
const timeout = setTimeout(() => {
  console.log('The function should have resolved by now.')
  isolate.dispose()
}, 1000)

await mainFn.apply(undefined, [], {
  result: {
    promise: true
  },
  timeout: 1000
})

clearTimeout(timeout)
isolate.dispose()
```
Here is [my original issue](https://gist.github.com/ElMatella/16a6b2d3284514e035c67b4bcff74a84) before limiting it to a smaller problem. Sorry for the inconvenience if you read it before.

**Comment by laverdet** [comment]
The timeout in this case only applies to actual execution time, not idle time. If we add a log above the mainFn.apply:
```js
  setInterval(async () => {
    console.log(await context.eval('"isolate is responsive"'));
  }, 1000);
  await mainFn.apply(undefined, [], {
```

We can see that the inner isolate is idle and still accepting requests. There's no way to verify that the awaited promise has been abandoned. I agree that this behavior is tricky.

I might suggest using a trusted context to apply a timeout on the promise results. Something like this:

```js
const ivm = require('isolated-vm')

const minimalReproduction = async () => {
  const isolate = new ivm.Isolate()
  
  const context = await isolate.createContext()
  const trustedContext = await isolate.createContext();
  trustedContext.global.set('ivm', ivm);
  trustedContext.global.set('setTimeout', (fn, timer) => void setTimeout(() => fn.apply(), timer));
  
  const script = await isolate.compileScript(`
    async function main () {
      await new Promise(resolve => null)
    }
  `)
  
  await script.run(context)
  
  const mainFn = await context.global.get('main', {
    reference: true
  })
  
  const promise = await mainFn.apply(undefined, [], {
    result: {
      reference: true
    },
    timeout: 1000
  });
  await trustedContext.evalClosure(
    'Promise.race([ $0, new Promise((resolve, reject) => setTimeout(new ivm.Reference(() => reject(new Error("Timed out"))), 1000)) ])',
    [ promise.derefInto() ],
    { result: { promise: true } });
}

minimalReproduction().then(resolved => {
  console.log('promise resolved')
}).catch(error => {
  console.error(error)
})

setInterval(() => {
  console.log('main thread not locked', new Date().getTime())
}, 1000)
```

**Comment by ElMatella** [comment]
Thank you very much for taking the time. This seems indeed a way better solution for me, as I can reuse the isolate behind if I'm not wrong. 
Have a very nice day.

**Comment by benben77** [comment]
@laverdet Hi, in this way, it only rejects the Promise.race and returns from `minimalReproduction`, but the code in `script` still runs there. Is there a way to `kill` the running script ?

**Comment by laverdet** [comment]
Sure, you can *not* invoke the callback from within `setTimeout`. In the example above the developer is invoking a function which belongs to the isolate and then is surprised when that function runs.
