### ISSUE TITLE
Disable parts of JS functionality inside isolate

### ISSUE THREAD

**Issue by bfelbo** [laverdet/isolated-vm#323]
Hi, thanks for a great library! I was wondering if there's a way to disable parts of the underlying execution environment that the code is running in. For instance, we'd like to disable any JS functionality related to Promises. If any code would try to use e.g. `Promise.all`, `async` or `await`, the code should just fail with a syntax error or similar. Would it be possible to do this inside isolated-vm?

Even if it's not supported by this library, any pointers on how to do this would be really appreciated!

**Comment by idleman** [comment]
My 2 cents here: You could use acorn/esprima to parse the JS code and check if the code uses Promises, async functions or not. You can also execute "globalThis.Promise = null;" and similar in the isolate. It will not be bulletproof: (new Function('return (async () => 1)()'))() will break it, but cannot see how it should be a security issue even it it does. All micro tasks are managed.

**Comment by bfelbo** [comment]
After reading more and reflecting on this, this seems to be outside of the scope of this project. Since isolated-vm just embeds the V8 engine, this would have be done by V8 itself (or using a more sideways approach like suggested by @idleman). So I'm closing this :)
