### ISSUE TITLE
[Question] Custom STDOUT

### ISSUE THREAD

**Issue by DiaxManPl** [laverdet/isolated-vm#325]
Hi! I have a question. When `console.log` is executed in isolated runtime, it's still printed to the main thread. Can I somehow pass custom stdout?

**Comment by laverdet** [comment]
I don't think this is true.

```js
const ivm = require('isolated-vm')

const isolate = new ivm.Isolate()
const context = isolate.createContextSync()
console.log(context.evalSync('console.log(1), 2'));
```

This logs "2", it doesn't log "1", "2"

**Comment by DiaxManPl** [comment]
Oh, sorry, it's true. My bad.
