### ISSUE TITLE
ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by ppedziwiatr** [laverdet/isolated-vm#329]
Hey,

the untrusted code that I'm trying to run inside the isolated-vm does sth. like this
```js
if (import_tweetnacl.sign.detached.verify(
          new Uint8Array(Buffer.from(JSON.stringify(_data))),
          new Uint8Array(fromHexString(signature)),
          new Uint8Array(unwrapDER(fromHexString(caller), ED25519_OID).buffer)
        )) {
          signer = caller;
        } else {
          throw new ContractError(`The wrong signature`);
        }
```

It ends up with error:
```
 'ReferenceError: Buffer is not defined\n' +
    '    at validate (<isolated-vm>:30475:9)\n' +
    '    at add3 (<isolated-vm>:30738:22)\n' +
    '    at handle (<isolated-vm>:31104:22)\n' +
    '    at async handleWrapper (<isolated-vm>:31171:16)'
```

Question - how can I make the `Buffer` available for the code running inside the isolated-vm?

**Comment by ppedziwiatr** [comment]
Ok, so what I've did as a workaround is:
```js
sandbox.setSync('__host__buffer_from', function (...args) {
    return Buffer.from(args);
  });
```

and then `context.evalSync`:
```
const Buffer = {
    from: __host__buffer_from
  }
```

before the main, untrusted code that I'm trying to run.

But that's probably dumb?

**Comment by laverdet** [comment]
You need to polyfill it inside the isolate https://www.npmjs.com/package/buffer

**Comment by jakedaleweb** [comment]
@laverdet are you able to elaborate on your comment here? Sorry I've tried following the documentation to have the linked buffer lib available but I'm quite lost. An example or pointer to the correct classes/methods to look at would be great 🙏
