### ISSUE TITLE
Manually stop running (and read reference)

### ISSUE THREAD

**Issue by akaustel** [laverdet/isolated-vm#340]
It is possible to manually stop a running script, and then before disposing reading out a value from the context?

I'm running user provided code, and sometimes the code is essentially `while(true)`. I'd like to find out where it happens, and would like to detect this with a watchdog timer on the outside. When the timeout fires, I'd like to stop running the script and read a state variable which was set before running the user provided code, to provide debug information.

I can't run every user provided function separately with a script timeout, as it resulted in poor performance, as it takes some 2-3 milliseconds for a round-trip into the isolate. I'm trying to get ~100-200k  functions evaluations per second, and that simply did not work out.

*Edit: One possibility would also be to continue running after timeout, if that would be possible.*

**Comment by laverdet** [comment]
It is theoretically possible with the v8 API but since the runtime will be in an unpredictable state I made the decision to simplify the process and dispose the Isolate on timeout.

**Comment by akaustel** [comment]
Thanks for the input, I'll have to see if I can figure out an alternative solution. I'll check back here if I solve the issue.

**Comment by akaustel** [comment]
> It is theoretically possible with the v8 API but since the runtime will be in an unpredictable state I made the decision to simplify the process and dispose the Isolate on timeout.

Just closing this as I assume this is not currently subject to change.
