### ISSUE TITLE
Serialize the state of the isolate for snapshots

### ISSUE THREAD

**Issue by mustafaakin** [laverdet/isolated-vm#343]
I've read it in several places, but it seems like not possible, just need to confirm. My use case would be to run a number of scripts dynamically (from user), and save/serialize the state completely to be cloned or used in a different machine. Is it possible to implement such behavior or is it not the intended way of using it?

**Comment by laverdet** [comment]
The snapshot feature is meant to speed up initialization of large applications, not for packing up arbitrary application state and reusing it later.
