### ISSUE TITLE
native compiled modules with node-addon-api

### ISSUE THREAD

**Issue by meixg** [laverdet/isolated-vm#347]
I have a native module written with [node-addon-api](https://github.com/nodejs/node-addon-api), I wonder how can I change this module to use it in isolated-vm.

How to get `Napi::Env` to use?

**Comment by laverdet** [comment]
I don't know about `Napi::Env` but basically you need to export `InitForContext` which is invoked once per context. An example of a native add-on is here:
https://github.com/laverdet/xxscreeps/blob/main/src/driver/path-finder/main.cc
and also here
https://github.com/laverdet/isolated-vm/blob/main/native-example/example.cc
