### ISSUE TITLE
transfer: true used on copy() or copyInto() does not work as documented

### ISSUE THREAD

**Issue by jeromegn** [laverdet/isolated-vm#35]
According to the readme, it's possible to use `{transfer: true}` during `.copy()` and `.copyInto()`, but with a simple test case I was unable to make this pass.

```javascript
const ivm = require('isolated-vm')
const iso = new ivm.Isolate()
const toArrayBuffer = require('to-arraybuffer')

const ctx = iso.createContextSync()

let arrBuf = toArrayBuffer(Buffer.from("string"))
console.log("before", Buffer.from(arrBuf))

let g = ctx.globalReference()
g.setSync("blah", new ivm.ExternalCopy(arrBuf).copyInto({ transfer: true }))

console.log("after", Buffer.from(arrBuf))
```

This outputs:

```
$ node test.js
before <Buffer 73 74 72 69 6e 67>
after <Buffer 73 74 72 69 6e 67>
```

If I move the transfer option to the constructor call, it does work:

```
$ node test.js
before <Buffer 73 74 72 69 6e 67>
after <Buffer >
```

Maybe I misunderstood the documentation though.

**Comment by jeromegn** [comment]
This may just affect `copyInto()`, after looking at the code.

**Comment by jeromegn** [comment]
It also appears to not work with empty `ArrayBuffer`. I think that make sense, but it's one more thing to test for in our code. Maybe it could be done at the isolated-vm level, just send an empty ArrayBuffer to the other side. It used to work without `{transfer: true}`

**Comment by laverdet** [comment]
You have to use `{ transfer: true }` on both the constructor and the copy method.

On the constructor it will transfer the ArrayBuffer *out of* the current isolate. On the copy method it will transfer the ArrayBuffer *into* the current isolate. So if you had an array that your main isolate was done with but that several isolates needed access to, you could transfer it out and then do a regular call to copy into the isolates.

**Comment by laverdet** [comment]
Also the problem with allowing `{transfer:true}` on 0-length arrays is that it may lead to the user trying transfer the same ArrayBuffer more than once. When you transfer an ArrayBuffer out of v8 that ArrayBuffer needs to be invalidated, but the way this manifests itself in JS is a value of 0 for `byteLength`. These transferred ArrayBuffers then become pretty much indistinguishable from 0-length ArrayBuffers. So by removing the check I open you up to a different class of error that could be difficult to track.

**Comment by jeromegn** [comment]
I see. So `new ExternalCopy(arrBuf, {transfer: true})` will transfer the pointer ownership to some memory space managed by isolated-vm and then with `copyInto({transfer: true})` it knows to take it from that memory space and send it into the v8 isolate?

Re 0-length arrays: makes sense, thanks for explaining.

**Comment by laverdet** [comment]
Yes, that's how it works. Originally I had these options named `transferOut` on the constructor and `transferIn` on copy and copyInto but ended up just making them the same for both. I'm thinking now I should have them named differently. Any objections?

**Comment by jeromegn** [comment]
They may make it simpler to understand intuitively.

Would it be possible to do all of this in a single step too? My thought is that most use cases will send an ArrayBuffer into only one different isolate. If `{transfer: true}` is not set during construction and then set during `copy()` or `copyInto()`, you could both "transfer out" and then "transfer in" to the targeted isolate.

It's not a big deal, I'm fine with writing the same options twice.

**Comment by laverdet** [comment]
Once the ExternalCopy constructor is finished the copy has already been made. If `transfer` isn't set then it will perform a full copy, and if it is set then it will transfer ownership of the pointer away from v8 to isolated-vm and disable the existing ArrayBuffer. The thing that sets ExternalCopy apart from Reference is that ExternalCopy doesn't maintain any references back into v8. So by the time copy() is called it is too late to perform a simple transfer.

Transfer out and transfer in are discrete steps that are performed separately. I think `copyInto()` kind of hides this. copyInto() doesn't actually do any work, it just creates a placeholder JS object that has a reference to the ExternalCopy (this reference is maintained by isolated-vm, not v8). When that placeholder object is transferred to another isolate (ie with `set` or `apply`) it knows to call `copy()` on the original ExternalCopy once inside the other isolate.

Anyway I think this might be best accomplished with a wrapper on your end:
```js
function transferInto(buffer) {
  return (new ivm.ExternalCopy(buffer, { transferOut: buffer.length > 0 })).copyInto({ transferIn: true });
}
```

**Comment by jeromegn** [comment]
Oh, nice. Thanks for the explanation.

That wrapper works great too.
