### ISSUE TITLE
How to create an object and execute a function after compiling a module

### ISSUE THREAD

**Issue by NoahHahm** [laverdet/isolated-vm#357]
A Module
````
class ParentClass {
    print() {
        console.log('Parent Class');
    }
}
export default class extends ParentClass {

    print() {
        console.log('print');
    }
}
````

````
const isolate = new Isolate({
});

const isolateContext = isolate.createContextSync();
const module = isolate.compileModuleSync(fs.readFileSync('A.js'), {

});

module.instantiateSync(isolateContext, (d, b) => {
    return null;
});

module.evaluateSync({
    reference: true
});

const clazz = module.namespace.getSync("default", {
    reference: true
});

const classObj = isolateContext.evalClosureSync('return new $0()', [ clazz.derefInto() ], { result: { reference: true } });
classObj.getSync('print', {
       reference: true
}).applySync(null, [])

````

classObj.getSync('print', {
       reference: true
}).applySync(null, [])

TypeError: Reference is not a function

The print function below is not called and an error occurs.
The desired behavior is the act of calling the print function.
Any good examples? Seek help.
thank you.

**Comment by laverdet** [comment]
getSync of print is undefined because this property is inherited from a prototype and not an "own property". You can use unsafeInherit of Reference if you want to inherit, but you can no longer use the convenience reference:true option in this case.

**Comment by NoahHahm** [comment]
I haven't been able to resolve this issue yet. Can you suggest a suitable example? I've tried many things, but I'm still immature. thank you.
