### ISSUE TITLE
Releases and versioning

### ISSUE THREAD

**Issue by jeromegn** [laverdet/isolated-vm#36]
Would it be possible to make releases more frequently? I tend to have to use the github source in my npm package to benefit from the latest features.

What versioning scheme does isolated-vm adhere to?

There were a lot of features added lately, but I've only seen patch version bumps.

I find changelogs painstaking to maintain, we've started using the `standard-version` npm package for this. As long as the commits follow the [Conventional Commits](https://conventionalcommits.org/) format, it'll automatically decide how to bump the version.

**Comment by laverdet** [comment]
I'm planning on cutting 1.0.0 soon actually. isolated-vm adheres to semver which includes an exception where major version 0 can introduce breaking changes on patches.

**Comment by jeromegn** [comment]
Sounds good!

We're doing similar with @fly/fly where we're introducing breaking changes before 1.0.0, usually as minor bumps though.

It does sound like isolated-vm is getting awfully close to 1.0.0, the project got better in the last few weeks. Great work.
