### ISSUE TITLE
How to pass an object to an Isolate

### ISSUE THREAD

**Issue by LJ5O** [laverdet/isolated-vm#376]
Hi ! I'm currently switching from vm2 to this great library, and I'm trying to understand how to use it properly.
I've been working for a few days on passing an object to an Isolate and did some research on the topic, but I can't understand how to do it correctly, documentation isn't very clear about this.

I'm trying to work with discord.js in the isolate, and need to pass some objets. In the following codes, I'm testing with a [Message Object](https://old.discordjs.dev/#/docs/discord.js/main/class/Message?scrollTo=reply) ( `eventMessage` )

For now, I have this code : 
```js
'use-strict';
const ivm = require('isolated-vm');

module.exports = {

  runCodeInSandbox: async function(logger, eventMessage, codeToRun){

    const isolate = new ivm.Isolate({ memoryLimit: 32 });
    const context = await isolate.createContext();
    const jail = context.global;

    eventMessage.reply("Working outside of sandbox");/*TEST, working*/

    jail.setSync(key, new ivm.Reference(eventMessage, {unsafeInherit:true}));//eventMessage is defined here

    const code = await isolate.compileScript(codeToRun);
    await code.run(context).catch(err => {
     logger.error("Error in Isolate : "+err);
   });
    
  }
}
```

And in the Isolate, I try this code :
```js
eventMessage = eventMessage.copySync();
/*throw eventMessage.id;*/ //Working, id is defined
eventMessage.reply('Working in sandbox');
```
which returns `TypeError: eventMessage.reply is not a function`

So, is it possible to pass an object and keep both properties and methods ? 
Thanks in advance ! 🙂

**Comment by laverdet** [comment]
You need to help me help you. This is a small fragment of what seems to be a larger project and I can't make sense of it at all. Please post an example that can be run on its own.

**Comment by LJ5O** [comment]
Thank you for your prompt response ! To clarify my intentions, I've prepared an example that demonstrates what I'm attempting to achieve :

```js
const Discord = require('discord.js');
const ivm = require('isolated-vm');
const token = 'BOT-TOKEN'; // Found on https://discord.com/developers/applications

const client = new Discord.Client({//Client is created
  intents:[
    Discord.GatewayIntentBits.Guilds,
    Discord.GatewayIntentBits.GuildMembers,
    Discord.GatewayIntentBits.GuildMessages,
    Discord.GatewayIntentBits.MessageContent
  ]
});

client.once('ready', () => {
  console.log('Bot is online!');
});

client.on('messageCreate', async (message) => {//When a message is sent on a Discord server, and received by the bot
  // Check if the message is from a bot to prevent infinite loops
  if (message.author.bot) return;

  // Check if the message content is "hello"
  if (message.content.toLowerCase() === 'hello') {
    // Reply to the message
    message.reply('Hello there ! I\'m outside the sandbox');//Working outside of sandbox

    const isolate = new ivm.Isolate({ memoryLimit: 32 });
    const context = isolate.createContextSync();
    const jail = context.global;

    jail.setSync("message", new ivm.Reference(message, {unsafeInherit:true}));//I'm trying to pass the Message object in the sandbox

    const code = `
      message = message.copySync();
      message.reply("Hello there ! I'm in sandbox !");
    `;//Throws TypeError: message.reply is not a function

    const script = await isolate.compileScript(code);
    await script.run(context).catch(err => {
     console.error("Error in Isolate : "+err);
    });

  }
});

client.login(token);
```
In this example, I'm creating and connecting a Discord bot, who will listen for any message being sent somewhere.
When a message is received, a function is called with the `message` parameter, which is an object representing the message. This object is provided by the library `discord.js`.
In the function, I can do some checks with the `message`, and use the `.reply` method, so the bot responds to the sent message.
My goal is to pass the `message` object in the isolate, so I can work on it from a sand-boxed environment.

I'm using `jail.setSync("message", new ivm.Reference(message, {unsafeInherit:true}));` to pass the `message` object in the sandbox, which seems incorrect, since I can't use object methods. Object properties are accessible though.
( `message.id` is usable, but `message.reply()` isn't; trying to use `reply` method will throw `TypeError: message.reply is not a function` ) 

Is it possible to pass the `message` object in the isolate, without losing access to methods ?

**Comment by laverdet** [comment]
You probably want something like `message.reply.applySync(null, [ "Hello there ! I'm in sandbox !" ]);`

Just a note that the `unsafeInherit` property is unsafe and should only be used if you know what you're doing.

**Comment by LJ5O** [comment]
Hi, thanks for your reply !

I used `message.reply.applySync(null, [ "Hello there ! I'm in sandbox !" ]);` in the isolate, but that doesn't seems to work, since `TypeError: Cannot read properties of undefined (reading 'applySync')` is thrown. Maybe I made a mistake somewhere ?

For now, the sandbox-related code looks like
```js
message.reply('Hello there ! I\'m outside the sandbox');

const isolate = new ivm.Isolate({ memoryLimit: 32 });// Create a new sandbox/isolate limited to 32MB
const context = isolate.createContextSync();
const jail = context.global;//Will hold variables and functions required in the isolate

jail.setSync("message", new ivm.Reference(message, {unsafeInherit:true}));

const code = `
   message = message.copySync();
   message.reply.applySync(null, [ "Hello there ! I'm in sandbox !" ]);
 `;//Throws TypeError: Cannot read properties of undefined (reading 'applySync')

const script = await isolate.compileScript(code);
await script.run(context).catch(err => {
  console.error("Error in Isolate : "+err);
});
```
I also tried with `.apply`, `.applySync` and `.applySyncPromise` but I always get the same result.

Maybe the problem is that `.reply` method isn't passed in the isolate, as `message.reply` doesn't seems to be defined in sandbox : 
```js
const code = `
      message = message.copySync();
      if(message.reply){
        message.reply.apply(null, [ "Hello there ! I'm in sandbox !" ]);
      }else{
        throw "message.reply is undefined !";
      }

    `;//throws message.reply is undefined !;
```

To fix this, I tried the same as in #49 : 
```js
message.reply('Hello there ! I\'m outside the sandbox');

const isolate = new ivm.Isolate({ memoryLimit: 32 });// Create a new sandbox/isolate limited to 32MB
const context = isolate.createContextSync();
const jail = context.global;//Will hold variables and functions required in the isolate

jail.setSync("message", new ivm.Reference(message, {unsafeInherit:true}));
let obj = jail.getSync('message');
obj.setSync('reply', new ivm.Reference(message.reply));

const code = `
    message = message.copySync();
   if(message.reply){
     message.reply.apply(null, [ "Hello there ! I'm in sandbox !" ]);
   }else{
     throw "message.reply is undefined !";
   }
`;

const script = await isolate.compileScript(code);
await script.run(context).catch(err => {
  console.error("Error in Isolate : "+err);
});
```
At this point, nothing is thrown anymore, but the `.reply()` method isn't working, since no new message is sent. Nothing seems to happen. Do you have any idea about this ?

I will also avoid using `unsafeInherit` in production, as I used it only to perform some tests.

**Comment by laverdet** [comment]
When you call `copySync` it creates a copy of the payload using the structured clone algorithm; methods aren't going to be available in the copy. If you want to return to your user an object with a method on it you will need to construct that object from within the isolate.

**Comment by LJ5O** [comment]
So, there is no way to pass objects methods to an isolate ? I will try to find an other way then. Anyway, that should be more secure than directly passing methods, so that's fine.
Thanks for your help and congrats for this useful library ! 👍🏻

**Comment by liur118** [comment]
> 

Thank you!
By the way, should this line "message = message.copySync()" be deleted?
