### ISSUE TITLE
Inspector question with multiple contexts

### ISSUE THREAD

**Issue by jeromegn** [laverdet/isolated-vm#38]
The inspector has been working great, but I'm running into issues where breakpoints don't work anymore (either manually set in the inspector or via the `debugger` keyword) when I'm using a new context.

Our development server will reload the code and create a new context for each request. The context and isolate still both have the `{inspector: true}` option on them.

The script has a different filename too (I'm appending the sha1 of the source to the filename.)

Any idea why the inspector would stop working in these cases?

**Comment by laverdet** [comment]
I'm not sure. To be honest the inspector holds a lot of secrets and mysteries. The header file [[v8-inspector.h](https://github.com/v8/v8/blob/master/include/v8-inspector.h)] barely has any comments, so it's tough to know what it expects of you. I noticed that most of the nodejs v8 inspector integration was done by two guys with chromium.org email addresses which doesn't bode well for me.

Though if you can create an example and steps to reproduce I can definitely take a look and try and see where it's failing.

**Comment by jeromegn** [comment]
I attempted replicating with what I thought was the issue (multiple contexts) and couldn't using the inspector-example.js

I will continue pursuing this though.
