### ISSUE TITLE
lifecirce event

### ISSUE THREAD

**Issue by lilong7676** [laverdet/isolated-vm#387]
Is there a way to get an event like beforeExit to notify the runtime that it is about to time out before the code execution time expires?

**Comment by lilong7676** [comment]
I have noticed this issue, which may have inaccurate timing, is there a more accurate way to solve it?

https://github.com/laverdet/isolated-vm/issues/318#issuecomment-1206605535

**Comment by laverdet** [comment]
It's not possible today but could be a good feature.
