### ISSUE TITLE
Transferable values and errors

### ISSUE THREAD

**Issue by jeromegn** [laverdet/isolated-vm#39]
Is it possible to know beforehand if a value is transferable or not?

It appears:
- `string`, `number`, `boolean` types are transferable as-is because they're primitives
- the return value of `ExternalCopy(value).copyInto()` is transferable where value is anything

Is it possible to detect when a value is transferable? I can check for primitives, but I'm not sure how to tell from a copied `ExternalCopy`. The TypeScript definition says it returns the assigned type `T`, but I'm not sure it can be trusted. Even if it did, how would I know it's already been set as transferable?

I've started getting promise rejections when using `apply` on an `ivm.Reference<Function>`. I'm wondering if the return value from those functions are passed in. I switched everything to return `undefined`, but I still get the

```
A non-transferable value was passed
```

error if I check `.caught()` on that promise.

Is it possible this is coming from a different `.apply()` call? Given this package is 100% C++, it is hard to debug, figure out return values and the general flow of things.

**Comment by laverdet** [comment]
All instances of `ExternalCopy` are transferable no matter what.

If you do `ref1.apply()` and that function then does `ref2.apply()` without a try/catch in place and `ref2` returns a non-transferable value then that exception would indeed throw back out to whoever invoked `ref1.apply()`.

I suspect cross-isolate stack traces will be interesting to trace. Currently if you inspect the `stack` property of the error it should be the trace from where the error was first constructed. But an error could be thrown back and forth between your isolates depending on how your code is structured.

**Comment by jeromegn** [comment]
Hopefully I understand well what can and cannot be transferred. I opened #43 to make this understanding available in code.
