### ISSUE TITLE
how to get result when eval a function inside isolate-vm

### ISSUE THREAD

**Issue by jianmaikj** [laverdet/isolated-vm#393]
```
const {readFileSync} = require("fs");
var init_code = readFileSync(`./code_bak.js`, 'utf-8');
const ivm = require('isolated-vm');
const isolate = new ivm.Isolate({memoryLimit: 128});
const context = isolate.createContextSync();
context.evalSync(init_code);
const res = await context.evalClosure(
`get_data('${a}')` 
);
console.log('res :', res)
```

I want to execute the internal function `get_data`, how can I get the result, and I can't find an example.
Thanks!

**Comment by laverdet** [comment]
For `evalClosure` you can return.. const res = await context.evalClosure(`return get_data('${a}')`);

**Comment by jianmaikj** [comment]
> For `evalClosure` you can return.. const res = await context.evalClosure(`return get_data('${a}')`);

I tried, but got `TypeError: A non-transferable value was passed`

**Comment by jianmaikj** [comment]
> 

I kwon why, because it can't return object

**Comment by laverdet** [comment]
Read the docs for evalClosure and TransferOptions
