### ISSUE TITLE
Handling unhandled promise rejections

### ISSUE THREAD

**Issue by jeromegn** [laverdet/isolated-vm#40]
Is an event like browsers' `unhandledrejection` or node's `unhandledRejection` possible with V8?

It looks like the docs for `RunMicroTasks` says any errors are swallowed. I can't quite tell how browsers or node.js do it though.

**Comment by laverdet** [comment]
Uncaught promises are actually thrown to the invoker:

```js
let ivm = require('isolated-vm');
let isolate = new ivm.Isolate;
let context = isolate.createContextSync();
isolate.compileScriptSync('new Promise((_, reject) => reject(new Error("oops")))').runSync(context);
```

You'll see this throws the uncaught promise rejection back out to the main process. A global event is needed for browsers and nodejs where the event loop is out of your hand, but with isolated-vm it's kind of superfluous.

**Comment by jeromegn** [comment]
Oh that makes sense.

I thought it would get caught and ignored during `RunMicroTasks`.

Thanks!

**Comment by laverdet** [comment]
Though note that if there are *multiple* uncaught promise rejections or a promise rejection and a regular thrown error then all but one of them will be swallowed since only one error can be thrown at a time. This seemed like an ok design decision to me but let me know if there are issues.

**Comment by mifopen** [comment]
@laverdet but is it possible to get the final result of the failed evaluation somehow?
I mean if I have
```js
console.log(eval(`
    new Promise((_, reject) => reject(new Error("oops")));
    42;
`));
```
and I run it with node/browser, I will see 42 in the console.
But with `await context.eval(...)`, an exception will be thrown in the main thread.

**Comment by laverdet** [comment]
It's kind of a design flaw with isolated-vm right now. The intent was an easier API than v8's promise hooks [https://github.com/v8/v8/blob/784eb5e6ff2faa412723a65aa11e1badfdb75262/include/v8-promise.h#L125-L152] but I failed in that regard.
