### ISSUE TITLE
Thats possible use `zod` inside ivm?

### ISSUE THREAD

**Issue by 1bye** [laverdet/isolated-vm#400]
**Node.js**: 18.17.1
**OS**: Ubuntu 22.04
**Compiler**: gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04) 

Hi! Thats possible use `zod` inside ivm or use bundled `zod` package using browserify?
Can you show example how to do it, if its possible, please?

[Browserify bundled zod](https://pastebin.com/GbHH7fRQ) <--- pastebin

Or I should declare every function from `zod` in `context.evalClosure()` ?
Like:
```js
export class ZodWrapper {
    static methods = [
        this.z, /* 0 */
    ]

    static z() {
        return z;
    }

    static object(shape: ZodRawShape, params?: RawCreateParams) {
        return z.object(shape, params);
    }

    static number() {
        return z.number();
    }
}

// Then in ivm file/function

context.evalClosureSync(`
        z = {
            object: function () { 
                  return $0.apply(undefined, [], { arguments: { copy: true }, result: { copy: true } })  
            }
        }
`, ZodWrapper.methods, {arguments: {reference: true}})
```
But if it nested like `z.number().describe('This is number')`?

Thank you for awesome package!

**Comment by 1bye** [comment]
Thanks, I found solution:
I just bundled `zod` with webpack and then imported it like:
```js
/*Zod*/
isolate.compileScriptSync(fs.readFileSync(path.resolve('dist/zod/main.js'), 'utf8')).runSync(context)
```

**Comment by Henry-Le-CS** [comment]
Hi @1bye, could you please tell me after you imported zod like that, how could you use it in the `code` that requires it ?
