### ISSUE TITLE
ReferenceError: setTimeout is not defined

### ISSUE THREAD

**Issue by Kyle-Derrick** [laverdet/isolated-vm#401]
```javascript
const isolate = new ivm.Isolate({ memoryLimit: 128 });
const context = isolate.createContextSync();

const echarts_m = isolate.compileModuleSync(fs.readFileSync(require.resolve("echarts")).toString());
echarts_m.instantiateSync(context, () => {});
echarts_m.evaluateSync();

context.evalSync(`
(function() {
// setTimeout(() => log('test setTimeout'), 2000)
const chart = echarts.init(null, null, {
    renderer: "svg",
    ssr: true,
    width: 400,
    height: 300
})
}())
`, {timeout: 5000});
```

> the program throw exception: 
```shell
ReferenceError: setTimeout is not defined  
```
> How should I initialize some basic functions, such as setTimeout and other basic functions mentioned above, when creating a VM?

**Comment by laverdet** [comment]
setTimeout is an HTML function. If you want to provide it then you have to implement it in the isolate.

**Comment by mifopen** [comment]
@laverdet What do you mean by that? https://nodejs.org/docs/latest/api/timers.html#settimeoutcallback-delay-args

**Comment by laverdet** [comment]
https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html
