### ISSUE TITLE
Passing object with functions to Isolate

### ISSUE THREAD

**Issue by RealSput** [laverdet/isolated-vm#410]
Hello,
I would like to know how to pass objects with functions (e.g. `{ func_a: () => { console.log('Hello!') } }`) to an isolate and call it. I am trying to make a program that can interact with isolates. Help would be appreciated.

Thanks :)

**Comment by laverdet** [comment]
Hi I just added a section to the readme for this https://github.com/laverdet/isolated-vm#frequently-asked-question
