### ISSUE TITLE
Trigger axios in main Thread by Isolated?

### ISSUE THREAD

**Issue by carlosmperilla** [laverdet/isolated-vm#414]
Hi, I need help, is there any way to run axios correctly?

I have a code-string containing a function axios, I know I can use a constant of the form:

`const axios = { get: ... }`

And use some reference, but it's not working as it should, since by definition axios returns promises. Any way I can make the main process execute an axios function from a trigger in the isolated context?

**Comment by laverdet** [comment]
Check the readme please

**Comment by carlosmperilla** [comment]
@laverdet I already checked, I don't need to run axios inside the Isolate, I'm aware it doesn't make sense, could you give me an example of how to get the information from an asynchronous axios request and enter it into the isolate?

For example do a POST or a GET, external and then get the information?
