### ISSUE TITLE
Script `install` fails on Node.js `18.18.0`

### ISSUE THREAD

**Issue by mauricesnip** [laverdet/isolated-vm#415]
**Mac OS**: `13.4.1`
**Node.js**: `18.18.0` (using nvm)
**Yarn**: `1.22.19`

Hey there!

When trying to do a clean install of a project with `isolated-vm@4.6.0` as a subdependency, I encountered the following error using Node.js `18.18.0`:

```sh
backend on  main [?] is 📦 v1.0.0 via ⬢ v18.18.0 on 🐳 v24.0.6 (desktop-linux) took 2s 
➜ yarn
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
[6/6] ⡀ sqlite3
[2/6] ⡀ argon2
[3/6] ⡀ isolated-vm
[4/6] ⡀ sharp
error /Users/mauricesnip/repositories/backend/node_modules/isolated-vm: Command failed.
Exit code: 127
Command: prebuild-install || (node-gyp rebuild --release -j 4 && node-gyp clean)
Arguments: 
Directory: /Users/mauricesnip/repositories/backend/node_modules/isolated-vm
```

Or, when trying with `yarn upgrade-interactive`:

```sh
Error: /Users/mauricesnip/repositories/backend/node_modules/isolated-vm: Command failed.
Exit code: 127
Command: prebuild-install || (node-gyp rebuild --release -j 4 && node-gyp clean)
Arguments: 
Directory: /Users/mauricesnip/repositories/backend/node_modules/isolated-vm
Output:
prebuild-install warn install No prebuilt binaries found (target=18.18.0 runtime=node arch=arm64 libc= platform=darwin)
/bin/sh: node-gyp: command not found
    at ProcessTermError.ExtendableBuiltin (/Users/mauricesnip/.yarn/lib/cli.js:721:66)
    at ProcessTermError.MessageError (/Users/mauricesnip/.yarn/lib/cli.js:750:123)
    at new ProcessTermError (/Users/mauricesnip/.yarn/lib/cli.js:790:113)
    at ChildProcess.<anonymous> (/Users/mauricesnip/.yarn/lib/cli.js:25787:17)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5)
```

Though, everything works just fine when using Node.js `18.17.1`.

Any clues on what causes these errors?

### Addendum

Node.js `18.18.1` does not fix this.

**Comment by laverdet** [comment]
node-gyp is included with nodejs. There's something spooky with your environment. Please troubleshoot and let me know what you find.

**Comment by mauricesnip** [comment]
For posterity, this probably relates to the following issue: https://github.com/npm/cli/issues/6842 (also addressed here: https://github.com/nodejs/node/issues/49737).

**Comment by laverdet** [comment]
Interesting, it'd definitely be alarming if node-gyp is no longer in npm's path. For what it's worth, I was unable to reproduce on nodejs v18.18.1 but I use a custom installation script which manages multiple built-from-source copies of nodejs.

**Comment by mauricesnip** [comment]
Yeah, indeed. Guessing this is permanent, since it was intentional: https://github.com/npm/cli/pull/6554. Perhaps you could add a heads up to README.md?
