### ISSUE TITLE
How to import external library to isolate?

### ISSUE THREAD

**Issue by yizou10** [laverdet/isolated-vm#416]
Hi, 
I plan to import the external library to my isolate, for example this library: https://github.com/ethers-io/ethers.js,
so that I can use the Classes/Functions of Ethers.js directly in my isolate.
I tried but failed, so I don't know how to do it now.
Can you help me it? Is that possible to achieve this goal? If yes, how to to?
Thanks!

**Comment by SiDDhartharG** [comment]
link axios??

**Comment by yizou10** [comment]
@SiDDhartharG Hi, sorry, what did you mean "link axios??" ? It is a recommended solution for my question or you ask me if my goal is to link axios?

**Comment by SiDDhartharG** [comment]
like** axios

**Comment by yizou10** [comment]
@SiDDhartharG yes, like those external library. How to do?

**Comment by SiDDhartharG** [comment]
https://github.com/laverdet/isolated-vm/issues/217

**Comment by yizou10** [comment]
@SiDDhartharG I saw the solution of #217 is to use vm2. Is that means I should change to use vm2 instead of isolated-vm? It is impossible to import external library to isolates if use isolated-vm?

**Comment by lacuong2009** [comment]
Like library "[moment](https://momentjs.com/)" How can I import to.

**Comment by laverdet** [comment]
Hi all this is covered in the read me.
[How would you import `moment` in a web browser?](https://github.com/laverdet/isolated-vm#frequently-asked-question)
