### ISSUE TITLE
What's the best way to pass Moment to isolate

### ISSUE THREAD

**Issue by lacuong2009** [laverdet/isolated-vm#418]
I have tried to pass Moment to isolate but I got the error  "could not be clone".

   // import * as moment from 'moment';

    const alias = 'moment';
    const globalContextKey = 'globalMoment';
    context.global.setSync(
      globalContextKey,
      new ivm.ExternalCopy({}).copyInto(),
    );
    const gMoment = context.global.getSync(globalContextKey);
    gMoment.setSync(
      globalContextKey,
      new ivm.Reference(moment(), { unsafeInherit: true }).copySync(),
    );

Results: 
![image](https://github.com/laverdet/isolated-vm/assets/24735887/2abe56cf-48e1-4094-9124-44223bf50528)

Could you suggest the best way to resolve this?

**Comment by laverdet** [comment]
https://github.com/laverdet/isolated-vm#frequently-asked-question
