### ISSUE TITLE
Realm.shared re-enactment

### ISSUE THREAD

**Issue by eddow** [laverdet/isolated-vm#422]
[label: question]
Simulating a code written for V8 using itself virtual machines, I stumbled across this difficulty:
`Realm` is used to manage V8 "processes" and it uses `Realm.shared` as an object available in all the VMs.
This object contains :
- call backs to some VMs
- results from other VMs

Is it possible to enact this behavior, knowing this:
```js
const shared = parent.global.getSync('Realm').getSync('shared');
this.global.getSync('Realm').setSync('shared', shared.derefInto());
```
will just throw a `Cannot dereference this from current isolate`

Note: I cannot change the code to be simulated

**Comment by laverdet** [comment]
I don't know what you're asking me

**Comment by eddow** [comment]
I try to reformulate:
I need two VMs to share an object, 
- containing callbacks so that a VM can call another one
- letting modifications effectuated by one VM later on be visible from another VM
For now, I found a way to make a new object in my VM management code, generating the interface's functions who will just `forward.aplySync(...)` to the interface in the first VM, and manually copy a value when needed...

**Comment by laverdet** [comment]
Alright good luck
