### ISSUE TITLE
Shimming a function that has callback function as an argument?

### ISSUE THREAD

**Issue by rfedoruk** [laverdet/isolated-vm#430]
I am trying to do a shim for a library called [request](https://www.npmjs.com/package/request?activeTab=readme). 
I am setting this in the isolate here:
```
import request from 'request';
import ivm from 'isolated-vm';
  const isolate = new ivm.Isolate({memoryLimit: 512});
  const context = await isolate.createContext({ inspector: true });
  const jail = context.global;
  await jail.set('global', jail.derefInto());
  await jail.set('_ivm', ivm);

  await jail.set(
    '__host_request_put',
    new ivm.Reference(async (opts: any, callback: ivm.Reference<any>) => {
      request.put(opts, function (err: any, response: any) {
        if (err) {
          console.log('error in request put');
          callback.applySync(undefined, [err]);
        } else {
          console.log('success!');
          callback.applySync(undefined, [null, 'success']);
        }
      });
    })
  );
```
and in my isolate I have defined put like so:
```
const request = {
  put: (opts, callback) => {
    __host_request_put.apply(undefined, [opts, new _ivm.Reference(callback)], {
      arguments: { copy: true },
      result: { promise: true },
    });
  },
};
```
The problem that I am facing is that the isolate is getting disposed before the callback can be called in __host_request_put and it never runs. Here is the exact error here:
```
          callback.applySync(undefined, [null, 'testing']);
                   ^
Error: Isolated is disposed
    at Request._callback
```

I have shimmed another library that uses callbacks (xml2js), but that one had no dependencies, so I simply used rollup to generate a js file and compiled the module. That approach did not work here because request is making http/s requests and has a bunch of external deps that cannot be easily bundled. 
I have also tried wrapping __host_request_put in a promise but that does not seem to help.
I am using node 20. 
Any advice?

**Comment by jakeonfire** [comment]
here is a simpler, more secure way:
```js
context.evalClosureSync(
  `globalThis.doRequest = (...args) => $0.applySync(null, args, { arguments: { copy: true }, result: { promise: true } })`,
  [doRequest],
  { arguments: { reference: true } }
)
```
where `doRequest` returns a promise which makes the network call.

**Comment by rakeshar3796** [comment]
@jakeonfire Thanks for the help, i've a followup question, consider if a doRequest method is returning an object of methods so do i need to set all those inside global context?

Ex:
```
function doRequest() {
    return {
       get: () => {},
       post: () => {}
    }
}
```

so in my code if i try to access doRequest.get("SOME_URL") will this work?

**Comment by jakeonfire** [comment]
> so in my code if i try to access doRequest.get("SOME_URL") will this work?

since `doRequest` is a method, you'll need to call `doRequest().get("SOME_URL")`, but i think you might have issues trying to return a function from `doRequest`. you'd have to give it a try. you might have better luck defining separate functions, like `doGetRequest`, `doPostRequest`, etc.

**Comment by jakeonfire** [comment]
or you could do something like:
```js
function doRequest(method, ...args) {
    function get(args) {
      // ...
    }

    function post(args) {
      // ...
    }

    return this[method](args);
}
```
