### ISSUE TITLE
How to make transferable values from NativeModule?

### ISSUE THREAD

**Issue by jeromegn** [laverdet/isolated-vm#44]
(Hopefully this is not too much, there's no rush in responding to any of our issues!)

I'm excited by the prospect of the native module work you've done. I think it will help a lot with our project at Fly.

I was wondering what makes a value transferable exactly? I'd be interested in making constructs that can be used both in the node isolate and plain v8 isolates.

For instance, a ReadableStream implementation would allow reading from a source natively, both in nodejs and v8 isolates. If the underlying stream is managed outside of both node and v8, then I imagine it should be usable by either isolate. Of course it would be locked to a single reader at a time (and won't be readable after the first read, like the spec prescribes.)

Our idea is to allow for passing ReadableStream created in either nodejs or v8, back and forth. Reading from it would not involve calling back into the other isolate.

Is this something in the realm of possibilities?

**Comment by laverdet** [comment]
On the C++ side to be transferable a value should inherit from `TransferableHandle` -- both the C++ class and the JS function template. You implement a method `TransferOut()` which returns an instance of `Transferable` which should have no more dependencies on the current isolate. That class then must implement a method `TransferIn()` which creates a new v8::Value in the current isolate.

I don't actually know if it's possible to write C++ modules that implement this interface currently. The module system was built simply to enable in isolated-vm what is currently possible in nodejs. Let me know if you're interested in building more complex modules and I can export a real API for you to use.

**Comment by jeromegn** [comment]
Thanks, that's good to know. We currently don't have a need for more complex modules. I was mostly curious about the possibilities.

Turns out we solved that problem a different way and the overhead doesn't seem too bad.
