### ISSUE TITLE
Bun.js Unable to Execute Isolated-VM

### ISSUE THREAD

**Issue by amirfarzamnia** [laverdet/isolated-vm#450]
Isolated VM utilizes Google's V8 engine, whereas Bun.js employs JSC. It appears that the isolated VM is specifically designed for JavaScript runtimes relying on the V8 engine. Is there a way to integrate the isolated virtual machine with Bun.js, which utilizes JSC?

**Comment by laverdet** [comment]
isolated-vm will be a nodejs-only project for the foreseeable future.

**Comment by micalevisk** [comment]
@amirfarzamnia I guess we can close this by now

**Comment by VityaSchel** [comment]
> isolated-vm will be a nodejs-only project for the foreseeable future.

can anyone recommend bun.sh alternatives for this project?

**Comment by 0x7s0lt1** [comment]
Maybe [WebWorkers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) or [Child processes](https://bun.com/docs/api/spawn) 🫠

**Comment by supersonictw** [comment]
> > isolated-vm will be a nodejs-only project for the foreseeable future.
> 
> can anyone recommend bun.sh alternatives for this project?

https://github.com/justjake/quickjs-emscripten

quickjs-emscripten works. (though it uses quickjs engine)

**Comment by laverdet** [comment]
The experimental releases work on Bun now. It's still not ready for real applications but we're getting there.

```ts
// $ cat example.mts
import { Agent, expectComplete } from "@isolated-vm/experimental";
import { makeDirectResolver, makeLinker, makeStaticLoader } from "@isolated-vm/experimental/utility/linker";

const agent = await Agent.create();
const realm = await agent.createRealm();
const log = await realm.createCapability(
	() => ({
		log(...args: unknown[]) { console.log(">", ...args); },
	}),
	{ origin: "example:log" },
);
const module = expectComplete(await agent.compileModule(`
	import { log } from "example:log";
	log("Hello from v8!");
`));
const linker = makeLinker(
	makeDirectResolver(),
	makeStaticLoader({ "example:log": log }),
);
await module.link(realm, linker);
expectComplete(await module.evaluate(realm));

// $ node example.mts
// > Hello from v8!

// $ bun example.mts
// > Hello from v8!
```
