### ISSUE TITLE
Segmentation fault while trying to use native-example from this repo

### ISSUE THREAD

**Issue by Strate** [laverdet/isolated-vm#463]
Hello, trying to launch native-example from this repo got me segmentation fault:

I'm trying to perform these steps
```
git clone git@github.com:laverdet/isolated-vm.git
cd isolated-vm
npm install
cd native-example
npm install
node usage.js
```
I got output
```
Before runSync
[1]    46857 segmentation fault  node usage.js
```
My system:
MacOS 14.4.1 (23E224)
node v18.19.1 (I also tried latest v21, and latest LTS v20 - same error)

**Comment by laverdet** [comment]
You need to pass a flag to nodejs, there's a note in the readme about that under "🚨". The native example hasn't been updated in some time so will probably need tinkering.

**Comment by Strate** [comment]
However, using `--no-node-snapshot` (this is the only flag under "🚨" i found in readme) didn't help :(
Thank you for note about native examplt
