### ISSUE TITLE
Next.js: `new ivm.Isolate()` aborts the whole application without errors

### ISSUE THREAD

**Issue by baptisteArno** [laverdet/isolated-vm#472]
On a brand new Next.js application, simply calling `new ivm.Isolate()` crashes the application without any error in the logs.

Reproduction: https://github.com/baptisteArno/nextjs-isolated-vm-crash

How can we debug this further?

**Comment by laverdet** [comment]
cmd+f readme for 🚨

**Comment by laverdet** [comment]
You need to pass --no-node-snapshot.

**Comment by baptisteArno** [comment]
So sorry I overlooked this 🙏

Thanks so much!
