### ISSUE TITLE
Error: Cannot find module './out/isolated_vm'

### ISSUE THREAD

**Issue by anonyein** [laverdet/isolated-vm#473]
Error: Cannot find module './out/isolated_vm'
Require stack:
- D:\node_modules\isolated-vm\isolated-vm.js
nodejs 20.12.1
python 3.12.1

and the Directory of “./out/isolated_vm” doesn't exist
this module should be build?

**Comment by yasircodingcrafts** [comment]
I am facing this same issue

**Comment by laverdet** [comment]
Remove node_modules and reinstall. You need to do this each time you update nodejs

**Comment by laverdet** [comment]
Odd versions of nodejs are not supported
