### ISSUE TITLE
Segfault regarding TypedArrays

### ISSUE THREAD

**Issue by jeromegn** [laverdet/isolated-vm#48]
I got this while playing with probably-too-large ArrayBuffer allocations:

```
PID 23911 received SIGSEGV for address: 0x0
0   segfault-handler.node               0x00000001038f3168 _ZL16segfault_handleriP9__siginfoPv + 280
1   libsystem_platform.dylib            0x00007fffe68deb3a _sigtramp + 26
2   ???                                 0x0000000105950600 0x0 + 4388619776
3   node                                0x0000000100559129 _ZN2v88internal12JSTypedArray22MaterializeArrayBufferENS0_6HandleIS1_EE + 601
4   node                                0x000000010068a562 _ZN2v88internal27Runtime_TypedArrayGetBufferEiPPNS0_6ObjectEPNS0_7IsolateE + 70
5   ???                                 0x0000141d30846eb8 0x0 + 22115600592568
```

I couldn't find the exact cause of this, I worked around the issue another way. In the past you've been able to fix segfaults from these traces without much context, so maybe you can do the same this time :)

**Comment by laverdet** [comment]
If you still have your old code that hits this error could you please try again on master. de608f57bacf28bcc95fdbcd275d18e8167c7558 resolves an issue that would crash with a stack similar to yours, though I couldn't reproduce it myself.
