### ISSUE TITLE
Cannot create sandbox like previous vm library

### ISSUE THREAD

**Issue by hkm15022001** [laverdet/isolated-vm#483]
I want to pass the sandbox into the vm, which is an object with properties of type functions, class objects, maps, child objects,...
I easily passed it into the vm using the old vm2 library.
![Screenshot from 2024-07-12 14-18-35](https://github.com/user-attachments/assets/06ff8d18-9961-43c9-a61e-56f0a1f1ccdf)
GroupImpl,AllThings,ThingImpl,...  are classes that include methods, which I will use in the vm when running code
We hope to receive your help in this case, best regards.

**Comment by laverdet** [comment]
Please read the frequently asked question on the readme
