### ISSUE TITLE
Web APIs not available in isolated-vm?

### ISSUE THREAD

**Issue by arladmin** [laverdet/isolated-vm#487]
## Is Your Question Already Answered?
- [x] I have read the [Frequently Asked Question](https://github.com/laverdet/isolated-vm?tab=readme-ov-file#frequently-asked-question) in the README. My question is not the Frequently Asked Question.

---

Which Web APIs (https://developer.mozilla.org/en-US/docs/Web/API) are actually included in 'isolated-vm' ?

e.g. Seems like even the URL API (https://developer.mozilla.org/en-US/docs/Web/API/URL_API) is not included!

**Comment by laverdet** [comment]
None of them. Those are implemented in Chromium, for example. nodejs also has their own version of `URL` https://github.com/nodejs/node/blob/main/lib/url.js.
