### ISSUE TITLE
`Math.E` is undefined

### ISSUE THREAD

**Issue by melikhov-dev** [laverdet/isolated-vm#496]
Hi! Thanks for the great library! 

I found small strange bug — `Math.E` is `undefined`

## Is Your Question Already Answered?
- [x] I have read the [Frequently Asked Question](https://github.com/laverdet/isolated-vm?tab=readme-ov-file#frequently-asked-question) in the README. My question is not the Frequently Asked Question.

## Personal Diagnostics
Please answer the following questions:

#### JavaScript includes a `setTimeout` function:
- [ ] Yes
- [x] No

#### Functions are a type of primitive value in JavaScript:
- [x] Yes
- [ ] No

#### Objects can be shared between isolates:
- [ ] Yes
- [x] No

## The Code
- [x] This code will parse and evaluate if I put it into a file called `main.mjs` and then run `node main.mjs`.

```js
import ivm from "isolated-vm";
const isolate = new ivm.Isolate();
const context = isolate.createContextSync();

console.log(context.evalSync('Math.E')); //undefined
console.log(context.evalSync('Math.PI')); //3.141592653589793
```

**Comment by laverdet** [comment]
I'm not seeing the same results:

```
-> % node a.mjs
2.718281828459045
3.141592653589793
```

I don't have a clue about what could cause this kind of issue. `Math.E` has been in the language forever so it's surprising that something would cause that particular constant to go missing.

**Comment by melikhov-dev** [comment]
I checked it. This only happens with `node 20` and is not reproduced at `18` and `22`.
linux x64

**Comment by goshander** [comment]
Same issue, but on ARM and NodeJS 20 it throw `[1]    5645 segmentation fault  node a.mjs`

```
➜ uname -m -o
Darwin arm64

➜ node -v
v20.17.0
```

**Comment by laverdet** [comment]
Are you using `--no-node-snapshot`?

**Comment by melikhov-dev** [comment]
> Are you using --no-node-snapshot?

```
node --no-node-snapshot ivm-test.mjs 
2.718281828459045
3.141592653589793
```

Oh, I thought it was only a problem with arm64. Because all other cases and tests are fine.
