### ISSUE TITLE
`MemoryLimitExceeded` not properly triggering in `isolated-vm`

### ISSUE THREAD

**Issue by nathang0147** [laverdet/isolated-vm#499]
**Description:**
I am experiencing an issue with `isolated-vm` where the memory limit set for an isolate is not being enforced correctly during memory-intensive operations. Even though the memory limit is specified, the isolate continues executing until it crashes due to an out-of-memory error, without triggering the expected `MemoryLimitExceeded` error when memory usage exceeds the limit.

**Steps to Reproduce:**
1. Create an isolate with a specific memory limit.
2. Run memory-intensive code that exceeds the memory limit.
3. Despite memory usage approaching or exceeding the limit, the `MemoryLimitExceeded` error is not thrown, and the isolate eventually crashes due to out-of-memory.

**Expected Behavior:**
- When the memory usage approaches or exceeds the set limit (e.g., 80% of the limit), the isolate should throw a `MemoryLimitExceeded` error.

**Actual Behavior:**
- Memory usage spikes, and the isolate continues executing until it crashes due to an out-of-memory condition. The error handling for memory limit exceeding does not work as expected.

**Example Code:**
```javascript
Copy code
import ivm from "isolated-vm";

async function run() {
  const isolate = new ivm.Isolate({ memoryLimit: 128 * 1024 * 1024 });  // 128 MB memory limit
  const context = await isolate.createContext();

  const script = await isolate.compileScript(`
    let arr = [];
    while(true) {
      arr.push(new Array(10000).fill(0));  // Continuously allocate memory until memory is exhausted
    }
  `);

  try {
    await script.run(context);
  } catch (error) {
    console.log('Error occurred:', error.message);
  }
}

run();
```

**What I've Tried:**
- I've attempted to monitor memory usage using `getHeapStatistics()` in a setInterval, but the memory usage still spikes beyond the limit without triggering the `MemoryLimitExceeded` error.
- The error handling for memory usage is not responsive enough to prevent an out-of-memory crash.
- I have tried different memory limits (e.g., 128 MB, 256 MB) to no avail.

**Environment:**
- isolated-vm version: v5.0.1
- Node.js version: v20.15.1

**Personal Diagnostics:**
 This code will parse and evaluate if I put it into a file called `main.mjs` and then run node `main.mjs`.
 Yes, JavaScript includes a `setTimeout` function.
 Yes, functions are a type of primitive value in JavaScript.
 No, objects cannot be shared between isolates.

**Comment by laverdet** [comment]
There are certain classes of scripts which v8 simply cannot preempt. The Array methods are particularly vulnerable to this. I reported `Array.prototype.join` to the team 5 years ago which is still open today. https://issues.chromium.org/issues/42212548

I would suspect `Array.prototype.fill` is the same

**Comment by nathang0147** [comment]
Thank you all for your help! Your insights on memory limits and handling isolate disposal really helped me resolve the issue in my project. I’ve successfully implemented a solution based on the suggestions here. Closing this now—thanks again!
