### ISSUE TITLE
CPU/wall time per context?

### ISSUE THREAD

**Issue by jeromegn** [laverdet/isolated-vm#54]
Would it be possible to get those timings per context? I assume it's a matter of summing the time during which the context "has the lock" on the isolate? (that would probably be wall time though)

**Comment by laverdet** [comment]
Sorry this is not possible. Consider:
- Contexts can grab references to each other without isolated-vm even knowing.
- Contexts share garbage collection, therefore a context may lose the garbage collection lottery and need to pay for other contexts' garbage.
- Many other operations don't belong to a context at all (`compileScript`, various v8 bookkeeping).
- The timer code is already super complex as it is.

Theoretically I could build per context timers but it would end up being clumsy and inaccurate. I think with the above considerations in mind you could slice up the timers on your end as your futures resolve.

**Comment by jeromegn** [comment]
👍 all good, thought I'd ask!
