### ISSUE TITLE
Segfault in Isolate Environment AsyncCallbackPool

### ISSUE THREAD

**Issue by jeromegn** [laverdet/isolated-vm#60]
I don't have the trace unfortunately. The segfault-handler package doesn't always catch it.

Here's the log line just before the process crashed (exit code 134):

```
node: ../src/isolate/environment.cc:171: static void ivm::IsolateEnvironment::Scheduler::AsyncCallbackPool(bool, void*): Assertion `root_async.data == nullptr' failed.
```

This is the only line I could find, this is in production. Our process promptly restarted afterwards.

**Comment by laverdet** [comment]
How often have you seen this error? I have an idea of what circumstances would cause an issue like this (I actually have a comment in [environment.cc](https://github.com/laverdet/isolated-vm/blob/f78203b4db0271894437001439a623350fd7413b/src/isolate/environment.cc#L172-L174) alluding to this), but I haven't managed to reproduce it myself.

**Comment by jeromegn** [comment]
I'm not sure when it happened exactly. Last time I saw it (and the only time i saw it,) it appears to have happened for no particular reason.

Next time I notice it (if ever), I'll try to figure that out more precisely.
