### ISSUE TITLE
Wire up existing `console` in v8?

### ISSUE THREAD

**Issue by mrkurt** [laverdet/isolated-vm#62]
v8 has console stuff built in but there's no stdout/err up to it (I think that's all that's missing). Is there a way to hook it up through isolated-vm?

**Comment by laverdet** [comment]
I think the v8 console API is meant for internal use only. The only way to get console working in an isolate is to create an object in the isolate which forwards calls back to nodejs via `apply`. This might be a good candidate for an npm module.

**Comment by mrkurt** [comment]
That's roughly what we did! But the built in console has a lot of really nice logic for turning random values into strings. I was hoping to be lazy. 😁
