### ISSUE TITLE
Example of making an XMLHttpRequest?

### ISSUE THREAD

**Issue by justin808** [laverdet/isolated-vm#63]
Following up on #27.
 
Is there any simple example of making an XMLHttpRequest? 

I'd like to create an "isolate" with a webpack bundle that has a function for server rendering an Apollo GraphQL React Component. 

Then I'd like to run a tiny bit of JS code to execute this function on repeated requests. 

The server should be able to understand that the "context" needs rebuilding with a new webpack bundler periodically.

Should this be possible with `isolated-vm`? It definitely is not with plain `vm`.

**Comment by laverdet** [comment]
It's definitely possible but you'll have to write the wrapper around the underlying `http` invocation within nodejs. What this project gives you is a plain isolate which is *only* javascript. XMLHttpRequest is a WHATWG/W3C standard which is far outside the scope of a JS vm.
