### ISSUE TITLE
Not compatible with Node 10

### ISSUE THREAD

**Issue by thelinuxlich** [laverdet/isolated-vm#64]

**Comment by laverdet** [comment]
Thanks for the report. I was testing on node v9.x and it seems a lot of stuff changed in between then and v10.x. This initial patch should get isolated-vm running for now, though I need to do some extra work before cutting an npm release. I'll follow up hopefully next week with some extra testing and a release.

**Comment by jeromegn** [comment]
Seems to work well for me.
