### ISSUE TITLE
can't build on windows?

### ISSUE THREAD

**Issue by barnese3** [laverdet/isolated-vm#65]
npm install -g @fly/fly
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
C:\Users\embar\AppData\Roaming\npm\fly -> C:\Users\embar\AppData\Roaming\npm\node_modules\@fly\fly\lib\cmd\index.js
> unix-dgram@0.2.3 install C:\Users\embar\AppData\Roaming\npm\node_modules\@fly\fly\node_modules\unix-dgram
> node-gyp rebuild
C:\Users\embar\AppData\Roaming\npm\node_modules\@fly\fly\node_modules\unix-dgram>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  unix_dgram.cc
  win_delay_load_hook.cc
..\src\unix_dgram.cc(9): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory [C:\Users\e
mbar\AppData\Roaming\npm\node_modules\@fly\fly\node_modules\unix-dgram\build\unix_dgram.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\embar\AppData\Roaming\npm\node_modules\@fly\fly\node_modules\unix-dgram
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
> isolated-vm@1.6.0 install C:\Users\embar\AppData\Roaming\npm\node_modules\@fly\fly\node_modules\isolated-vm
> node-gyp rebuild --release -j 4
C:\Users\embar\AppData\Roaming\npm\node_modules\@fly\fly\node_modules\isolated-vm>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release -j 4 )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --release -j 4 )
cl : Command line warning D9025: overriding '/GR-' with '/GR' [C:\Users\embar\AppData\Roaming\npm\node_modules\@fly\fly
\node_modules\isolated-vm\build\isolated_vm.vcxproj]
cl : Command line warning D9025: overriding '/GR-' with '/GR' [C:\Users\embar\AppData\Roaming\npm\node_modules\@fly\fly
\node_modules\isolated-vm\build\isolated_vm.vcxproj]
cl : Command line warning D9025: overriding '/GR-' with '/GR' [C:\Users\embar\AppData\Roaming\npm\node_modules\@fly\fly
\node_modules\isolated-vm\build\isolated_vm.vcxproj]
  allocator.cc
  class_handle.cc
cl : Command line warning D9025: overriding '/GR-' with '/GR' [C:\Users\embar\AppData\Roaming\npm\node_modules\@fly\fly
\node_modules\isolated-vm\build\isolated_vm.vcxproj]
cl : Command line warning D9025: overriding '/GR-' with '/GR' [C:\Users\embar\AppData\Roaming\npm\node_modules\@fly\fly
\node_modules\isolated-vm\build\isolated_vm.vcxproj]
  environment.cc
  holder.cc
  inspector.cc
  stack_trace.cc
  three_phase_task.cc
  context_handle.cc
  external_copy.cc
  external_copy_handle.cc
  isolate.cc
  isolate_handle.cc
..\src\external_copy_handle.cc(66): warning C4244: 'argument': conversion from 'std::size_t' to 'double', possible loss
 of data [C:\Users\embar\AppData\Roaming\npm\node_modules\@fly\fly\node_modules\isolated-vm\build\isolated_vm.vcxproj]
c:\users\embar\appdata\roaming\npm\node_modules\@fly\fly\node_modules\isolated-vm\src\isolate/platform_delegate.h(104):
 warning C4244: 'argument': conversion from 'double' to 'uint32_t', possible loss of data (compiling source file ..\src
\isolate.cc) [C:\Users\embar\AppData\Roaming\npm\node_modules\@fly\fly\node_modules\isolated-vm\build\isolated_vm.vcxpr
oj]
  lib_handle.cc
  native_module_handle.cc
c:\users\embar\appdata\roaming\npm\node_modules\@fly\fly\node_modules\isolated-vm\src\isolate/platform_delegate.h(104):
 warning C4244: 'argument': conversion from 'double' to 'uint32_t', possible loss of data (compiling source file ..\src
\isolate_handle.cc) [C:\Users\embar\AppData\Roaming\npm\node_modules\@fly\fly\node_modules\isolated-vm\build\isolated_v
m.vcxproj]
..\src\isolate_handle.cc(432): warning C4244: 'argument': conversion from 'std::size_t' to 'double', possible loss of d
ata [C:\Users\embar\AppData\Roaming\npm\node_modules\@fly\fly\node_modules\isolated-vm\build\isolated_vm.vcxproj]
..\src\isolate_handle.cc(433): warning C4244: 'argument': conversion from 'std::size_t' to 'double', possible loss of d
ata [C:\Users\embar\AppData\Roaming\npm\node_modules\@fly\fly\node_modules\isolated-vm\build\isolated_vm.vcxproj]
..\src\isolate_handle.cc(434): warning C4244: 'argument': conversion from 'std::size_t' to 'double', possible loss of d
ata [C:\Users\embar\AppData\Roaming\npm\node_modules\@fly\fly\node_modules\isolated-vm\build\isolated_vm.vcxproj]
..\src\isolate_handle.cc(436): warning C4244: 'argument': conversion from 'std::size_t' to 'double', possible loss of d
ata [C:\Users\embar\AppData\Roaming\npm\node_modules\@fly\fly\node_modules\isolated-vm\build\isolated_vm.vcxproj]
..\src\isolate_handle.cc(438): warning C4244: 'argument': conversion from 'std::size_t' to 'double', possible loss of d
ata [C:\Users\embar\AppData\Roaming\npm\node_modules\@fly\fly\node_modules\isolated-vm\build\isolated_vm.vcxproj]
..\src\isolate_handle.cc(439): warning C4244: 'argument': conversion from 'std::size_t' to 'double', possible loss of d
ata [C:\Users\embar\AppData\Roaming\npm\node_modules\@fly\fly\node_modules\isolated-vm\build\isolated_vm.vcxproj]
..\src\isolate_handle.cc(440): warning C4244: 'argument': conversion from 'std::size_t' to 'double', possible loss of d
ata [C:\Users\embar\AppData\Roaming\npm\node_modules\@fly\fly\node_modules\isolated-vm\build\isolated_vm.vcxproj]
..\src\isolate_handle.cc(441): warning C4244: 'argument': conversion from 'std::size_t' to 'double', possible loss of d
ata [C:\Users\embar\AppData\Roaming\npm\node_modules\@fly\fly\node_modules\isolated-vm\build\isolated_vm.vcxproj]
  reference_handle.cc
  script_handle.cc
  session_handle.cc
  transferable.cc
  win_delay_load_hook.cc
     Creating library C:\Users\embar\AppData\Roaming\npm\node_modules\@fly\fly\node_modules\isolated-vm\build\Release\i
  solated_vm.lib and object C:\Users\embar\AppData\Roaming\npm\node_modules\@fly\fly\node_modules\isolated-vm\build\Rel
  ease\isolated_vm.exp
isolate.obj : error LNK2001: unresolved external symbol "protected: static double __cdecl v8::Platform::SystemClockTime
Millis(void)" (?SystemClockTimeMillis@Platform@v8@@KANXZ) [C:\Users\embar\AppData\Roaming\npm\node_modules\@fly\fly\nod
e_modules\isolated-vm\build\isolated_vm.vcxproj]
C:\Users\embar\AppData\Roaming\npm\node_modules\@fly\fly\node_modules\isolated-vm\build\Release\isolated_vm.node : fata
l error LNK1120: 1 unresolved externals [C:\Users\embar\AppData\Roaming\npm\node_modules\@fly\fly\node_modules\isolated
-vm\build\isolated_vm.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release" "-j" "4"
gyp ERR! cwd C:\Users\embar\AppData\Roaming\npm\node_modules\@fly\fly\node_modules\isolated-vm
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN rollback Rolling back fsevents@1.2.3 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\Users\embar\AppData\Roaming\npm\node_modules\@fly\fly\node_modules'
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules\@fly\fly\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: unix-dgram@0.2.3 (node_modules\@fly\fly\node_modules\unix-dgram):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: unix-dgram@0.2.3 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! isolated-vm@1.6.0 install: `node-gyp rebuild --release -j 4`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the isolated-vm@1.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\embar\AppData\Roaming\npm-cache\_logs\2018-05-10T15_45_57_657Z-debug.log

**Comment by laverdet** [comment]
Can you try building from the source on github please? I think that'll work
for you. I just need to publish a new npm package.
