### ISSUE TITLE
Passing functions between isolates

### ISSUE THREAD

**Issue by eaglgenes101** [laverdet/isolated-vm#73]
As isolated-vm currently is, the module will choke if it ever tries to pass a function across an isolate boundary. This can be overcome by adding boilerplate to manually wrap the object in a reference and then calling apply on the reference, but with passing functions being a regularity in javascript, and a number of objects having methods implicitly attached to them thanks to prototypes, this becomes real unwieldy, real fast. 

Are there plans to make passing functions between isolate boundaries less tedious?

**Comment by laverdet** [comment]
I think a clear declaration of intent is necessary. Passing data between isolates is imperfect and trying to make this simpler could have surprising results in all but the most simple cases.

**Comment by eaglgenes101** [comment]
Would a callback of "Hey, I ran into a function while trying to apply a structured clone, what should I bind the corresponding serialized function to?" be specific enough? I am fine with declaring my intent, but being required to check my object for function-freeness all the way through before I can send it through means I'm basically rewriting half of a serializer again.

**Comment by laverdet** [comment]
The callback idea is interesting.

I'm wondering if #49 is a better solution to whatever you're trying to solve though. What's your use case for passing arbitrarily nested structures of functions?

**Comment by eaglgenes101** [comment]
I'm currently working on a sandbox wrapper for executing code that was (and still is) expecting to be able to interface with object methods and functions from outside. That said, I've since implemented a proxy-based method that fetches property values from the reference on-the-fly. Still, being able to recover from a noncloneable value within an object without having to walk it first would be a nice boon to performance.

**Comment by laverdet** [comment]
How do your proxy objects handle references..

```js
let foo = {};
let obj1 = { foo };
let obj2 = { foo };
crossIsolateObject.prop1 = obj1;
crossIsolateObject.prop2 = obj2;
console.log(crossIsolateObject.prop1.foo == crossIsolateObject.prop2.foo);
```

**Comment by eaglgenes101** [comment]
As of now, as a performance optimization to avoid having to fetch and demarshal a new object every time a new property is accessed, object properties that can be cloned are cloned into the other isolate. Admittedly, this makes my isolate sandbox distinguishable from an unsandboxed runtime, but in practice, this turns out to be rare in tests, as objects passed to the code in the sandbox generally were defensively copied and avoided aliasing even before I decided to confine their resources, and changes to the objects are intercepted by the proxy and confined to the local isolate object, making it impossible to tell whether objects are aliased by modifying them. If accurate behavior with object aliasing was a greater concern, I could revert to the old sandboxing behavior, which resolves properties to new proxy objects only once they are accessed, and take care that each object is only ever referred to by one reference.

**Comment by elglogins** [comment]
Hi @eaglgenes101 , did you get any further with this?
