### ISSUE TITLE
Segfault 11 while calling evaluateSync

### ISSUE THREAD

**Issue by xtforgame** [laverdet/isolated-vm#74]
My environment is
 - node version: v10.7.0
 - MacOS version: 10.12.6
 - isolated-vm version: master

I tried to run the following code:

```js
const ivm = require('isolated-vm');

const isolate = new ivm.Isolate();
const context = isolate.createContextSync();

const jail = context.global;
jail.setSync('global', jail.derefInto());

const m = isolate.compileModuleSync('global');
const dependencySpecifiers = m.dependencySpecifiers;
m.instantiateSync(context);
m.evaluateSync();
```

then I got

```
Segmentation fault: 11
```

**Comment by laverdet** [comment]
Modules are still kind of a work of progress. Could you please try master again, my push should resolve this issue.

**Comment by xtforgame** [comment]
@laverdet Thanks, I have tried the new master, and it works now :)
