### ISSUE TITLE
Problem about resolving dependencies by using the new `instantiateSync` function

### ISSUE THREAD

**Issue by xtforgame** [laverdet/isolated-vm#77]
Hi,

I just found the `setDependency` function was deprecated, and I tried to use the new ```instantiateSync``` function.

My problem is, I think the arguments for the callback function are not enough to resolve the modules.

For example, my file structure as shown below:
```
index.js
a.js
xxx/index.js
xxx/a.js
```

Both``` index.js``` and ```xxx/index.js``` use ```import './a.js';``` to import different ```a.js``` files
. And while calling ```instantiateSync```, I can't resolve ```./a.js``` without the filename of the ```referrer```

**Comment by laverdet** [comment]
When you create the module can you assign your file name to it as a
property on the object?

**Comment by laverdet** [comment]
It's a bit of a strange problem.. module resolution is an implementation detail which is left entirely to the "host", and as a user of isolated-vm you are the host. The nodejs [vm.Module](https://nodejs.org/api/vm.html#vm_constructor_new_vm_module_code_options) constructor has a simple `url` option which just adds a property called `url` to the returned module. It felt superfluous to add a similar feature, but it also kind of feels like something is missing without it. Anyway I'll probably add a similar feature in a minor release later but for now it doesn't seem like too big of a deal.

**Comment by xtforgame** [comment]
@laverdet 
Hi, thanks for your detail explanation, I really learned a lot from that. I also read some article about the ES module, now I understand that the ```module_name``` is irrelevant to the file system specifications, and I also agree that the ```url``` is a nice-to-have feature but not really necessary for module resolution. 

Thank you again for your sharing 👍
