### ISSUE TITLE
How to add setInterval and console as reference to the Isolate context

### ISSUE THREAD

**Issue by TheAifam5** [laverdet/isolated-vm#79]
Hey,
I want to start a script which using setInterval and console and. Script is compiled using WebPack.

The problem is that `ReferenceError: setInterval is not defined`.
Can someone help me with it?

Regards,
TheAifam5

**Comment by laverdet** [comment]
You need to define it with a `Reference` object wrapped around the user's callback. You then use `apply` to call it.
