### ISSUE TITLE
Passing data around a script transparently

### ISSUE THREAD

**Issue by TLadd** [laverdet/isolated-vm#83]
I'm trying to figure out if there is a way to get data through a script transparently with the following setup: I'm using a single isolate and context per-script in my node server. The scripts themselves set up a listener, which is then triggered on each request by calling a function exposed in the global context. For global api's that I setup in the context that call back out to node, I want to have information about the request that triggered the script passed through to the node handlers. I don't want the scripts themselves to have to worry about passing this data through manually. I'm wondering if this is possible. This shows the basic setup, where triggerFn triggers the script to run, and I'm trying to get reqId through to the _log function:

```javascript
let ivm = require("isolated-vm");
let isolate = new ivm.Isolate({ memoryLimit: 128 });
let context = isolate.createContextSync();

let jail = context.global;
jail.setSync("global", jail.derefInto());
jail.setSync("_ivm", ivm);

jail.setSync(
  "_log",
  new ivm.Reference(function(...args) {
    // How can I get reqId here?
    console.log(...args);
  })
);

let bootstrap = isolate.compileScriptSync(
  "new " +
    function() {
      let ivm = _ivm;
      delete _ivm;

      let log = _log;
      delete _log;
      global.log = function(...args) {
        log.applyIgnored(
          undefined,
          args.map(arg => new ivm.ExternalCopy(arg).copyInto())
        );
      };

      let listener;
      global.addEventListener = function(fn) {
        listener = fn;
      };

      global.triggerFn = function(reqId) {
        listener();
      };
    }
);

bootstrap.runSync(context);

isolate
  .compileScriptSync('addEventListener(() => log("hello world"))')
  .runSync(context);

let triggerFn = context.global.getSync("triggerFn");
triggerFn.apply(null, [1]);
triggerFn.apply(null, [2]);
```

One thing I've considered is creating a new context for each request, which would result in there being a new _log handler for each request that could have the reqId built into it. I'm a little worried about the overhead of creating/releasing a context for each request though. It would also prevent a script from storing information across invocations in a global variable. Any insight on approaches would be greatly appreciated!

**Comment by xtforgame** [comment]
I'm not sure if the following way is what you want

```js
jail.setSync(
  "_log",
  new ivm.Reference(function(reqId, ...args) {
    console.log(...args);
  })
);

let bootstrap = isolate.compileScriptSync(
  "new" + function() {
    let ivm = _ivm;
    delete _ivm;

    let log = _log;
    delete _log;

    let listener;
    global.addEventListener = function(fn) {
      listener = fn;
    };

    global.triggerFn = function(reqId) {
      global.log = function(...args) {
        log.applyIgnored(
          undefined,
          [reqId, ...args.map(arg => new ivm.ExternalCopy(arg).copyInto())]
        );
      };
      listener();
    };
  }
);
```

**Comment by TLadd** [comment]
I believe if I were to overwrite the global api each time triggerFn is called, there would be issues where one call would overwrite the function prior to another call making all of its invocations of the global apis, since each call is sharing the same global context. Some of the global functions I setup are asynchronous with callbacks as well.

**Comment by laverdet** [comment]
I'd just recommend making a new context per request if you want those contexts to have different global variables between them.

Otherwise you can do something like this:
```js
let ivm = require("isolated-vm");
let isolate = new ivm.Isolate({ memoryLimit: 128 });
let context = isolate.createContextSync();

let jail = context.global;
jail.setSync("global", jail.derefInto());
jail.setSync("_ivm", ivm);

jail.setSync(
  "_log",
  new ivm.Reference(function(redId, ...args) {
    // How can I get reqId here?
    console.log(...args);
  })
);

let bootstrap = isolate.compileScriptSync(
  "new " +
    function() {
      let ivm = _ivm;
      delete _ivm;

      let log = _log;
      delete _log;
      let reqId;
      global.log = function(...args) {
        log.applyIgnored(
          undefined,
          [reqId, ...args.map(arg => new ivm.ExternalCopy(arg).copyInto())]
        );
      };

      let listener;
      global.addEventListener = function(fn) {
        let myReqId = reqId;
        listener = function(...args) {
          reqId = myReqId;
          return fn.apply(this, ...args);
        };
      };

      global.triggerFn = function(myReqId) {
        reqId = myReqId;
        listener();
      };
    }
);

bootstrap.runSync(context);

isolate
  .compileScriptSync('addEventListener(() => log("hello world"))')
  .runSync(context);

let triggerFn = context.global.getSync("triggerFn");
triggerFn.apply(null, [1]);
triggerFn.apply(null, [2]);
```

Something that isn't obvious when you start working with isolated-vm is that you're actually in control of all entry points into the isolate. So even though your isolate might be making asynchronous requests, your code must act as a delegate. Therefore you would always have a chance to update `reqId` to the correct value even while using a single context.

**Comment by TLadd** [comment]
Thank you for the response! I tried running the snippet you posted but the reqId received by the _log function is always undefined. 
```
      let listener;
      global.addEventListener = function(fn) {
        let myReqId = reqId;
        listener = function(...args) {
          reqId = myReqId;
          return fn.apply(this, ...args);
        };
      };
```
Since addEventListener is called once before calling triggerFn, reqId hasn't been set and myReqId is set to undefined. When the listener is called by triggerFn, reqId is then set to undefined.

I tried removing the `let myReqId = reqId;` and the `reqId = myReqId;` lines here, and I do get reqId through, since it is set in triggerFn. However, if triggerFn is called twice and I add a setTimeout to the script, I will get a reqId of 2 for both invocations, since the second triggerFn call overwrites reqId before the first invocation calls log.

```
let ivm = require("isolated-vm");
let isolate = new ivm.Isolate({ memoryLimit: 128 });
let context = isolate.createContextSync();

let jail = context.global;
jail.setSync("global", jail.derefInto());
jail.setSync("_ivm", ivm);

jail.setSync(
  "_log",
  new ivm.Reference(function(reqId, ...args) {
    // How can I get reqId here?
    console.log(reqId, ...args);
  })
);
jail.setSync(
  "_setTimeout",
  new ivm.Reference(function(fn, ms) {
    setTimeout(() => {
      fn.applyIgnored(null, []);
    }, ms);
  })
);

let bootstrap = isolate.compileScriptSync(
  "new " +
    function() {
      let ivm = _ivm;
      delete _ivm;

      let log = _log;
      delete _log;
      let reqId;
      global.log = function(...args) {
        log.applyIgnored(undefined, [
          reqId,
          ...args.map(arg => new ivm.ExternalCopy(arg).copyInto())
        ]);
      };

      let setTimeout = _setTimeout;
      delete _setTimeout;
      global.setTimeout = function(fn, ms) {
        setTimeout.applyIgnored(undefined, [new ivm.Reference(fn), ms]);
      };

      let listener;
      global.addEventListener = function(fn) {
        listener = function(...args) {
          return fn.apply(this, ...args);
        };
      };

      global.triggerFn = function(myReqId) {
        reqId = myReqId;
        listener();
      };
    }
);

bootstrap.runSync(context);

isolate
  .compileScriptSync(
    'addEventListener(() => { setTimeout(() => log("hello world"), 1000) })'
  )
  .runSync(context);

let triggerFn = context.global.getSync("triggerFn");
triggerFn.apply(null, [1]);
triggerFn.apply(null, [2]);
```

The output of running this is
```
2 'hello world'
2 'hello world'
```

But I would want it to be
```
1 'hello world'
2 'hello world'
```

**Comment by laverdet** [comment]
You'll have to keep track of `reqId` in your `setTimeout` function then.

**Comment by TLadd** [comment]
Just to be clear, by keeping track of reqId in setTimeout, you mean doing something like this, right?

```
      global.setTimeout = function(fn, ms) {
        let myReqId = reqId;
        setTimeout.applyIgnored(undefined, [
          new ivm.Reference(() => {
            reqId = myReqId;
            fn();
          }),
          ms
        ]);
      };
```

**Comment by laverdet** [comment]
Sure, that works. I think you might be overthinking this, because the problem you're running into here would be the exact same if you removed isolated-vm from the equation entirely.
