### ISSUE TITLE
No Module type in TypeScript definitions (isolated-vm.d.ts)

### ISSUE THREAD

**Issue by alufers** [laverdet/isolated-vm#85]
Hi!
I see that the TypeScript definition files are out of date in reference to the current API. They lack the `Module` class and the functions connected with it. I could create a pull request fixing this, but I'd like to ask first :)

Best regards

**Comment by laverdet** [comment]
Sure, go ahead. I don't actually use TypeScript so I'm not personally keeping them up to date, the definitions there were contributed and maintained by other users. Thanks!
