### ISSUE TITLE
Question about filesystem and process

### ISSUE THREAD

**Issue by tripodsan** [laverdet/isolated-vm#87]
Hi,
if I understand correctly, all the isolates run in the same process. so they share the `process` object as well as the host filesystem. what prevents a _malicious_ code do `process.exit()` or `fs.readFile('/etc/passwd')` ?

**Comment by laverdet** [comment]
`process` and `fs` are implemented by nodejs are not part of the JS specification. The environment created by isolated-vm is a *pure* JS environment. For instance `setTimeout` and `console` are also not defined because they are part of the HTML specification.
