### ISSUE TITLE
Script.run*() returns undefined on non-primitive transferable value

### ISSUE THREAD

**Issue by Fayti1703** [laverdet/isolated-vm#88]
When a script's last expression returns a Transferable which is not a primitive value (for example, an instance of `ivm.Reference`), Script.run/Script.runSync return `undefined`, despite [the documentation](https://github.com/laverdet/isolated-vm#scriptruncontext-options-promise) telling us it should return the value instead.

This happens because [the relevant code](https://github.com/laverdet/isolated-vm/blob/master/src/script_handle.cc#L64) calls `ExternalCopy::CopyIfPrimitive`.

A possible quick fix would be changing that call to `ExternalCopy::Copy` and catching the `std::logic_error` that may be thrown.

EDIT: I have since discovered that this "quick fix" causes an Error to be thrown if the last expression in a script returns a function, so a more complex solution may be more appropriate

**Comment by laverdet** [comment]
Thanks for pointing out the inconsistency here. This is fixed in master now.

**Comment by Fayti1703** [comment]
Sorry for the ping @laverdet, but is there any particular reason this change isn't reflected on the yarn/npm packages yet?

**Comment by laverdet** [comment]
It just didn't seem like a huge deal worth pushing a new npm release. Is this blocking you on something?

**Comment by envis10n** [comment]
Being able to transfer out transferables is important to my project, and without removing this as a dependency from package.json and removing it from yarn.lock I have to keep replacing the module with the repo version, as it just rebuilds it with the old broken version when I add something to my project.

**Comment by laverdet** [comment]
Ok this is on npm now as 1.7.5

**Comment by envis10n** [comment]
Thanks!
