### ISSUE TITLE
[Question] Is it possible to have C++ standard library shipped with the module?

### ISSUE THREAD

**Issue by ErkoKnoll** [laverdet/isolated-vm#91]
Hi,

I have a rather peculiar problem. I need to run isolated-vm on a Linux environment where I cannot modify a single thing. And the problem is that the Linux environment comes with an old C++ standard library and I'm getting the following error: "/var/lang/lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /var/task/node_modules/isolated-vm/build/Release/isolated_vm.node)". 

By installing a newer g++ the problem is solved as it would include a newer libstdc++.so.6, but unfortunately I cannot do that. I also cannot modify LD_LIBRARY_PATH to have newer libstdc++.so.6 included before the old one gets included when Node process starts.

So the only thing left I can think of is to have libstdc++.so.6 included with the distribution in a way the module wouldn't want to load it from operating systems library. I don't know much about C++, but would it be theoretically possible?

**Comment by laverdet** [comment]
You can add -static-libgcc -static-libstdc++ to LDFLAGS to statically link libgcc and libstdc++.

```
$ LDFLAGS='-static-libgcc -static-libstdc++' node-gyp rebuild -j 4
...
$ ldd build/Release/isolated_vm.node
	linux-vdso.so.1 (0x00007fff2bbff000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f06d8c65000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f06d882e000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f06d847f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f06d93f3000)
```

**Comment by ErkoKnoll** [comment]
It worked, thanks a lot!
