### ISSUE TITLE
Trouble transferring TensorFlow.js

### ISSUE THREAD

**Issue by rkotcherr** [laverdet/isolated-vm#97]
The examples provided have helped me to successfully transfer simple datatypes for my application, namely function and plain javascript objects.

I'd now like to provide a reference to tensorflow so that my users can load and use models that they develop on their own machines.

# What I tried first:

On the top-level, I am importing tensorflow as `tf`, and then creating an `ExternalCopy`:

```
const tf = require('@tensorflow/tfjs-node');
jail.setSync('_tf', new ivm.ExternalCopy(tf));
```

From inside the isolate I am calling .copy on the `ExternalCopy`:

```
global.tf = _tf.copy();
```

and ending up with the error:

```
TypeError: function browserFiles(files) {
    return new BrowserFiles(files);
} could not be cloned.
```

I've actually done the same thing on other, simpler objects, successfully. This leads me to my two questions:
1. Why are some thing not clone-able?
2. What is recommended in this case? I was thinking that I could stub out the functions I need here, namely `loadModel`, but given that this is a ML library that would require very very large files to be transferred between isolates. It seems like the wrong approach.

**Comment by laverdet** [comment]
Oh and on the topic of transferring large files please take a look at the `transfer` option on `ExternalCopy`. It allows you to move an `ArrayBuffer` to an isolate instantaneously.
